// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

static AGGREGATE_WINDOW_DURATION_SECONDS_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "aggregate_window_duration_seconds",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

static AGGREGATE_FLUSH_INTERVAL_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "aggregate_flush_interval",
    env_vars: &[],
    value_type: ValueType::String,
    default: None,
};

static AGGREGATE_CONTEXT_LIMIT_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "aggregate_context_limit",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

static COUNTER_EXPIRY_SECONDS_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "counter_expiry_seconds",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

static AGGREGATE_PASSTHROUGH_IDLE_FLUSH_TIMEOUT_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "aggregate_passthrough_idle_flush_timeout",
    env_vars: &[],
    value_type: ValueType::String,
    default: None,
};

crate::declare_annotations! {
    /// `aggregate_window_duration_seconds`
    AGGREGATE_WINDOW_DURATION_SECONDS = SalukiAnnotation {
        schema: &AGGREGATE_WINDOW_DURATION_SECONDS_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
    /// `aggregate_flush_interval`
    AGGREGATE_FLUSH_INTERVAL = SalukiAnnotation {
        schema: &AGGREGATE_FLUSH_INTERVAL_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#"{"secs": 42, "nanos": 0}"#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
    /// `aggregate_context_limit`
    AGGREGATE_CONTEXT_LIMIT = SalukiAnnotation {
        schema: &AGGREGATE_CONTEXT_LIMIT_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
    /// `dogstatsd_flush_incomplete_buckets`-Flush open buckets on shutdown
    DOGSTATSD_FLUSH_INCOMPLETE_BUCKETS = SalukiAnnotation {
        schema: &schema::DOGSTATSD_FLUSH_INCOMPLETE_BUCKETS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &["aggregate_flush_open_windows"],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
    /// `counter_expiry_seconds`
    COUNTER_EXPIRY_SECONDS = SalukiAnnotation {
        schema: &COUNTER_EXPIRY_SECONDS_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &["dogstatsd_expiry_seconds"],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
    /// `dogstatsd_no_aggregation_pipeline`-Enable no-agg timestamped path
    DOGSTATSD_NO_AGGREGATION_PIPELINE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_NO_AGGREGATION_PIPELINE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION, structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
    /// `aggregate_passthrough_idle_flush_timeout`
    AGGREGATE_PASSTHROUGH_IDLE_FLUSH_TIMEOUT = SalukiAnnotation {
        schema: &AGGREGATE_PASSTHROUGH_IDLE_FLUSH_TIMEOUT_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#"{"secs": 42, "nanos": 0}"#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
    /// `histogram_aggregates`-Histogram aggregate statistics
    HISTOGRAM_AGGREGATES = SalukiAnnotation {
        schema: &schema::HISTOGRAM_AGGREGATES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#"["count"]"#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
    /// `histogram_copy_to_distribution`-Copy histograms to distributions
    HISTOGRAM_COPY_TO_DISTRIBUTION = SalukiAnnotation {
        schema: &schema::HISTOGRAM_COPY_TO_DISTRIBUTION,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
    /// `histogram_copy_to_distribution_prefix`-Prefix for hist-to-dist copies
    HISTOGRAM_COPY_TO_DISTRIBUTION_PREFIX = SalukiAnnotation {
        schema: &schema::HISTOGRAM_COPY_TO_DISTRIBUTION_PREFIX,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::AGGREGATE_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks]),
    };
}
