// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `cri_connection_timeout`-CRI container runtime connection timeout (s)
    CRI_CONNECTION_TIMEOUT = SalukiAnnotation {
        schema: &schema::CRI_CONNECTION_TIMEOUT,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::CONTAINERD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `cri_query_timeout`-CRI container runtime query timeout (s)
    CRI_QUERY_TIMEOUT = SalukiAnnotation {
        schema: &schema::CRI_QUERY_TIMEOUT,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::CONTAINERD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
}
