// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

static DOGSTATSD_ALLOW_CONTEXT_HEAP_ALLOCS_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_allow_context_heap_allocs",
    env_vars: &[],
    value_type: ValueType::Bool,
    default: Some("true"),
};

static DOGSTATSD_AUTOSCALE_UDP_LISTENERS_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_autoscale_udp_listeners",
    env_vars: &[],
    value_type: ValueType::Bool,
    default: Some("false"),
};

static DOGSTATSD_BUFFER_COUNT_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_buffer_count",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

static DOGSTATSD_CACHED_CONTEXTS_LIMIT_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_cached_contexts_limit",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

static DOGSTATSD_CACHED_TAGSETS_LIMIT_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_cached_tagsets_limit",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

static DOGSTATSD_MINIMUM_SAMPLE_RATE_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_minimum_sample_rate",
    env_vars: &[],
    value_type: ValueType::Float,
    default: None,
};

static DOGSTATSD_PERMISSIVE_DECODING_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_permissive_decoding",
    env_vars: &[],
    value_type: ValueType::Bool,
    default: Some("true"),
};

static DOGSTATSD_STRING_INTERNER_SIZE_BYTES_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_string_interner_size_bytes",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

static DOGSTATSD_TCP_PORT_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_tcp_port",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

crate::declare_annotations! {
    /// `bind_host`-Global listen host fallback
    BIND_HOST = SalukiAnnotation {
        schema: &schema::BIND_HOST,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_buffer_size`-Receive buffer size (bytes)
    DOGSTATSD_BUFFER_SIZE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_BUFFER_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_capture_depth`-Traffic capture channel depth
    DOGSTATSD_CAPTURE_DEPTH = SalukiAnnotation {
        schema: &schema::DOGSTATSD_CAPTURE_DEPTH,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_capture_path`-Traffic capture file location
    DOGSTATSD_CAPTURE_PATH = SalukiAnnotation {
        schema: &schema::DOGSTATSD_CAPTURE_PATH,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_context_expiry_seconds`-Context cache TTL (seconds)
    DOGSTATSD_CONTEXT_EXPIRY_SECONDS = SalukiAnnotation {
        schema: &schema::DOGSTATSD_CONTEXT_EXPIRY_SECONDS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_entity_id_precedence`-Entity ID over auto-detection
    DOGSTATSD_ENTITY_ID_PRECEDENCE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_ENTITY_ID_PRECEDENCE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_DOGSTATSD_ENTITY_ID_PRECEDENCE"]),
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_eol_required`-Require newline-terminated messages
    DOGSTATSD_EOL_REQUIRED = SalukiAnnotation {
        schema: &schema::DOGSTATSD_EOL_REQUIRED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#"["udp"]"#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_non_local_traffic`-Accept non-localhost UDP/TCP
    DOGSTATSD_NON_LOCAL_TRAFFIC = SalukiAnnotation {
        schema: &schema::DOGSTATSD_NON_LOCAL_TRAFFIC,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_origin_detection`-Enable UDS origin detection
    DOGSTATSD_ORIGIN_DETECTION = SalukiAnnotation {
        schema: &schema::DOGSTATSD_ORIGIN_DETECTION,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_DOGSTATSD_ORIGIN_DETECTION"]),
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_origin_detection_client`-Honor client origin proto fields
    DOGSTATSD_ORIGIN_DETECTION_CLIENT = SalukiAnnotation {
        schema: &schema::DOGSTATSD_ORIGIN_DETECTION_CLIENT,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_DOGSTATSD_ORIGIN_DETECTION_CLIENT"]),
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_origin_optout_enabled`-Allow clients to opt out origin
    DOGSTATSD_ORIGIN_OPTOUT_ENABLED = SalukiAnnotation {
        schema: &schema::DOGSTATSD_ORIGIN_OPTOUT_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_DOGSTATSD_ORIGIN_OPTOUT_ENABLED"]),
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_port`-UDP listen port
    DOGSTATSD_PORT = SalukiAnnotation {
        schema: &schema::DOGSTATSD_PORT,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_socket`-UDS datagram socket path
    DOGSTATSD_SOCKET = SalukiAnnotation {
        schema: &schema::DOGSTATSD_SOCKET,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_so_rcvbuf`-Socket receive buffer size
    DOGSTATSD_SO_RCVBUF = SalukiAnnotation {
        schema: &schema::DOGSTATSD_SO_RCVBUF,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_stream_socket`-UDS stream socket path
    DOGSTATSD_STREAM_SOCKET = SalukiAnnotation {
        schema: &schema::DOGSTATSD_STREAM_SOCKET,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_stream_log_too_big`-Log oversized UDS stream frames
    DOGSTATSD_STREAM_LOG_TOO_BIG = SalukiAnnotation {
        schema: &schema::DOGSTATSD_STREAM_LOG_TOO_BIG,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `statsd_forward_host`-UDP packet forwarding destination host
    STATSD_FORWARD_HOST = SalukiAnnotation {
        schema: &schema::STATSD_FORWARD_HOST,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#""127.0.0.1""#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `statsd_forward_port`-UDP packet forwarding destination port
    STATSD_FORWARD_PORT = SalukiAnnotation {
        schema: &schema::STATSD_FORWARD_PORT,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: Some("9125"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_string_interner_size`-String interner capacity
    DOGSTATSD_STRING_INTERNER_SIZE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_STRING_INTERNER_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_tag_cardinality`-Default tag cardinality level
    DOGSTATSD_TAG_CARDINALITY = SalukiAnnotation {
        schema: &schema::DOGSTATSD_TAG_CARDINALITY,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_DOGSTATSD_TAG_CARDINALITY"]),
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#""high""#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_tags`-Extra tags added to all DSD data
    DOGSTATSD_TAGS = SalukiAnnotation {
        schema: &schema::DOGSTATSD_TAGS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `provider_kind`-Provider kind static tag
    PROVIDER_KIND = SalukiAnnotation {
        schema: &schema::PROVIDER_KIND,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_PROVIDER_KIND"]),
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `origin_detection_unified`-Unified origin detection mode
    ORIGIN_DETECTION_UNIFIED = SalukiAnnotation {
        schema: &schema::ORIGIN_DETECTION_UNIFIED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_ORIGIN_DETECTION_UNIFIED"]),
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_log_file`-DSD dedicated log file path
    DOGSTATSD_LOG_FILE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_LOG_FILE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_DEBUG_LOG_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_log_file_max_rolls`-DSD log file max roll count
    DOGSTATSD_LOG_FILE_MAX_ROLLS = SalukiAnnotation {
        schema: &schema::DOGSTATSD_LOG_FILE_MAX_ROLLS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_DEBUG_LOG_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_log_file_max_size`-DSD log file max size
    DOGSTATSD_LOG_FILE_MAX_SIZE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_LOG_FILE_MAX_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_DEBUG_LOG_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#""42MB""#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_logging_enabled`-Enables DSD metric logging
    DOGSTATSD_LOGGING_ENABLED = SalukiAnnotation {
        schema: &schema::DOGSTATSD_LOGGING_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_DEBUG_LOG_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_metrics_stats_enable`-Enable per-metric debug stats
    DOGSTATSD_METRICS_STATS_ENABLE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_METRICS_STATS_ENABLE,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_DEBUG_LOG_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_allow_context_heap_allocs`
    DOGSTATSD_ALLOW_CONTEXT_HEAP_ALLOCS = SalukiAnnotation {
        schema: &DOGSTATSD_ALLOW_CONTEXT_HEAP_ALLOCS_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_autoscale_udp_listeners`
    DOGSTATSD_AUTOSCALE_UDP_LISTENERS = SalukiAnnotation {
        schema: &DOGSTATSD_AUTOSCALE_UDP_LISTENERS_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_buffer_count`
    DOGSTATSD_BUFFER_COUNT = SalukiAnnotation {
        schema: &DOGSTATSD_BUFFER_COUNT_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_cached_contexts_limit`
    DOGSTATSD_CACHED_CONTEXTS_LIMIT = SalukiAnnotation {
        schema: &DOGSTATSD_CACHED_CONTEXTS_LIMIT_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_cached_tagsets_limit`
    DOGSTATSD_CACHED_TAGSETS_LIMIT = SalukiAnnotation {
        schema: &DOGSTATSD_CACHED_TAGSETS_LIMIT_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_minimum_sample_rate`
    DOGSTATSD_MINIMUM_SAMPLE_RATE = SalukiAnnotation {
        schema: &DOGSTATSD_MINIMUM_SAMPLE_RATE_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_permissive_decoding`
    DOGSTATSD_PERMISSIVE_DECODING = SalukiAnnotation {
        schema: &DOGSTATSD_PERMISSIVE_DECODING_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_string_interner_size_bytes`
    DOGSTATSD_STRING_INTERNER_SIZE_BYTES = SalukiAnnotation {
        schema: &DOGSTATSD_STRING_INTERNER_SIZE_BYTES_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_tcp_port`
    DOGSTATSD_TCP_PORT = SalukiAnnotation {
        schema: &DOGSTATSD_TCP_PORT_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `enable_payloads.events`-Allow sending event payloads
    ENABLE_PAYLOADS_EVENTS = SalukiAnnotation {
        schema: &schema::ENABLE_PAYLOADS_EVENTS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `enable_payloads.series`-Allow sending series payloads
    ENABLE_PAYLOADS_SERIES = SalukiAnnotation {
        schema: &schema::ENABLE_PAYLOADS_SERIES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `enable_payloads.service_checks`-Allow sending service check payloads
    ENABLE_PAYLOADS_SERVICE_CHECKS = SalukiAnnotation {
        schema: &schema::ENABLE_PAYLOADS_SERVICE_CHECKS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `enable_payloads.sketches`-Allow sending sketch payloads
    ENABLE_PAYLOADS_SKETCHES = SalukiAnnotation {
        schema: &schema::ENABLE_PAYLOADS_SKETCHES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
}
