// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `metric_filterlist`-Metric name blocklist
    METRIC_FILTERLIST = SalukiAnnotation {
        schema: &schema::METRIC_FILTERLIST,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_PREFIX_FILTER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `metric_filterlist_match_prefix`-Blocklist uses prefix matching
    METRIC_FILTERLIST_MATCH_PREFIX = SalukiAnnotation {
        schema: &schema::METRIC_FILTERLIST_MATCH_PREFIX,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_PREFIX_FILTER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `statsd_metric_blocklist`-List of metric names to block/drop
    STATSD_METRIC_BLOCKLIST = SalukiAnnotation {
        schema: &schema::STATSD_METRIC_BLOCKLIST,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_PREFIX_FILTER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `statsd_metric_blocklist_match_prefix`-Treat blocklist entries as prefixes
    STATSD_METRIC_BLOCKLIST_MATCH_PREFIX = SalukiAnnotation {
        schema: &schema::STATSD_METRIC_BLOCKLIST_MATCH_PREFIX,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_PREFIX_FILTER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `statsd_metric_namespace`-Prefix prepended to all metric names
    STATSD_METRIC_NAMESPACE = SalukiAnnotation {
        schema: &schema::STATSD_METRIC_NAMESPACE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_PREFIX_FILTER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `statsd_metric_namespace_blacklist`-Prefixes exempt from namespace
    STATSD_METRIC_NAMESPACE_BLACKLIST = SalukiAnnotation {
        schema: &schema::STATSD_METRIC_NAMESPACE_BLACKLIST,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &["statsd_metric_namespace_blocklist"],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_PREFIX_FILTER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
}
