// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

static DOGSTATSD_MAPPER_STRING_INTERNER_SIZE_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "dogstatsd_mapper_string_interner_size",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

crate::declare_annotations! {
    /// `dogstatsd_mapper_cache_size`-Mapper result LRU cache size
    DOGSTATSD_MAPPER_CACHE_SIZE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MAPPER_CACHE_SIZE,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_MAPPER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mapper_profiles`-Metric mapping profile definitions
    DOGSTATSD_MAPPER_PROFILES = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MAPPER_PROFILES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_MAPPER_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#"[{"name":"test","prefix":"test.","mappings":[]}]"#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mapper_string_interner_size`
    DOGSTATSD_MAPPER_STRING_INTERNER_SIZE = SalukiAnnotation {
        schema: &DOGSTATSD_MAPPER_STRING_INTERNER_SIZE_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DOGSTATSD_MAPPER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
}
