// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

static FLUSH_TIMEOUT_SECS_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "flush_timeout_secs",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

static SERIALIZER_MAX_METRICS_PER_PAYLOAD_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "serializer_max_metrics_per_payload",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

crate::declare_annotations! {
    /// `serializer_compressor_kind`-Payload compression algorithm
    SERIALIZER_COMPRESSOR_KIND = SalukiAnnotation {
        schema: &schema::SERIALIZER_COMPRESSOR_KIND,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `serializer_zstd_compressor_level`-Zstd compression level (Agent)
    SERIALIZER_ZSTD_COMPRESSOR_LEVEL = SalukiAnnotation {
        schema: &schema::SERIALIZER_ZSTD_COMPRESSOR_LEVEL,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `flush_timeout_secs`
    FLUSH_TIMEOUT_SECS = SalukiAnnotation {
        schema: &FLUSH_TIMEOUT_SECS_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::Traces, Pipeline::DogStatsD]),
    };
    /// `serializer_max_metrics_per_payload`
    SERIALIZER_MAX_METRICS_PER_PAYLOAD = SalukiAnnotation {
        schema: &SERIALIZER_MAX_METRICS_PER_PAYLOAD_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `log_payloads`-Debug-log decoded payload contents before encoding
    LOG_PAYLOADS = SalukiAnnotation {
        schema: &schema::LOG_PAYLOADS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD, Pipeline::Traces]),
    };
    /// `serializer_max_payload_size`-Max compressed payload size (generic)
    SERIALIZER_MAX_PAYLOAD_SIZE = SalukiAnnotation {
        schema: &schema::SERIALIZER_MAX_PAYLOAD_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `serializer_max_uncompressed_payload_size`-Max uncompressed payload size (generic)
    SERIALIZER_MAX_UNCOMPRESSED_PAYLOAD_SIZE = SalukiAnnotation {
        schema: &schema::SERIALIZER_MAX_UNCOMPRESSED_PAYLOAD_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `serializer_max_series_payload_size`-Max compressed V2 series payload size
    SERIALIZER_MAX_SERIES_PAYLOAD_SIZE = SalukiAnnotation {
        schema: &schema::SERIALIZER_MAX_SERIES_PAYLOAD_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `serializer_max_series_uncompressed_payload_size`-Max uncompressed V2 series payload size
    SERIALIZER_MAX_SERIES_UNCOMPRESSED_PAYLOAD_SIZE = SalukiAnnotation {
        schema: &schema::SERIALIZER_MAX_SERIES_UNCOMPRESSED_PAYLOAD_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `serializer_max_series_points_per_payload`-Max data points per series payload
    SERIALIZER_MAX_SERIES_POINTS_PER_PAYLOAD = SalukiAnnotation {
        schema: &schema::SERIALIZER_MAX_SERIES_POINTS_PER_PAYLOAD,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `use_v2_api.series`-Send series via V2 protobuf endpoint
    USE_V2_API_SERIES = SalukiAnnotation {
        schema: &schema::USE_V2_API_SERIES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `env`-Agent environment name
    ENV = SalukiAnnotation {
        schema: &schema::ENV,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `serializer_experimental_use_v3_api.compression_level`-V3 API zstd compression level
    SERIALIZER_EXPERIMENTAL_USE_V3_API_COMPRESSION_LEVEL = SalukiAnnotation {
        schema: &schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_COMPRESSION_LEVEL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `serializer_experimental_use_v3_api.series.endpoints`-Endpoints enabled for V3 series API
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_ENDPOINTS = SalukiAnnotation {
        schema: &schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_ENDPOINTS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `serializer_experimental_use_v3_api.sketches.endpoints`-Endpoints enabling v3 sketches API
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_ENDPOINTS = SalukiAnnotation {
        schema: &schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_ENDPOINTS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `use_v3_api.series.enabled`-Global V3 series mode
    USE_V3_API_SERIES_ENABLED = SalukiAnnotation {
        schema: &schema::USE_V3_API_SERIES_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_USE_V3_API_SERIES_ENABLED"]),
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `use_v3_api.series.endpoints`-Per-endpoint V3 series modes
    USE_V3_API_SERIES_ENDPOINTS = SalukiAnnotation {
        schema: &schema::USE_V3_API_SERIES_ENDPOINTS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_USE_V3_API_SERIES_ENDPOINTS"]),
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: Some(r#""{\"http://datadog.example.com\":\"false\"}""#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
}
