// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `api_key`-API key for endpoint auth
    API_KEY = SalukiAnnotation {
        schema: &schema::API_KEY,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `site`-Datadog site domain
    SITE = SalukiAnnotation {
        schema: &schema::SITE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `dd_url`-Override intake endpoint URL
    DD_URL = SalukiAnnotation {
        schema: &schema::DD_URL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `observability_pipelines_worker.metrics.enabled`-Route metrics to OPW instance
    OBSERVABILITY_PIPELINES_WORKER_METRICS_ENABLED = SalukiAnnotation {
        schema: &schema::OBSERVABILITY_PIPELINES_WORKER_METRICS_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_OBSERVABILITY_PIPELINES_WORKER_METRICS_ENABLED"]),
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION, structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `observability_pipelines_worker.metrics.url`-OPW metrics intake URL
    OBSERVABILITY_PIPELINES_WORKER_METRICS_URL = SalukiAnnotation {
        schema: &schema::OBSERVABILITY_PIPELINES_WORKER_METRICS_URL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_OBSERVABILITY_PIPELINES_WORKER_METRICS_URL"]),
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION, structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `vector.metrics.enabled`-Route metrics to OPW (legacy alias)
    VECTOR_METRICS_ENABLED = SalukiAnnotation {
        schema: &schema::VECTOR_METRICS_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_VECTOR_METRICS_ENABLED"]),
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION, structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `vector.metrics.url`-OPW metrics intake URL (legacy alias)
    VECTOR_METRICS_URL = SalukiAnnotation {
        schema: &schema::VECTOR_METRICS_URL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_VECTOR_METRICS_URL"]),
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION, structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `additional_endpoints`-Dual-ship to extra endpoints
    ADDITIONAL_ENDPOINTS = SalukiAnnotation {
        schema: &schema::ADDITIONAL_ENDPOINTS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION, structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#"{"smoke-host-1.example.com": ["smoke-api-key"]}"#),
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_num_workers`-Concurrent forwarder workers
    FORWARDER_NUM_WORKERS = SalukiAnnotation {
        schema: &schema::FORWARDER_NUM_WORKERS,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_timeout`-Forwarder HTTP request timeout
    FORWARDER_TIMEOUT = SalukiAnnotation {
        schema: &schema::FORWARDER_TIMEOUT,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_high_prio_buffer_size`-High-priority request queue size
    FORWARDER_HIGH_PRIO_BUFFER_SIZE = SalukiAnnotation {
        schema: &schema::FORWARDER_HIGH_PRIO_BUFFER_SIZE,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_connection_reset_interval`-HTTP conn reset interval (secs)
    FORWARDER_CONNECTION_RESET_INTERVAL = SalukiAnnotation {
        schema: &schema::FORWARDER_CONNECTION_RESET_INTERVAL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_http_protocol`-HTTP version selection (auto/http1/http2)
    FORWARDER_HTTP_PROTOCOL = SalukiAnnotation {
        schema: &schema::FORWARDER_HTTP_PROTOCOL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#""http1""#),
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `skip_ssl_validation`-Skip TLS cert validation
    SKIP_SSL_VALIDATION = SalukiAnnotation {
        schema: &schema::SKIP_SSL_VALIDATION,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_SKIP_SSL_VALIDATION"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `sslkeylogfile`-Write TLS session keys to file
    SSLKEYLOGFILE = SalukiAnnotation {
        schema: &schema::SSLKEYLOGFILE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_SSLKEYLOGFILE"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#""/tmp/saluki-sslkeylogfile""#),
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `min_tls_version`-Minimum TLS version for HTTPS connections
    MIN_TLS_VERSION = SalukiAnnotation {
        schema: &schema::MIN_TLS_VERSION,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_MIN_TLS_VERSION"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `allow_arbitrary_tags`-Relax backend tag validation via HTTP header
    ALLOW_ARBITRARY_TAGS = SalukiAnnotation {
        schema: &schema::ALLOW_ARBITRARY_TAGS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_ALLOW_ARBITRARY_TAGS"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_backoff_base`-Retry backoff base (secs)
    FORWARDER_BACKOFF_BASE = SalukiAnnotation {
        schema: &schema::FORWARDER_BACKOFF_BASE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_backoff_factor`-Retry backoff jitter factor
    FORWARDER_BACKOFF_FACTOR = SalukiAnnotation {
        schema: &schema::FORWARDER_BACKOFF_FACTOR,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_backoff_max`-Retry backoff ceiling (secs)
    FORWARDER_BACKOFF_MAX = SalukiAnnotation {
        schema: &schema::FORWARDER_BACKOFF_MAX,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_recovery_interval`-Backoff recovery decrease factor
    FORWARDER_RECOVERY_INTERVAL = SalukiAnnotation {
        schema: &schema::FORWARDER_RECOVERY_INTERVAL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_recovery_reset`-Reset errors on success
    FORWARDER_RECOVERY_RESET = SalukiAnnotation {
        schema: &schema::FORWARDER_RECOVERY_RESET,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_retry_queue_max_size`-Retry queue max size (deprecated)
    FORWARDER_RETRY_QUEUE_MAX_SIZE = SalukiAnnotation {
        schema: &schema::FORWARDER_RETRY_QUEUE_MAX_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_retry_queue_payloads_max_size`-Retry queue max size (bytes)
    FORWARDER_RETRY_QUEUE_PAYLOADS_MAX_SIZE = SalukiAnnotation {
        schema: &schema::FORWARDER_RETRY_QUEUE_PAYLOADS_MAX_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_storage_max_disk_ratio`-Max disk usage ratio for retry
    FORWARDER_STORAGE_MAX_DISK_RATIO = SalukiAnnotation {
        schema: &schema::FORWARDER_STORAGE_MAX_DISK_RATIO,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_storage_max_size_in_bytes`-Max on-disk retry storage size
    FORWARDER_STORAGE_MAX_SIZE_IN_BYTES = SalukiAnnotation {
        schema: &schema::FORWARDER_STORAGE_MAX_SIZE_IN_BYTES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_storage_path`-On-disk retry storage directory
    FORWARDER_STORAGE_PATH = SalukiAnnotation {
        schema: &schema::FORWARDER_STORAGE_PATH,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_outdated_file_in_days`-Days before retry files are deleted
    FORWARDER_OUTDATED_FILE_IN_DAYS = SalukiAnnotation {
        schema: &schema::FORWARDER_OUTDATED_FILE_IN_DAYS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_apikey_validation_interval`-API key check interval (minutes)
    FORWARDER_APIKEY_VALIDATION_INTERVAL = SalukiAnnotation {
        schema: &schema::FORWARDER_APIKEY_VALIDATION_INTERVAL,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_flush_to_disk_mem_ratio`-Mem-to-disk flush ratio
    FORWARDER_FLUSH_TO_DISK_MEM_RATIO = SalukiAnnotation {
        schema: &schema::FORWARDER_FLUSH_TO_DISK_MEM_RATIO,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_max_concurrent_requests`-Max concurrent HTTP requests
    FORWARDER_MAX_CONCURRENT_REQUESTS = SalukiAnnotation {
        schema: &schema::FORWARDER_MAX_CONCURRENT_REQUESTS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_retry_queue_capacity_time_interval_sec`-Retry queue time-based capacity
    FORWARDER_RETRY_QUEUE_CAPACITY_TIME_INTERVAL_SEC = SalukiAnnotation {
        schema: &schema::FORWARDER_RETRY_QUEUE_CAPACITY_TIME_INTERVAL_SEC,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `observability_pipelines_worker.metrics.use_v3_api.series`-Use V3 series for OPW
    OBSERVABILITY_PIPELINES_WORKER_METRICS_USE_V3_API_SERIES = SalukiAnnotation {
        schema: &schema::OBSERVABILITY_PIPELINES_WORKER_METRICS_USE_V3_API_SERIES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_OBSERVABILITY_PIPELINES_WORKER_METRICS_USE_V3_API_SERIES"]),
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION, structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `vector.metrics.use_v3_api.series`-Use V3 series for Vector
    VECTOR_METRICS_USE_V3_API_SERIES = SalukiAnnotation {
        schema: &schema::VECTOR_METRICS_USE_V3_API_SERIES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_VECTOR_METRICS_USE_V3_API_SERIES"]),
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION, structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
}
