// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `aggregator_stop_timeout`-Timeout (s) for aggregator flush on stop
    AGGREGATOR_STOP_TIMEOUT = SalukiAnnotation {
        schema: &schema::AGGREGATOR_STOP_TIMEOUT,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::GET_TYPED],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `log_format_rfc3339`-Use RFC 3339 timestamps in log output
    LOG_FORMAT_RFC3339 = SalukiAnnotation {
        schema: &schema::LOG_FORMAT_RFC3339,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::GET_TYPED],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `syslog_rfc`-Use RFC-style syslog header
    SYSLOG_RFC = SalukiAnnotation {
        schema: &schema::SYSLOG_RFC,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::GET_TYPED],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `syslog_uri`-Syslog destination URI
    SYSLOG_URI = SalukiAnnotation {
        schema: &schema::SYSLOG_URI,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::GET_TYPED],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_stop_timeout`-Timeout (s) for forwarder graceful stop
    FORWARDER_STOP_TIMEOUT = SalukiAnnotation {
        schema: &schema::FORWARDER_STOP_TIMEOUT,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::GET_TYPED],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `log_level`-Log verbosity directives
    LOG_LEVEL = SalukiAnnotation {
        schema: &schema::LOG_LEVEL,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::GET_TYPED],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
}
