// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

static LOGS_CONFIG_USE_GRPC_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "logs_config.use_grpc",
    env_vars: &[],
    value_type: ValueType::Bool,
    default: Some("false"),
};

crate::declare_annotations! {
    /// `logs_config.use_grpc`
    LOGS_CONFIG_USE_GRPC = SalukiAnnotation {
        schema: &LOGS_CONFIG_USE_GRPC_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::Otlp]),
    };
}
