// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `multi_region_failover.api_key`-API key for the failover-region endpoint
    MULTI_REGION_FAILOVER_API_KEY = SalukiAnnotation {
        schema: &schema::MULTI_REGION_FAILOVER_API_KEY,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_MULTI_REGION_FAILOVER_API_KEY"]),
        used_by: &[structs::MRF_CONFIGURATION],
        value_type_override: Some(ValueType::String),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `multi_region_failover.dd_url`-Failover intake URL
    MULTI_REGION_FAILOVER_DD_URL = SalukiAnnotation {
        schema: &schema::MULTI_REGION_FAILOVER_DD_URL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_MULTI_REGION_FAILOVER_DD_URL"]),
        used_by: &[structs::MRF_CONFIGURATION],
        value_type_override: Some(ValueType::String),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `multi_region_failover.enabled`-Enable multi-region failover mode
    MULTI_REGION_FAILOVER_ENABLED = SalukiAnnotation {
        schema: &schema::MULTI_REGION_FAILOVER_ENABLED,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_MULTI_REGION_FAILOVER_ENABLED"]),
        used_by: &[structs::MRF_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `multi_region_failover.failover_metrics`-Enable metrics forwarding to failover region
    MULTI_REGION_FAILOVER_FAILOVER_METRICS = SalukiAnnotation {
        schema: &schema::MULTI_REGION_FAILOVER_FAILOVER_METRICS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_MULTI_REGION_FAILOVER_FAILOVER_METRICS"]),
        used_by: &[structs::MRF_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `multi_region_failover.metric_allowlist`-Metric name allowlist for MRF forwarding
    MULTI_REGION_FAILOVER_METRIC_ALLOWLIST = SalukiAnnotation {
        schema: &schema::MULTI_REGION_FAILOVER_METRIC_ALLOWLIST,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_MULTI_REGION_FAILOVER_METRIC_ALLOWLIST"]),
        used_by: &[structs::MRF_CONFIGURATION],
        value_type_override: Some(ValueType::StringList),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `multi_region_failover.site`-Datadog site for the failover region
    MULTI_REGION_FAILOVER_SITE = SalukiAnnotation {
        schema: &schema::MULTI_REGION_FAILOVER_SITE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_MULTI_REGION_FAILOVER_SITE"]),
        used_by: &[structs::MRF_CONFIGURATION],
        value_type_override: Some(ValueType::String),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
}
