// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `proxy.http`-HTTP proxy URL
    PROXY_HTTP = SalukiAnnotation {
        schema: &schema::PROXY_HTTP,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_PROXY_HTTP", "HTTP_PROXY"]),
        used_by: &[structs::FORWARDER_CONFIGURATION, structs::PROXY_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `proxy.https`-HTTPS proxy URL
    PROXY_HTTPS = SalukiAnnotation {
        schema: &schema::PROXY_HTTPS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_PROXY_HTTPS", "HTTPS_PROXY"]),
        used_by: &[structs::FORWARDER_CONFIGURATION, structs::PROXY_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `proxy.no_proxy`-Hosts bypassing proxy
    PROXY_NO_PROXY = SalukiAnnotation {
        schema: &schema::PROXY_NO_PROXY,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_PROXY_NO_PROXY"]),
        used_by: &[structs::FORWARDER_CONFIGURATION, structs::PROXY_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `no_proxy_nonexact_match`-Domain/CIDR `no_proxy` matching
    NO_PROXY_NONEXACT_MATCH = SalukiAnnotation {
        schema: &schema::NO_PROXY_NONEXACT_MATCH,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_NO_PROXY_NONEXACT_MATCH"]),
        used_by: &[structs::FORWARDER_CONFIGURATION, structs::PROXY_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `use_proxy_for_cloud_metadata`-Proxy cloud metadata endpoints
    USE_PROXY_FOR_CLOUD_METADATA = SalukiAnnotation {
        schema: &schema::USE_PROXY_FOR_CLOUD_METADATA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_USE_PROXY_FOR_CLOUD_METADATA"]),
        used_by: &[structs::FORWARDER_CONFIGURATION, structs::PROXY_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
}
