// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `autoscaling.failover.enabled`-Enable autoscaling failover metric routing
    AUTOSCALING_FAILOVER_ENABLED = SalukiAnnotation {
        schema: &schema::AUTOSCALING_FAILOVER_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `autoscaling.failover.metrics`-Metric names forwarded to DCA for failover
    AUTOSCALING_FAILOVER_METRICS = SalukiAnnotation {
        schema: &schema::AUTOSCALING_FAILOVER_METRICS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: Some(r#"["container.memory.usage"]"#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `cluster_agent.auth_token`-Bearer token for Cluster Agent requests
    CLUSTER_AGENT_AUTH_TOKEN = SalukiAnnotation {
        schema: &schema::CLUSTER_AGENT_AUTH_TOKEN,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: Some(r#""cluster-agent-token""#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `cluster_agent.enabled`-Enable Cluster Agent communication
    CLUSTER_AGENT_ENABLED = SalukiAnnotation {
        schema: &schema::CLUSTER_AGENT_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `cluster_agent.kubernetes_service_name`-Cluster Agent Kubernetes service name
    CLUSTER_AGENT_KUBERNETES_SERVICE_NAME = SalukiAnnotation {
        schema: &schema::CLUSTER_AGENT_KUBERNETES_SERVICE_NAME,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: Some(r#""datadog-cluster-agent""#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `cluster_agent.url`-Cluster Agent HTTPS endpoint
    CLUSTER_AGENT_URL = SalukiAnnotation {
        schema: &schema::CLUSTER_AGENT_URL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: Some(r#""https://cluster-agent.example.com""#),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `cluster_name`-EKS Fargate cluster name static tag
    CLUSTER_NAME = SalukiAnnotation {
        schema: &schema::CLUSTER_NAME,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `eks_fargate`-Enable EKS Fargate static tags
    EKS_FARGATE = SalukiAnnotation {
        schema: &schema::EKS_FARGATE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `expected_tags_duration`-How long startup host tags are attached
    EXPECTED_TAGS_DURATION = SalukiAnnotation {
        schema: &schema::EXPECTED_TAGS_DURATION,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `hostname`-Forced hostname for emitted data
    HOSTNAME = SalukiAnnotation {
        schema: &schema::HOSTNAME,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `kubernetes_kubelet_nodename`-Kubernetes node name for EKS Fargate static tags
    KUBERNETES_KUBELET_NODENAME = SalukiAnnotation {
        schema: &schema::KUBERNETES_KUBELET_NODENAME,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `provider_kind`-Provider kind static tag
    PROVIDER_KIND = SalukiAnnotation {
        schema: &schema::PROVIDER_KIND,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_PROVIDER_KIND"]),
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Otlp]),
    };
    /// `run_path`-Runtime state directory
    RUN_PATH = SalukiAnnotation {
        schema: &schema::RUN_PATH,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TYPED_CONFIG_SYSTEM],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
}
