// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `apm_config.probabilistic_sampler.enabled`-APM probabilistic sampler enabled gate
    APM_CONFIG_PROBABILISTIC_SAMPLER_ENABLED = SalukiAnnotation {
        schema: &schema::APM_CONFIG_PROBABILISTIC_SAMPLER_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_SAMPLER_CONFIGURATION],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.probabilistic_sampler.sampling_percentage`-APM probabilistic sampler sampling percentage
    APM_CONFIG_PROBABILISTIC_SAMPLER_SAMPLING_PERCENTAGE = SalukiAnnotation {
        schema: &schema::APM_CONFIG_PROBABILISTIC_SAMPLER_SAMPLING_PERCENTAGE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_SAMPLER_CONFIGURATION],
        value_type_override: None,
        test_json: Some("50.0"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
}
