// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

static APM_CONFIG_OBFUSCATION_SQL_DBMS_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "apm_config.obfuscation.sql.dbms",
    env_vars: &[],
    value_type: ValueType::String,
    default: None,
};

static APM_CONFIG_OBFUSCATION_SQL_DOLLAR_QUOTED_FUNC_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "apm_config.obfuscation.sql.dollar_quoted_func",
    env_vars: &[],
    value_type: ValueType::Bool,
    default: None,
};

static APM_CONFIG_OBFUSCATION_SQL_KEEP_SQL_ALIAS_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "apm_config.obfuscation.sql.keep_sql_alias",
    env_vars: &[],
    value_type: ValueType::Bool,
    default: None,
};

static APM_CONFIG_OBFUSCATION_SQL_REPLACE_DIGITS_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "apm_config.obfuscation.sql.replace_digits",
    env_vars: &[],
    value_type: ValueType::Bool,
    default: None,
};

static APM_CONFIG_OBFUSCATION_SQL_TABLE_NAMES_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "apm_config.obfuscation.sql.table_names",
    env_vars: &[],
    value_type: ValueType::Bool,
    default: None,
};

crate::declare_annotations! {
    /// `apm_config.obfuscation.credit_cards.enabled`-apm_config.obfuscation.credit_cards.enabled
    APM_CONFIG_OBFUSCATION_CREDIT_CARDS_ENABLED = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_CREDIT_CARDS_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.credit_cards.keep_values`-apm_config.obfuscation.credit_cards.keep_values
    APM_CONFIG_OBFUSCATION_CREDIT_CARDS_KEEP_VALUES = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_CREDIT_CARDS_KEEP_VALUES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.credit_cards.luhn`-apm_config.obfuscation.credit_cards.luhn
    APM_CONFIG_OBFUSCATION_CREDIT_CARDS_LUHN = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_CREDIT_CARDS_LUHN,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.elasticsearch.enabled`-apm_config.obfuscation.elasticsearch.enabled
    APM_CONFIG_OBFUSCATION_ELASTICSEARCH_ENABLED = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_ELASTICSEARCH_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.elasticsearch.keep_values`-apm_config.obfuscation.elasticsearch.keep_values
    APM_CONFIG_OBFUSCATION_ELASTICSEARCH_KEEP_VALUES = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_ELASTICSEARCH_KEEP_VALUES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.elasticsearch.obfuscate_sql_values`-Obfuscate SQL values in ES queries
    APM_CONFIG_OBFUSCATION_ELASTICSEARCH_OBFUSCATE_SQL_VALUES = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_ELASTICSEARCH_OBFUSCATE_SQL_VALUES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.http.remove_paths_with_digits`-Strip numeric segments from HTTP paths
    APM_CONFIG_OBFUSCATION_HTTP_REMOVE_PATHS_WITH_DIGITS = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_HTTP_REMOVE_PATHS_WITH_DIGITS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.http.remove_query_string`-apm_config.obfuscation.http.remove_query_string
    APM_CONFIG_OBFUSCATION_HTTP_REMOVE_QUERY_STRING = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_HTTP_REMOVE_QUERY_STRING,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.memcached.enabled`-apm_config.obfuscation.memcached.enabled
    APM_CONFIG_OBFUSCATION_MEMCACHED_ENABLED = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_MEMCACHED_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.memcached.keep_command`-apm_config.obfuscation.memcached.keep_command
    APM_CONFIG_OBFUSCATION_MEMCACHED_KEEP_COMMAND = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_MEMCACHED_KEEP_COMMAND,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.mongodb.enabled`-apm_config.obfuscation.mongodb.enabled
    APM_CONFIG_OBFUSCATION_MONGODB_ENABLED = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_MONGODB_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.mongodb.keep_values`-apm_config.obfuscation.mongodb.keep_values
    APM_CONFIG_OBFUSCATION_MONGODB_KEEP_VALUES = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_MONGODB_KEEP_VALUES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.mongodb.obfuscate_sql_values`-Obfuscate SQL values in MongoDB queries
    APM_CONFIG_OBFUSCATION_MONGODB_OBFUSCATE_SQL_VALUES = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_MONGODB_OBFUSCATE_SQL_VALUES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.opensearch.enabled`-apm_config.obfuscation.opensearch.enabled
    APM_CONFIG_OBFUSCATION_OPENSEARCH_ENABLED = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_OPENSEARCH_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.opensearch.keep_values`-apm_config.obfuscation.opensearch.keep_values
    APM_CONFIG_OBFUSCATION_OPENSEARCH_KEEP_VALUES = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_OPENSEARCH_KEEP_VALUES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.opensearch.obfuscate_sql_values`-Obfuscate SQL values in OpenSearch queries
    APM_CONFIG_OBFUSCATION_OPENSEARCH_OBFUSCATE_SQL_VALUES = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_OPENSEARCH_OBFUSCATE_SQL_VALUES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.redis.enabled`-apm_config.obfuscation.redis.enabled
    APM_CONFIG_OBFUSCATION_REDIS_ENABLED = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_REDIS_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.redis.remove_all_args`-apm_config.obfuscation.redis.remove_all_args
    APM_CONFIG_OBFUSCATION_REDIS_REMOVE_ALL_ARGS = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_REDIS_REMOVE_ALL_ARGS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.sql.dbms`
    APM_CONFIG_OBFUSCATION_SQL_DBMS = SalukiAnnotation {
        schema: &APM_CONFIG_OBFUSCATION_SQL_DBMS_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.sql.dollar_quoted_func`
    APM_CONFIG_OBFUSCATION_SQL_DOLLAR_QUOTED_FUNC = SalukiAnnotation {
        schema: &APM_CONFIG_OBFUSCATION_SQL_DOLLAR_QUOTED_FUNC_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.sql.keep_sql_alias`
    APM_CONFIG_OBFUSCATION_SQL_KEEP_SQL_ALIAS = SalukiAnnotation {
        schema: &APM_CONFIG_OBFUSCATION_SQL_KEEP_SQL_ALIAS_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.sql.replace_digits`
    APM_CONFIG_OBFUSCATION_SQL_REPLACE_DIGITS = SalukiAnnotation {
        schema: &APM_CONFIG_OBFUSCATION_SQL_REPLACE_DIGITS_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.sql.table_names`
    APM_CONFIG_OBFUSCATION_SQL_TABLE_NAMES = SalukiAnnotation {
        schema: &APM_CONFIG_OBFUSCATION_SQL_TABLE_NAMES_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.valkey.enabled`-apm_config.obfuscation.valkey.enabled
    APM_CONFIG_OBFUSCATION_VALKEY_ENABLED = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_VALKEY_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: Some("true"),
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `apm_config.obfuscation.valkey.remove_all_args`-apm_config.obfuscation.valkey.remove_all_args
    APM_CONFIG_OBFUSCATION_VALKEY_REMOVE_ALL_ARGS = SalukiAnnotation {
        schema: &schema::APM_CONFIG_OBFUSCATION_VALKEY_REMOVE_ALL_ARGS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::TRACE_OBFUSCATION_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
}
