#!/usr/bin/env bash
set -euo pipefail

echo "[*] Running pre-commit checks..."

make check-fmt
make check-clippy
make check-licenses
make check-deny
make check-api-docs

echo "[*] Pre-commit checks passed."
