// @generated by build.rs from core_schema.yaml + schema_overlay.yaml — DO NOT EDIT
// Regenerate by running `cargo build -p datadog-agent-config`.
#![allow(clippy::all, dead_code, unused)]

use std::collections::HashMap;

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}

/// `DatadogConfiguration`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfiguration {
    #[serde(default, skip_serializing_if = ":: std :: collections :: HashMap::is_empty")]
    pub additional_endpoints: HashMap<String, Vec<String>>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub agent_ipc: Option<DatadogConfigurationAgentIpc>,

    /// When stopping the agent, the Aggregator will try to flush out data ready for
    /// aggregation (metrics, events, ...). Data are flushed to the Forwarder in order
    /// to be sent to Datadog, therefore the Agent might take at most
    /// 'aggregator_stop_timeout'+'forwarder_stop_timeout' seconds to exit.
    ///
    /// You can set the maximum amount of time, in seconds, allocated to the
    /// Aggregator to do so. You can disable this feature by setting
    /// 'aggregator_stop_timeout' to 0.
    #[serde(default = "defaults::default_u64::<i64, 2>")]
    pub aggregator_stop_timeout: i64,

    #[serde(default)]
    pub allow_arbitrary_tags: bool,

    /// The Datadog API key used by your Agent to submit metrics and events to Datadog.
    /// Create a new API key here: https://app.datadoghq.com/organization-settings/api-keys .
    /// Read more about API keys here: https://docs.datadoghq.com/account_management/api-app-keys/#api-keys .
    #[serde(default)]
    pub api_key: String,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub apm_config: Option<DatadogConfigurationApmConfig>,

    /// The host to listen on for Dogstatsd and traces. This is ignored by APM when
    /// `apm_config.apm_non_local_traffic` is enabled and ignored by DogStatsD when `dogstatsd_non_local_traffic`
    /// is enabled. The trace-agent uses this host to send metrics to.
    /// The `localhost` default value is invalid in IPv6 environments where dogstatsd listens on "::1".
    /// To solve this problem, ensure Dogstatsd is listening on IPv4 by setting this value to "127.0.0.1".
    #[serde(default)]
    pub bind_host: String,

    /// The port on which the IPC api listens.
    #[serde(default = "defaults::default_u64::<i64, 5001>")]
    pub cmd_port: i64,

    /// Configure the initial connection timeout in seconds.
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub cri_connection_timeout: i64,

    /// Configure the timeout in seconds for querying the CRI or Containerd API.
    #[serde(default = "defaults::default_u64::<i64, 5>")]
    pub cri_query_timeout: i64,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub data_plane: Option<DatadogConfigurationDataPlane>,

    /// The host of the Datadog intake server to send metrics to, only set this option
    /// if you need the Agent to send metrics to a custom URL, it overrides the site
    /// setting defined in "site". It does not affect APM, Logs, Remote Configuration, or Live Process intake which have their
    /// own "*_dd_url" settings.
    /// If DD_DD_URL and DD_URL are both set, DD_DD_URL is used in priority.
    #[serde(default = "defaults::datadog_configuration_dd_url")]
    pub dd_url: String,

    /// The buffer size use to receive statsd packets, in bytes.
    #[serde(default = "defaults::default_u64::<i64, 8192>")]
    pub dogstatsd_buffer_size: i64,

    #[serde(default)]
    pub dogstatsd_capture_depth: i64,

    #[serde(default)]
    pub dogstatsd_capture_path: String,

    #[serde(default = "defaults::default_u64::<i64, 20>")]
    pub dogstatsd_context_expiry_seconds: i64,

    /// Disable enriching Dogstatsd metrics with tags from "origin detection" when Entity-ID is set.
    #[serde(default)]
    pub dogstatsd_entity_id_precedence: bool,

    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub dogstatsd_eol_required: Vec<String>,

    #[serde(default)]
    pub dogstatsd_flush_incomplete_buckets: bool,

    #[serde(default)]
    pub dogstatsd_log_file: String,

    #[serde(default = "defaults::default_u64::<i64, 3>")]
    pub dogstatsd_log_file_max_rolls: i64,

    /// Maximum size of dogstatsd log file. Use either a size (for example, 10MB) or
    /// provide value in bytes (for example, 10485760.)
    #[serde(default = "defaults::datadog_configuration_dogstatsd_log_file_max_size")]
    pub dogstatsd_log_file_max_size: String,

    /// Set to true to write DogstatsD metrics received by the Agent to dogstats_stats log files.
    /// Requires `dogstatsd_stats_enable: true`.
    #[serde(default = "defaults::default_bool::<true>")]
    pub dogstatsd_logging_enabled: bool,

    /// Size of the cache (max number of mapping results) used by Dogstatsd mapping feature.
    #[serde(default = "defaults::default_u64::<i64, 1000>")]
    pub dogstatsd_mapper_cache_size: i64,

    /// The profiles will be used to convert parts of metrics names into tags.
    /// If a profile prefix is matched, other profiles won't be tried even if that profile matching rules doesn't match.
    /// The profiles and matching rules are processed in the order defined in this configuration.
    ///
    /// For each profile, following fields are available:
    ///   name (required): profile name
    ///   prefix (required): mapping only applies to metrics with the prefix. If set to `*`, it will match everything.
    ///   mappings: mapping rules, see below.
    /// For each mapping, following fields are available:
    ///   match (required): pattern for matching the incoming metric name e.g. `test.job.duration.*`
    ///   match_type (optional): pattern type can be `wildcard` (default) or `regex` e.g. `test\.job\.(\w+)\.(.*)`
    ///   name (required): the metric name the metric should be mapped to e.g. `test.job.duration`
    ///   tags (optional): list of key:value pair of tag key and tag value
    ///     The value can use $1, $2, etc, that will be replaced by the corresponding element capture by `match` pattern
    ///     This alternative syntax can also be used: ${1}, ${2}, etc
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub dogstatsd_mapper_profiles: Vec<::serde_json::Value>,

    /// Set this parameter to true to have DogStatsD collects basic statistics (count/last seen)
    /// about the metrics it processed. Use the Agent command "dogstatsd-stats" to visualize
    /// those statistics.
    #[serde(default)]
    pub dogstatsd_metrics_stats_enable: bool,

    /// Enable the no-aggregation pipeline in DogStatsD: a pipeline receiving metrics
    /// with timestamp and forwarding them to the intake without extra processing except
    /// for tagging.
    #[serde(default = "defaults::default_bool::<true>")]
    pub dogstatsd_no_aggregation_pipeline: bool,

    /// Set to true to make DogStatsD listen to non local UDP traffic.
    #[serde(default)]
    pub dogstatsd_non_local_traffic: bool,

    /// When using Unix Socket, DogStatsD can tag metrics with container metadata.
    /// If running DogStatsD in a container, host PID mode (e.g. with --pid=host) is required.
    #[serde(default)]
    pub dogstatsd_origin_detection: bool,

    /// Whether the Agent should use a client-provided container ID to enrich the metrics, events and service checks with container tags.
    /// Note: This requires using a client compatible with DogStatsD protocol version 1.2.
    #[serde(default)]
    pub dogstatsd_origin_detection_client: bool,

    #[serde(default = "defaults::default_bool::<true>")]
    pub dogstatsd_origin_optout_enabled: bool,

    /// Override the Agent DogStatsD port.
    /// Note: Make sure your client is sending to the same UDP port.
    #[serde(default = "defaults::default_u64::<i64, 8125>")]
    pub dogstatsd_port: i64,

    /// The number of bytes allocated to DogStatsD's socket receive buffer (POSIX system only).
    /// By default, the system sets this value. If you need to increase the size of this buffer
    /// but keep the OS default value the same, you can set DogStatsD's receive buffer size here.
    /// The maximum accepted value might change depending on the OS.
    #[serde(default)]
    pub dogstatsd_so_rcvbuf: i64,

    /// Listen for Dogstatsd metrics on a Unix Socket (*nix only).
    /// Set to a valid and existing filesystem path to enable.
    /// Set to "" to disable this feature.
    ///
    /// Please note that UDS receiver is not available in Windows.
    /// Enabling this setting may result in unexpected behavior.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub dogstatsd_socket: Option<String>,

    #[serde(default)]
    pub dogstatsd_stream_log_too_big: bool,

    #[serde(default)]
    pub dogstatsd_stream_socket: String,

    #[serde(default = "defaults::default_u64::<i64, 4096>")]
    pub dogstatsd_string_interner_size: i64,

    /// Configure the level of granularity of tags to send for DogStatsD metrics and events. Choices are:
    ///  * low: add tags about low-cardinality objects (clusters, hosts, deployments, container images, ...)
    ///  * orchestrator: add tags about pod, (in Kubernetes), or task (in ECS or Mesos) -level of cardinality
    ///  * high: add tags about high-cardinality objects (individual containers, user IDs in requests, ...)
    ///
    /// WARNING: sending container tags for dogstatsd metrics may create more metrics
    /// (one per container instead of one per host). This may impact your custom metrics billing.
    #[serde(default = "defaults::datadog_configuration_dogstatsd_tag_cardinality")]
    pub dogstatsd_tag_cardinality: String,

    /// Additional tags to append to all metrics, events and service checks received by
    /// this DogStatsD server.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub dogstatsd_tags: Vec<String>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub enable_payloads: Option<DatadogConfigurationEnablePayloads>,

    /// The environment name where the agent is running. Attached in-app to every
    /// metric, event, log, trace, and service check emitted by this Agent.
    #[serde(default)]
    pub env: String,

    #[serde(default = "defaults::default_u64::<i64, 60>")]
    pub forwarder_apikey_validation_interval: i64,

    /// Defines the rate of exponential growth, and the first retry interval range.
    /// Do not set a lower value than the default. You may increase it if you use a proxy that benefits from a
    /// higher rate of exponential growth.
    #[serde(default = "defaults::default_u64::<i64, 2>")]
    pub forwarder_backoff_base: i64,

    #[serde(default = "defaults::default_u64::<i64, 2>")]
    pub forwarder_backoff_factor: i64,

    /// Defines the maximum number of seconds to wait for a retry.
    /// Do not set a lower value than the default. You may increase it if you use a proxy that benefits from a
    /// higher maximum backoff time.
    #[serde(default = "defaults::default_u64::<i64, 64>")]
    pub forwarder_backoff_max: i64,

    #[serde(default)]
    pub forwarder_connection_reset_interval: i64,

    #[serde(default = "defaults::datadog_configuration_forwarder_flush_to_disk_mem_ratio")]
    pub forwarder_flush_to_disk_mem_ratio: f64,

    /// Defines the size of the high prio buffer.
    /// Increasing the buffer size can help if payload drops occur due to high prio buffer being full.
    #[serde(default = "defaults::default_u64::<i64, 100>")]
    pub forwarder_high_prio_buffer_size: i64,

    /// The transport type to use for sending logs. Possible values are "auto" or "http1".
    #[serde(default = "defaults::datadog_configuration_forwarder_http_protocol")]
    pub forwarder_http_protocol: String,

    /// The maximum number of concurrent requests that each worker can have queued up
    /// at any one time. If the connection is over HTTP/1 each request will be waiting
    /// for the previous request to complete before sending the next one. With HTTP/2
    /// each request can be sent before waiting for the response.
    #[serde(default = "defaults::default_u64::<i64, 10>")]
    pub forwarder_max_concurrent_requests: i64,

    /// The number of workers used by the forwarder.
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub forwarder_num_workers: i64,

    /// This value specifies how many days the overflow transactions will remain valid before
    /// being discarded. During the Agent restart, if a retry file contains transactions that were
    /// created more than `forwarder_outdated_file_in_days` days ago, they are removed.
    #[serde(default = "defaults::default_u64::<i64, 10>")]
    pub forwarder_outdated_file_in_days: i64,

    #[serde(default = "defaults::default_u64::<i64, 2>")]
    pub forwarder_recovery_interval: i64,

    #[serde(default)]
    pub forwarder_recovery_reset: bool,

    #[serde(default = "defaults::default_u64::<i64, 900>")]
    pub forwarder_retry_queue_capacity_time_interval_sec: i64,

    #[serde(default)]
    pub forwarder_retry_queue_max_size: i64,

    /// It defines the maximum size in bytes of all the payloads in the forwarder's retry queue.
    /// The actual memory used is greater than the payloads size as there are extra fields like HTTP headers,

    /// but no more than 2.5 times the payload size. The default is 15MB.
    #[serde(default = "defaults::default_u64::<i64, 15728640>")]
    pub forwarder_retry_queue_payloads_max_size: i64,

    /// When stopping the agent, the Forwarder will try to flush all new
    /// transactions (not the ones in retry state).  New transactions will be created
    /// as the Aggregator flush it's internal data too, therefore the Agent might take
    /// at most 'aggregator_stop_timeout'+'forwarder_stop_timeout' seconds to exit.
    ///
    /// You can set the maximum amount of time, in seconds, allocated to the
    /// Forwarder to send those transactions.  You can disable this feature by setting
    /// 'forwarder_stop_timeout' to 0.
    #[serde(default = "defaults::default_u64::<i64, 2>")]
    pub forwarder_stop_timeout: i64,

    /// `forwarder_storage_max_disk_ratio` defines the disk capacity limit for storing transactions.
    /// `0.8` means the Agent can store transactions on disk until `forwarder_storage_max_size_in_bytes`
    /// is reached or when the disk mount for `forwarder_storage_path` exceeds 80% of the disk capacity,

    /// whichever is lower.
    #[serde(default = "defaults::datadog_configuration_forwarder_storage_max_disk_ratio")]
    pub forwarder_storage_max_disk_ratio: f64,

    /// When the retry queue of the forwarder is full, `forwarder_storage_max_size_in_bytes`
    /// defines the amount of disk space the Agent can use to store transactions on the disk.
    /// When `forwarder_storage_max_size_in_bytes` is `0`, the transactions are never stored on the disk.
    #[serde(default)]
    pub forwarder_storage_max_size_in_bytes: i64,

    #[serde(default)]
    pub forwarder_storage_path: String,

    /// Forwarder timeout in seconds
    #[serde(default = "defaults::default_u64::<i64, 20>")]
    pub forwarder_timeout: i64,

    /// Configure which aggregated value to compute.
    /// Possible values are: min, max, median, avg, sum and count.
    #[serde(default = "defaults::datadog_configuration_histogram_aggregates")]
    pub histogram_aggregates: Vec<String>,

    /// Copy histogram values to distributions for true global distributions (in beta)
    /// Note: This increases the number of custom metrics created.
    #[serde(default)]
    pub histogram_copy_to_distribution: bool,

    /// A prefix to add to distribution metrics created when histogram_copy_to_distributions is true
    #[serde(default)]
    pub histogram_copy_to_distribution_prefix: String,

    /// If enabled the Agent will log using the RFC3339 format for the log time.
    #[serde(default)]
    pub log_format_rfc3339: bool,

    /// Minimum log level of the Datadog Agent.
    /// Valid log levels are: trace, debug, info, warn, error, critical, and off.
    /// Note: When using the 'off' log level, quotes are mandatory.
    #[serde(default = "defaults::datadog_configuration_log_level")]
    pub log_level: String,

    #[serde(default)]
    pub log_payloads: bool,

    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub metric_filterlist: Vec<String>,

    #[serde(default)]
    pub metric_filterlist_match_prefix: bool,

    /// This option defines the minimum TLS version that will be used when
    /// submitting data to the Datadog intake specified in "site" or "dd_url".
    /// This parameter defaults to "tlsv1.2".
    /// Possible values are: tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3; values are case-
    /// insensitive.
    #[serde(default = "defaults::datadog_configuration_min_tls_version")]
    pub min_tls_version: String,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub multi_region_failover: Option<DatadogConfigurationMultiRegionFailover>,

    /// Enable more flexible no_proxy matching. See https://godoc.org/golang.org/x/net/http/httpproxy#Config
    /// for more information on accepted matching criteria.
    #[serde(default)]
    pub no_proxy_nonexact_match: bool,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub observability_pipelines_worker: Option<DatadogConfigurationObservabilityPipelinesWorker>,

    #[serde(default)]
    pub origin_detection_unified: bool,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub otlp_config: Option<DatadogConfigurationOtlpConfig>,

    #[serde(default)]
    pub provider_kind: String,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub proxy: Option<DatadogConfigurationProxy>,

    #[serde(default = "defaults::datadog_configuration_serializer_compressor_kind")]
    pub serializer_compressor_kind: String,

    #[serde(default = "defaults::default_u64::<i64, 2621440>")]
    pub serializer_max_payload_size: i64,

    #[serde(default = "defaults::default_u64::<i64, 512000>")]
    pub serializer_max_series_payload_size: i64,

    #[serde(default = "defaults::default_u64::<i64, 10000>")]
    pub serializer_max_series_points_per_payload: i64,

    #[serde(default = "defaults::default_u64::<i64, 5242880>")]
    pub serializer_max_series_uncompressed_payload_size: i64,

    #[serde(default = "defaults::default_u64::<i64, 4194304>")]
    pub serializer_max_uncompressed_payload_size: i64,

    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub serializer_zstd_compressor_level: i64,

    /// The site of the Datadog intake to send Agent data to.
    /// The site parameter must be set to enable your agent with Remote Configuration.
    /// Set to 'datadoghq.eu' to send data to the EU site.
    /// Set to 'us3.datadoghq.com' to send data to the US3 site.
    /// Set to 'us5.datadoghq.com' to send data to the US5 site.
    /// Set to 'ap1.datadoghq.com' to send data to the AP1 site.
    /// Set to 'ddog-gov.com' to send data to the US1-FED site.
    #[serde(default = "defaults::datadog_configuration_site")]
    pub site: String,

    /// Setting this option to "true" tells the Agent to skip validation of SSL/TLS certificates.
    #[serde(default)]
    pub skip_ssl_validation: bool,

    /// sslkeylogfile specifies a destination for TLS master secrets
    /// in NSS key log format to allow external programs
    /// such as Wireshark to decrypt TLS connections.
    /// For more details, see https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format.
    /// Use of sslkeylogfile compromises security and should only be
    /// used for debugging.
    #[serde(default)]
    pub sslkeylogfile: String,

    /// Forward every packet received by the DogStatsD server to another statsd server.
    /// WARNING: Make sure that forwarded packets are regular statsd packets and not "DogStatsD" packets,

    /// as your other statsd server might not be able to handle them.
    #[serde(default)]
    pub statsd_forward_host: String,

    /// Port or the "statsd_forward_host" to forward StatsD packet to.
    #[serde(default)]
    pub statsd_forward_port: i64,

    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub statsd_metric_blocklist: Vec<String>,

    #[serde(default)]
    pub statsd_metric_blocklist_match_prefix: bool,

    /// Set a namespace for all StatsD metrics coming from this host.
    /// Each metric received is prefixed with the namespace before it's sent to Datadog.
    #[serde(default)]
    pub statsd_metric_namespace: String,

    #[serde(default = "defaults::datadog_configuration_statsd_metric_namespace_blacklist")]
    pub statsd_metric_namespace_blacklist: Vec<String>,

    /// Set to 'true' to output in an RFC 5424-compliant format for Agent logs.
    #[serde(default)]
    pub syslog_rfc: bool,

    /// Define a custom remote syslog uri if needed. If 'syslog_uri' is left undefined/empty,

    /// a local domain socket connection is attempted.
    #[serde(default)]
    pub syslog_uri: String,

    /// By default cloud provider IP's are added to the transport's `no_proxy` list.
    /// Use this parameter to remove them from the `no_proxy` list.
    #[serde(default)]
    pub use_proxy_for_cloud_metadata: bool,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub use_v2_api: Option<DatadogConfigurationUseV2Api>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub vector: Option<DatadogConfigurationVector>,

    #[serde(default)]
    pub vsock_addr: String,
}

impl Default for DatadogConfiguration {
    fn default() -> Self {
        Self {
            additional_endpoints: Default::default(),
            agent_ipc: Default::default(),
            aggregator_stop_timeout: defaults::default_u64::<i64, 2>(),
            allow_arbitrary_tags: Default::default(),
            api_key: Default::default(),
            apm_config: Default::default(),
            bind_host: Default::default(),
            cmd_port: defaults::default_u64::<i64, 5001>(),
            cri_connection_timeout: defaults::default_u64::<i64, 1>(),
            cri_query_timeout: defaults::default_u64::<i64, 5>(),
            data_plane: Default::default(),
            dd_url: defaults::datadog_configuration_dd_url(),
            dogstatsd_buffer_size: defaults::default_u64::<i64, 8192>(),
            dogstatsd_capture_depth: Default::default(),
            dogstatsd_capture_path: Default::default(),
            dogstatsd_context_expiry_seconds: defaults::default_u64::<i64, 20>(),
            dogstatsd_entity_id_precedence: Default::default(),
            dogstatsd_eol_required: Default::default(),
            dogstatsd_flush_incomplete_buckets: Default::default(),
            dogstatsd_log_file: Default::default(),
            dogstatsd_log_file_max_rolls: defaults::default_u64::<i64, 3>(),
            dogstatsd_log_file_max_size: defaults::datadog_configuration_dogstatsd_log_file_max_size(),
            dogstatsd_logging_enabled: defaults::default_bool::<true>(),
            dogstatsd_mapper_cache_size: defaults::default_u64::<i64, 1000>(),
            dogstatsd_mapper_profiles: Default::default(),
            dogstatsd_metrics_stats_enable: Default::default(),
            dogstatsd_no_aggregation_pipeline: defaults::default_bool::<true>(),
            dogstatsd_non_local_traffic: Default::default(),
            dogstatsd_origin_detection: Default::default(),
            dogstatsd_origin_detection_client: Default::default(),
            dogstatsd_origin_optout_enabled: defaults::default_bool::<true>(),
            dogstatsd_port: defaults::default_u64::<i64, 8125>(),
            dogstatsd_so_rcvbuf: Default::default(),
            dogstatsd_socket: Default::default(),
            dogstatsd_stream_log_too_big: Default::default(),
            dogstatsd_stream_socket: Default::default(),
            dogstatsd_string_interner_size: defaults::default_u64::<i64, 4096>(),
            dogstatsd_tag_cardinality: defaults::datadog_configuration_dogstatsd_tag_cardinality(),
            dogstatsd_tags: Default::default(),
            enable_payloads: Default::default(),
            env: Default::default(),
            forwarder_apikey_validation_interval: defaults::default_u64::<i64, 60>(),
            forwarder_backoff_base: defaults::default_u64::<i64, 2>(),
            forwarder_backoff_factor: defaults::default_u64::<i64, 2>(),
            forwarder_backoff_max: defaults::default_u64::<i64, 64>(),
            forwarder_connection_reset_interval: Default::default(),
            forwarder_flush_to_disk_mem_ratio: defaults::datadog_configuration_forwarder_flush_to_disk_mem_ratio(),
            forwarder_high_prio_buffer_size: defaults::default_u64::<i64, 100>(),
            forwarder_http_protocol: defaults::datadog_configuration_forwarder_http_protocol(),
            forwarder_max_concurrent_requests: defaults::default_u64::<i64, 10>(),
            forwarder_num_workers: defaults::default_u64::<i64, 1>(),
            forwarder_outdated_file_in_days: defaults::default_u64::<i64, 10>(),
            forwarder_recovery_interval: defaults::default_u64::<i64, 2>(),
            forwarder_recovery_reset: Default::default(),
            forwarder_retry_queue_capacity_time_interval_sec: defaults::default_u64::<i64, 900>(),
            forwarder_retry_queue_max_size: Default::default(),
            forwarder_retry_queue_payloads_max_size: defaults::default_u64::<i64, 15728640>(),
            forwarder_stop_timeout: defaults::default_u64::<i64, 2>(),
            forwarder_storage_max_disk_ratio: defaults::datadog_configuration_forwarder_storage_max_disk_ratio(),
            forwarder_storage_max_size_in_bytes: Default::default(),
            forwarder_storage_path: Default::default(),
            forwarder_timeout: defaults::default_u64::<i64, 20>(),
            histogram_aggregates: defaults::datadog_configuration_histogram_aggregates(),
            histogram_copy_to_distribution: Default::default(),
            histogram_copy_to_distribution_prefix: Default::default(),
            log_format_rfc3339: Default::default(),
            log_level: defaults::datadog_configuration_log_level(),
            log_payloads: Default::default(),
            metric_filterlist: Default::default(),
            metric_filterlist_match_prefix: Default::default(),
            min_tls_version: defaults::datadog_configuration_min_tls_version(),
            multi_region_failover: Default::default(),
            no_proxy_nonexact_match: Default::default(),
            observability_pipelines_worker: Default::default(),
            origin_detection_unified: Default::default(),
            otlp_config: Default::default(),
            provider_kind: Default::default(),
            proxy: Default::default(),
            serializer_compressor_kind: defaults::datadog_configuration_serializer_compressor_kind(),
            serializer_max_payload_size: defaults::default_u64::<i64, 2621440>(),
            serializer_max_series_payload_size: defaults::default_u64::<i64, 512000>(),
            serializer_max_series_points_per_payload: defaults::default_u64::<i64, 10000>(),
            serializer_max_series_uncompressed_payload_size: defaults::default_u64::<i64, 5242880>(),
            serializer_max_uncompressed_payload_size: defaults::default_u64::<i64, 4194304>(),
            serializer_zstd_compressor_level: defaults::default_u64::<i64, 1>(),
            site: defaults::datadog_configuration_site(),
            skip_ssl_validation: Default::default(),
            sslkeylogfile: Default::default(),
            statsd_forward_host: Default::default(),
            statsd_forward_port: Default::default(),
            statsd_metric_blocklist: Default::default(),
            statsd_metric_blocklist_match_prefix: Default::default(),
            statsd_metric_namespace: Default::default(),
            statsd_metric_namespace_blacklist: defaults::datadog_configuration_statsd_metric_namespace_blacklist(),
            syslog_rfc: Default::default(),
            syslog_uri: Default::default(),
            use_proxy_for_cloud_metadata: Default::default(),
            use_v2_api: Default::default(),
            vector: Default::default(),
            vsock_addr: Default::default(),
        }
    }
}

/// `DatadogConfigurationAgentIpc`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationAgentIpc {
    #[serde(default = "defaults::default_u64::<i64, 134217728>")]
    pub grpc_max_message_size: i64,
}

impl Default for DatadogConfigurationAgentIpc {
    fn default() -> Self {
        Self {
            grpc_max_message_size: defaults::default_u64::<i64, 134217728>(),
        }
    }
}

/// Enter specific configurations for your trace collection.
/// Uncomment this parameter and the one below to enable them.
/// See https://docs.datadoghq.com/agent/apm/
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfig {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub obfuscation: Option<DatadogConfigurationApmConfigObfuscation>,
}

impl Default for DatadogConfigurationApmConfig {
    fn default() -> Self {
        Self {
            obfuscation: Default::default(),
        }
    }
}

/// Defines obfuscation rules for sensitive data.
/// See https://docs.datadoghq.com/tracing/setup_overview/configure_data_security/#agent-trace-obfuscation
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfigObfuscation {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub credit_cards: Option<DatadogConfigurationApmConfigObfuscationCreditCards>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub elasticsearch: Option<DatadogConfigurationApmConfigObfuscationElasticsearch>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub http: Option<DatadogConfigurationApmConfigObfuscationHttp>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub memcached: Option<DatadogConfigurationApmConfigObfuscationMemcached>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub mongodb: Option<DatadogConfigurationApmConfigObfuscationMongodb>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub opensearch: Option<DatadogConfigurationApmConfigObfuscationOpensearch>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub redis: Option<DatadogConfigurationApmConfigObfuscationRedis>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub valkey: Option<DatadogConfigurationApmConfigObfuscationValkey>,
}

impl Default for DatadogConfigurationApmConfigObfuscation {
    fn default() -> Self {
        Self {
            credit_cards: Default::default(),
            elasticsearch: Default::default(),
            http: Default::default(),
            memcached: Default::default(),
            mongodb: Default::default(),
            opensearch: Default::default(),
            redis: Default::default(),
            valkey: Default::default(),
        }
    }
}

/// Obfuscation rules for credit card numbers found in trace span values.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfigObfuscationCreditCards {
    /// Enables obfuscation rules for credit cards. Enabled by default.
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,

    /// List of keys that should not be obfuscated.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub keep_values: Vec<String>,

    /// Enables a Luhn checksum check in order to eliminate false negatives. Disabled by default.
    #[serde(default)]
    pub luhn: bool,
}

impl Default for DatadogConfigurationApmConfigObfuscationCreditCards {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
            keep_values: Default::default(),
            luhn: Default::default(),
        }
    }
}

/// Obfuscation rules for Elasticsearch query bodies in trace spans.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfigObfuscationElasticsearch {
    /// Enables obfuscation rules for spans of type "elasticsearch". Enabled by default.
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,

    /// List of keys that should not be obfuscated.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub keep_values: Vec<String>,

    /// The set of keys for which their values will be passed through SQL obfuscation
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub obfuscate_sql_values: Vec<String>,
}

impl Default for DatadogConfigurationApmConfigObfuscationElasticsearch {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
            keep_values: Default::default(),
            obfuscate_sql_values: Default::default(),
        }
    }
}

/// Obfuscation rules for HTTP URLs and query strings in trace spans.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfigObfuscationHttp {
    /// If enabled, path segments in URLs containing digits are replaced by "?"
    #[serde(default)]
    pub remove_paths_with_digits: bool,

    /// Enables obfuscation of query strings in URLs
    #[serde(default)]
    pub remove_query_string: bool,
}

impl Default for DatadogConfigurationApmConfigObfuscationHttp {
    fn default() -> Self {
        Self {
            remove_paths_with_digits: Default::default(),
            remove_query_string: Default::default(),
        }
    }
}

/// Obfuscation rules for Memcached command strings in trace spans.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfigObfuscationMemcached {
    /// Enables obfuscation rules for spans of type "memcached". Enabled by default.
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,

    /// If enabled, the full command for the query will be kept, including any lookup
    /// keys that could be present. The value for storage commands will still be
    /// redacted if Memcached obfuscation is enabled.
    #[serde(default)]
    pub keep_command: bool,
}

impl Default for DatadogConfigurationApmConfigObfuscationMemcached {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
            keep_command: Default::default(),
        }
    }
}

/// Obfuscation rules for MongoDB query documents in trace spans.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfigObfuscationMongodb {
    /// Enables obfuscation rules for spans of type "mongodb". Enabled by default.
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,

    /// List of keys that should not be obfuscated.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub keep_values: Vec<String>,

    /// The set of keys for which their values will be passed through SQL obfuscation
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub obfuscate_sql_values: Vec<String>,
}

impl Default for DatadogConfigurationApmConfigObfuscationMongodb {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
            keep_values: Default::default(),
            obfuscate_sql_values: Default::default(),
        }
    }
}

/// Obfuscation rules for OpenSearch query bodies in trace spans.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfigObfuscationOpensearch {
    /// Enables obfuscation rules for spans of type "opensearch". Enabled by default.
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,

    /// List of keys that should not be obfuscated.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub keep_values: Vec<String>,

    /// The set of keys for which their values will be passed through SQL obfuscation
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub obfuscate_sql_values: Vec<String>,
}

impl Default for DatadogConfigurationApmConfigObfuscationOpensearch {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
            keep_values: Default::default(),
            obfuscate_sql_values: Default::default(),
        }
    }
}

/// Obfuscation rules for Redis command arguments in trace spans.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfigObfuscationRedis {
    /// Enables obfuscation rules for spans of type "redis". Enabled by default.
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,

    /// When true, replaces all arguments of a redis command with a single "?". Disabled by default.
    #[serde(default)]
    pub remove_all_args: bool,
}

impl Default for DatadogConfigurationApmConfigObfuscationRedis {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
            remove_all_args: Default::default(),
        }
    }
}

/// Obfuscation rules for Valkey command arguments in trace spans.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationApmConfigObfuscationValkey {
    /// Enables obfuscation rules for spans of type "valkey". Enabled by default.
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,

    /// When true, replaces all arguments of a valkey command with a single "?". Disabled by default.
    #[serde(default)]
    pub remove_all_args: bool,
}

impl Default for DatadogConfigurationApmConfigObfuscationValkey {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
            remove_all_args: Default::default(),
        }
    }
}

/// `DatadogConfigurationDataPlane`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationDataPlane {
    #[serde(default = "defaults::datadog_configuration_data_plane_api_listen_address")]
    pub api_listen_address: String,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub dogstatsd: Option<DatadogConfigurationDataPlaneDogstatsd>,

    #[serde(default = "defaults::datadog_configuration_data_plane_log_file")]
    pub log_file: String,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub otlp: Option<DatadogConfigurationDataPlaneOtlp>,

    #[serde(default = "defaults::default_bool::<true>")]
    pub remote_agent_enabled: bool,

    #[serde(default = "defaults::datadog_configuration_data_plane_secure_api_listen_address")]
    pub secure_api_listen_address: String,

    #[serde(default = "defaults::default_bool::<true>")]
    pub use_new_config_stream_endpoint: bool,
}

impl Default for DatadogConfigurationDataPlane {
    fn default() -> Self {
        Self {
            api_listen_address: defaults::datadog_configuration_data_plane_api_listen_address(),
            dogstatsd: Default::default(),
            log_file: defaults::datadog_configuration_data_plane_log_file(),
            otlp: Default::default(),
            remote_agent_enabled: defaults::default_bool::<true>(),
            secure_api_listen_address: defaults::datadog_configuration_data_plane_secure_api_listen_address(),
            use_new_config_stream_endpoint: defaults::default_bool::<true>(),
        }
    }
}

/// `DatadogConfigurationDataPlaneDogstatsd`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationDataPlaneDogstatsd {
    #[serde(default = "defaults::default_u64::<i64, 100000>")]
    pub aggregator_tag_filter_cache_capacity: i64,
}

impl Default for DatadogConfigurationDataPlaneDogstatsd {
    fn default() -> Self {
        Self {
            aggregator_tag_filter_cache_capacity: defaults::default_u64::<i64, 100000>(),
        }
    }
}

/// `DatadogConfigurationDataPlaneOtlp`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationDataPlaneOtlp {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub proxy: Option<DatadogConfigurationDataPlaneOtlpProxy>,
}

impl Default for DatadogConfigurationDataPlaneOtlp {
    fn default() -> Self {
        Self {
            proxy: Default::default(),
        }
    }
}

/// `DatadogConfigurationDataPlaneOtlpProxy`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationDataPlaneOtlpProxy {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub logs: Option<DatadogConfigurationDataPlaneOtlpProxyLogs>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub metrics: Option<DatadogConfigurationDataPlaneOtlpProxyMetrics>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub traces: Option<DatadogConfigurationDataPlaneOtlpProxyTraces>,
}

impl Default for DatadogConfigurationDataPlaneOtlpProxy {
    fn default() -> Self {
        Self {
            logs: Default::default(),
            metrics: Default::default(),
            traces: Default::default(),
        }
    }
}

/// `DatadogConfigurationDataPlaneOtlpProxyLogs`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationDataPlaneOtlpProxyLogs {
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,
}

impl Default for DatadogConfigurationDataPlaneOtlpProxyLogs {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
        }
    }
}

/// `DatadogConfigurationDataPlaneOtlpProxyMetrics`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationDataPlaneOtlpProxyMetrics {
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,
}

impl Default for DatadogConfigurationDataPlaneOtlpProxyMetrics {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
        }
    }
}

/// `DatadogConfigurationDataPlaneOtlpProxyTraces`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationDataPlaneOtlpProxyTraces {
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,
}

impl Default for DatadogConfigurationDataPlaneOtlpProxyTraces {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
        }
    }
}

/// `DatadogConfigurationEnablePayloads`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationEnablePayloads {
    #[serde(default = "defaults::default_bool::<true>")]
    pub events: bool,

    #[serde(default = "defaults::default_bool::<true>")]
    pub series: bool,

    #[serde(default = "defaults::default_bool::<true>")]
    pub service_checks: bool,

    #[serde(default = "defaults::default_bool::<true>")]
    pub sketches: bool,
}

impl Default for DatadogConfigurationEnablePayloads {
    fn default() -> Self {
        Self {
            events: defaults::default_bool::<true>(),
            series: defaults::default_bool::<true>(),
            service_checks: defaults::default_bool::<true>(),
            sketches: defaults::default_bool::<true>(),
        }
    }
}

/// `DatadogConfigurationMultiRegionFailover`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationMultiRegionFailover {
    #[serde(default)]
    pub api_key: String,

    #[serde(default)]
    pub dd_url: String,

    #[serde(default)]
    pub enabled: bool,

    #[serde(default)]
    pub failover_metrics: bool,

    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub metric_allowlist: Vec<String>,

    #[serde(default)]
    pub site: String,
}

impl Default for DatadogConfigurationMultiRegionFailover {
    fn default() -> Self {
        Self {
            api_key: Default::default(),
            dd_url: Default::default(),
            enabled: Default::default(),
            failover_metrics: Default::default(),
            metric_allowlist: Default::default(),
            site: Default::default(),
        }
    }
}

/// Configuration for forwarding telemetry to an Observability Pipelines Worker instead of Datadog.
/// https://www.datadoghq.com/product/observability-pipelines/
/// Note: This config is interchangeable with `vector`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationObservabilityPipelinesWorker {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub metrics: Option<DatadogConfigurationObservabilityPipelinesWorkerMetrics>,
}

impl Default for DatadogConfigurationObservabilityPipelinesWorker {
    fn default() -> Self {
        Self {
            metrics: Default::default(),
        }
    }
}

/// Specific configurations for metrics
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationObservabilityPipelinesWorkerMetrics {
    /// Enables forwarding of metrics to an Observability Pipelines Worker
    #[serde(default)]
    pub enabled: bool,

    /// URL endpoint for the Observability Pipelines Worker to send metrics to
    #[serde(default)]
    pub url: String,
}

impl Default for DatadogConfigurationObservabilityPipelinesWorkerMetrics {
    fn default() -> Self {
        Self {
            enabled: Default::default(),
            url: Default::default(),
        }
    }
}

/// This section configures OTLP ingest in the Datadog Agent.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationOtlpConfig {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub logs: Option<DatadogConfigurationOtlpConfigLogs>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub metrics: Option<DatadogConfigurationOtlpConfigMetrics>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub receiver: Option<DatadogConfigurationOtlpConfigReceiver>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub traces: Option<DatadogConfigurationOtlpConfigTraces>,
}

impl Default for DatadogConfigurationOtlpConfig {
    fn default() -> Self {
        Self {
            logs: Default::default(),
            metrics: Default::default(),
            receiver: Default::default(),
            traces: Default::default(),
        }
    }
}

/// Logs-specific configuration for OTLP ingest in the Datadog Agent.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationOtlpConfigLogs {
    /// Set to true to enable logs support in the OTLP ingest endpoint.
    /// To enable the OTLP ingest, the otlp_config.receiver section must be set.
    #[serde(default)]
    pub enabled: bool,
}

impl Default for DatadogConfigurationOtlpConfigLogs {
    fn default() -> Self {
        Self {
            enabled: Default::default(),
        }
    }
}

/// Metrics-specific configuration for OTLP ingest in the Datadog Agent.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationOtlpConfigMetrics {
    /// Set to false to disable metrics support in the OTLP ingest endpoint.
    /// To enable the OTLP ingest, the otlp_config.receiver section must be set.
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,
}

impl Default for DatadogConfigurationOtlpConfigMetrics {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
        }
    }
}

/// The receiver configuration. It follows the OpenTelemetry Collector's OTLP Receiver Configuration.
/// This template lists the most commonly used settings; see the OpenTelemetry Collector documentation
/// for a full list of available settings:
/// https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/config.md
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationOtlpConfigReceiver {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub protocols: Option<DatadogConfigurationOtlpConfigReceiverProtocols>,
}

impl Default for DatadogConfigurationOtlpConfigReceiver {
    fn default() -> Self {
        Self {
            protocols: Default::default(),
        }
    }
}

/// Configuration for the supported protocols.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationOtlpConfigReceiverProtocols {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub grpc: Option<DatadogConfigurationOtlpConfigReceiverProtocolsGrpc>,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub http: Option<DatadogConfigurationOtlpConfigReceiverProtocolsHttp>,
}

impl Default for DatadogConfigurationOtlpConfigReceiverProtocols {
    fn default() -> Self {
        Self {
            grpc: Default::default(),
            http: Default::default(),
        }
    }
}

/// Configuration for OTLP/gRPC listener.
/// Setting this as an empty section enables the OTLP/gRPC listener with default options.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationOtlpConfigReceiverProtocolsGrpc {
    /// The OTLP/gRPC listener endpoint.
    #[serde(default = "defaults::datadog_configuration_otlp_config_receiver_protocols_grpc_endpoint")]
    pub endpoint: String,

    /// The maximum size (in MiB) of messages accepted by the OTLP/gRPC endpoint.
    /// When set to 0 (the default), grpc-go applies its built-in 4 MiB limit.
    #[serde(default)]
    pub max_recv_msg_size_mib: i64,

    /// The OTLP/gRPC listener transport protocol.
    /// Known protocols are "tcp", "udp", "ip", "unix", "unixgram", and "unixpacket".
    #[serde(default = "defaults::datadog_configuration_otlp_config_receiver_protocols_grpc_transport")]
    pub transport: String,
}

impl Default for DatadogConfigurationOtlpConfigReceiverProtocolsGrpc {
    fn default() -> Self {
        Self {
            endpoint: defaults::datadog_configuration_otlp_config_receiver_protocols_grpc_endpoint(),
            max_recv_msg_size_mib: Default::default(),
            transport: defaults::datadog_configuration_otlp_config_receiver_protocols_grpc_transport(),
        }
    }
}

/// Configuration for OTLP/HTTP listener.
/// Setting this as an empty section enables the OTLP/HTTP listener with default options.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationOtlpConfigReceiverProtocolsHttp {
    /// The OTLP/HTTP listener endpoint.
    #[serde(default = "defaults::datadog_configuration_otlp_config_receiver_protocols_http_endpoint")]
    pub endpoint: String,
}

impl Default for DatadogConfigurationOtlpConfigReceiverProtocolsHttp {
    fn default() -> Self {
        Self {
            endpoint: defaults::datadog_configuration_otlp_config_receiver_protocols_http_endpoint(),
        }
    }
}

/// Traces-specific configuration for OTLP ingest in the Datadog Agent.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationOtlpConfigTraces {
    /// Set to false to disable traces support in the OTLP ingest endpoint.
    /// To enable the OTLP ingest, the otlp_config.receiver section must be set.
    #[serde(default = "defaults::default_bool::<true>")]
    pub enabled: bool,

    #[serde(default = "defaults::default_u64::<i64, 5003>")]
    pub internal_port: i64,

    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub probabilistic_sampler: Option<DatadogConfigurationOtlpConfigTracesProbabilisticSampler>,
}

impl Default for DatadogConfigurationOtlpConfigTraces {
    fn default() -> Self {
        Self {
            enabled: defaults::default_bool::<true>(),
            internal_port: defaults::default_u64::<i64, 5003>(),
            probabilistic_sampler: Default::default(),
        }
    }
}

/// Probabilistic sampler controlling the rate of ingestion. Using this sampler works consistently
/// in a distributed system where the sampling rate is shared. Exceptions are made for errors and
/// rare traces (if enabled via apm_config.enable_rare_sampler).
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationOtlpConfigTracesProbabilisticSampler {
    /// If `apm_config.probabilistic_sampler.enabled` is enabled, this config is ignored, `apm_config.probabilistic_sampler.enabled.sampling_percentage`
    /// is used instead.
    /// Percentage of traces to ingest (0 100]. Invalid values (<= 0 || > 100) are disconsidered and the default is used.
    /// If incoming spans have a sampling.priority set by the user, it will be followed and the sampling percentage will
    /// be overridden.
    #[serde(default = "defaults::datadog_configuration_otlp_config_traces_probabilistic_sampler_sampling_percentage")]
    pub sampling_percentage: f64,
}

impl Default for DatadogConfigurationOtlpConfigTracesProbabilisticSampler {
    fn default() -> Self {
        Self {
            sampling_percentage:
                defaults::datadog_configuration_otlp_config_traces_probabilistic_sampler_sampling_percentage(),
        }
    }
}

/// If you need a proxy to connect to the Internet, provide it here (default:
/// disabled). Refer to https://docs.datadoghq.com/agent/proxy/ to understand how to use these settings.
/// For Logs proxy information, refer to https://docs.datadoghq.com/agent/proxy/#proxy-for-logs
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationProxy {
    /// @env DD_PROXY_HTTP - string - optional - default: ""
    /// The proxy to use for HTTP requests
    #[serde(default)]
    pub http: String,

    /// @env DD_PROXY_HTTPS - string - optional - default: ""
    /// The proxy to use for HTTPS requests
    #[serde(default)]
    pub https: String,

    /// @env DD_PROXY_NO_PROXY - space-separated list of strings - optional - default: []
    /// A list of hosts for which the proxy setting should not be used
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub no_proxy: Vec<String>,
}

impl Default for DatadogConfigurationProxy {
    fn default() -> Self {
        Self {
            http: Default::default(),
            https: Default::default(),
            no_proxy: Default::default(),
        }
    }
}

/// `DatadogConfigurationUseV2Api`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationUseV2Api {
    #[serde(default = "defaults::default_bool::<true>")]
    pub series: bool,
}

impl Default for DatadogConfigurationUseV2Api {
    fn default() -> Self {
        Self {
            series: defaults::default_bool::<true>(),
        }
    }
}

/// `DatadogConfigurationVector`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationVector {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub metrics: Option<DatadogConfigurationVectorMetrics>,
}

impl Default for DatadogConfigurationVector {
    fn default() -> Self {
        Self {
            metrics: Default::default(),
        }
    }
}

/// `DatadogConfigurationVectorMetrics`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DatadogConfigurationVectorMetrics {
    #[serde(default)]
    pub enabled: bool,

    #[serde(default)]
    pub url: String,
}

impl Default for DatadogConfigurationVectorMetrics {
    fn default() -> Self {
        Self {
            enabled: Default::default(),
            url: Default::default(),
        }
    }
}

/// Generation of default values for serde.
pub mod defaults {
    pub(super) fn default_bool<const V: bool>() -> bool {
        V
    }
    pub(super) fn default_i64<T, const V: i64>() -> T
    where
        T: TryFrom<i64>,
        <T as ::std::convert::TryFrom<i64>>::Error: ::std::fmt::Debug,
    {
        T::try_from(V).unwrap()
    }
    pub(super) fn default_u64<T, const V: u64>() -> T
    where
        T: TryFrom<u64>,
        <T as ::std::convert::TryFrom<u64>>::Error: ::std::fmt::Debug,
    {
        T::try_from(V).unwrap()
    }
    pub(super) fn datadog_configuration_dd_url() -> String {
        "https://app.datadoghq.com".to_string()
    }
    pub(super) fn datadog_configuration_dogstatsd_log_file_max_size() -> String {
        "10Mb".to_string()
    }
    pub(super) fn datadog_configuration_dogstatsd_tag_cardinality() -> String {
        "low".to_string()
    }
    pub(super) fn datadog_configuration_forwarder_flush_to_disk_mem_ratio() -> f64 {
        0.5_f64
    }
    pub(super) fn datadog_configuration_forwarder_http_protocol() -> String {
        "auto".to_string()
    }
    pub(super) fn datadog_configuration_forwarder_storage_max_disk_ratio() -> f64 {
        0.8_f64
    }
    pub(super) fn datadog_configuration_histogram_aggregates() -> Vec<String> {
        vec![
            "max".to_string(),
            "median".to_string(),
            "avg".to_string(),
            "count".to_string(),
        ]
    }
    pub(super) fn datadog_configuration_log_level() -> String {
        "info".to_string()
    }
    pub(super) fn datadog_configuration_min_tls_version() -> String {
        "tlsv1.2".to_string()
    }
    pub(super) fn datadog_configuration_serializer_compressor_kind() -> String {
        "zstd".to_string()
    }
    pub(super) fn datadog_configuration_site() -> String {
        "datadoghq.com".to_string()
    }
    pub(super) fn datadog_configuration_statsd_metric_namespace_blacklist() -> Vec<String> {
        vec![
            "datadog.agent".to_string(),
            "datadog.dogstatsd".to_string(),
            "datadog.process".to_string(),
            "datadog.trace_agent".to_string(),
            "datadog.tracer".to_string(),
            "activemq".to_string(),
            "activemq_58".to_string(),
            "airflow".to_string(),
            "cassandra".to_string(),
            "confluent".to_string(),
            "hazelcast".to_string(),
            "hive".to_string(),
            "ignite".to_string(),
            "jboss".to_string(),
            "jvm".to_string(),
            "kafka".to_string(),
            "presto".to_string(),
            "sidekiq".to_string(),
            "solr".to_string(),
            "tomcat".to_string(),
            "runtime".to_string(),
        ]
    }
    pub(super) fn datadog_configuration_data_plane_api_listen_address() -> String {
        "tcp://0.0.0.0:5100".to_string()
    }
    pub(super) fn datadog_configuration_data_plane_log_file() -> String {
        "/var/log/datadog/agent-data-plane.log".to_string()
    }
    pub(super) fn datadog_configuration_data_plane_secure_api_listen_address() -> String {
        "tcp://0.0.0.0:5101".to_string()
    }
    pub(super) fn datadog_configuration_otlp_config_receiver_protocols_grpc_endpoint() -> String {
        "localhost:4317".to_string()
    }
    pub(super) fn datadog_configuration_otlp_config_receiver_protocols_grpc_transport() -> String {
        "tcp".to_string()
    }
    pub(super) fn datadog_configuration_otlp_config_receiver_protocols_http_endpoint() -> String {
        "localhost:4318".to_string()
    }
    pub(super) fn datadog_configuration_otlp_config_traces_probabilistic_sampler_sampling_percentage() -> f64 {
        100_f64
    }
}
