// @generated by build.rs from core_schema.yaml + schema_overlay.yaml — DO NOT EDIT
// Regenerate by running `cargo build -p datadog-agent-config`.
#![allow(clippy::all, dead_code, unused)]

use std::collections::HashMap;

use crate::datadog_configuration::*;
use crate::translate_error::TranslateError;

/// Witness trait over every supported Datadog configuration key.
///
/// One `consume_<key>` method per `support: full` / `support: partial` overlay key. A
/// hand-written translator implements this trait; adding support for a key adds a method here
/// and so creates a compile-time obligation to choose a translation destination.
pub trait DatadogConfigConsumer {
    /// Consumes the value of the `additional_endpoints` key.
    fn consume_additional_endpoints(&mut self, value: HashMap<String, Vec<String>>);
    /// Consumes the value of the `agent_ipc.grpc_max_message_size` key.
    fn consume_agent_ipc_grpc_max_message_size(&mut self, value: i64);
    /// Consumes the value of the `aggregator_stop_timeout` key.
    fn consume_aggregator_stop_timeout(&mut self, value: i64);
    /// Consumes the value of the `allow_arbitrary_tags` key.
    fn consume_allow_arbitrary_tags(&mut self, value: bool);
    /// Consumes the value of the `api_key` key.
    fn consume_api_key(&mut self, value: String);
    /// Consumes the value of the `apm_config.obfuscation.credit_cards.enabled` key.
    fn consume_apm_config_obfuscation_credit_cards_enabled(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.credit_cards.keep_values` key.
    fn consume_apm_config_obfuscation_credit_cards_keep_values(&mut self, value: Vec<String>);
    /// Consumes the value of the `apm_config.obfuscation.credit_cards.luhn` key.
    fn consume_apm_config_obfuscation_credit_cards_luhn(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.elasticsearch.enabled` key.
    fn consume_apm_config_obfuscation_elasticsearch_enabled(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.elasticsearch.keep_values` key.
    fn consume_apm_config_obfuscation_elasticsearch_keep_values(&mut self, value: Vec<String>);
    /// Consumes the value of the `apm_config.obfuscation.elasticsearch.obfuscate_sql_values` key.
    fn consume_apm_config_obfuscation_elasticsearch_obfuscate_sql_values(&mut self, value: Vec<String>);
    /// Consumes the value of the `apm_config.obfuscation.http.remove_paths_with_digits` key.
    fn consume_apm_config_obfuscation_http_remove_paths_with_digits(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.http.remove_query_string` key.
    fn consume_apm_config_obfuscation_http_remove_query_string(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.memcached.enabled` key.
    fn consume_apm_config_obfuscation_memcached_enabled(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.memcached.keep_command` key.
    fn consume_apm_config_obfuscation_memcached_keep_command(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.mongodb.enabled` key.
    fn consume_apm_config_obfuscation_mongodb_enabled(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.mongodb.keep_values` key.
    fn consume_apm_config_obfuscation_mongodb_keep_values(&mut self, value: Vec<String>);
    /// Consumes the value of the `apm_config.obfuscation.mongodb.obfuscate_sql_values` key.
    fn consume_apm_config_obfuscation_mongodb_obfuscate_sql_values(&mut self, value: Vec<String>);
    /// Consumes the value of the `apm_config.obfuscation.opensearch.enabled` key.
    fn consume_apm_config_obfuscation_opensearch_enabled(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.opensearch.keep_values` key.
    fn consume_apm_config_obfuscation_opensearch_keep_values(&mut self, value: Vec<String>);
    /// Consumes the value of the `apm_config.obfuscation.opensearch.obfuscate_sql_values` key.
    fn consume_apm_config_obfuscation_opensearch_obfuscate_sql_values(&mut self, value: Vec<String>);
    /// Consumes the value of the `apm_config.obfuscation.redis.enabled` key.
    fn consume_apm_config_obfuscation_redis_enabled(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.redis.remove_all_args` key.
    fn consume_apm_config_obfuscation_redis_remove_all_args(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.valkey.enabled` key.
    fn consume_apm_config_obfuscation_valkey_enabled(&mut self, value: bool);
    /// Consumes the value of the `apm_config.obfuscation.valkey.remove_all_args` key.
    fn consume_apm_config_obfuscation_valkey_remove_all_args(&mut self, value: bool);
    /// Consumes the value of the `bind_host` key.
    fn consume_bind_host(&mut self, value: String);
    /// Consumes the value of the `cmd_port` key.
    fn consume_cmd_port(&mut self, value: i64);
    /// Consumes the value of the `cri_connection_timeout` key.
    fn consume_cri_connection_timeout(&mut self, value: i64);
    /// Consumes the value of the `cri_query_timeout` key.
    fn consume_cri_query_timeout(&mut self, value: i64);
    /// Consumes the value of the `data_plane.api_listen_address` key.
    fn consume_data_plane_api_listen_address(&mut self, value: String);
    /// Consumes the value of the `data_plane.dogstatsd.aggregator_tag_filter_cache_capacity` key.
    fn consume_data_plane_dogstatsd_aggregator_tag_filter_cache_capacity(&mut self, value: i64);
    /// Consumes the value of the `data_plane.log_file` key.
    fn consume_data_plane_log_file(&mut self, value: String);
    /// Consumes the value of the `data_plane.otlp.proxy.logs.enabled` key.
    fn consume_data_plane_otlp_proxy_logs_enabled(&mut self, value: bool);
    /// Consumes the value of the `data_plane.otlp.proxy.metrics.enabled` key.
    fn consume_data_plane_otlp_proxy_metrics_enabled(&mut self, value: bool);
    /// Consumes the value of the `data_plane.otlp.proxy.traces.enabled` key.
    fn consume_data_plane_otlp_proxy_traces_enabled(&mut self, value: bool);
    /// Consumes the value of the `data_plane.remote_agent_enabled` key.
    fn consume_data_plane_remote_agent_enabled(&mut self, value: bool);
    /// Consumes the value of the `data_plane.secure_api_listen_address` key.
    fn consume_data_plane_secure_api_listen_address(&mut self, value: String);
    /// Consumes the value of the `data_plane.use_new_config_stream_endpoint` key.
    fn consume_data_plane_use_new_config_stream_endpoint(&mut self, value: bool);
    /// Consumes the value of the `dd_url` key.
    fn consume_dd_url(&mut self, value: String);
    /// Consumes the value of the `dogstatsd_buffer_size` key.
    fn consume_dogstatsd_buffer_size(&mut self, value: i64);
    /// Consumes the value of the `dogstatsd_capture_depth` key.
    fn consume_dogstatsd_capture_depth(&mut self, value: i64);
    /// Consumes the value of the `dogstatsd_capture_path` key.
    fn consume_dogstatsd_capture_path(&mut self, value: String);
    /// Consumes the value of the `dogstatsd_context_expiry_seconds` key.
    fn consume_dogstatsd_context_expiry_seconds(&mut self, value: i64);
    /// Consumes the value of the `dogstatsd_entity_id_precedence` key.
    fn consume_dogstatsd_entity_id_precedence(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_eol_required` key.
    fn consume_dogstatsd_eol_required(&mut self, value: Vec<String>);
    /// Consumes the value of the `dogstatsd_flush_incomplete_buckets` key.
    fn consume_dogstatsd_flush_incomplete_buckets(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_log_file` key.
    fn consume_dogstatsd_log_file(&mut self, value: String);
    /// Consumes the value of the `dogstatsd_log_file_max_rolls` key.
    fn consume_dogstatsd_log_file_max_rolls(&mut self, value: i64);
    /// Consumes the value of the `dogstatsd_log_file_max_size` key.
    fn consume_dogstatsd_log_file_max_size(&mut self, value: String);
    /// Consumes the value of the `dogstatsd_logging_enabled` key.
    fn consume_dogstatsd_logging_enabled(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_mapper_cache_size` key.
    fn consume_dogstatsd_mapper_cache_size(&mut self, value: i64);
    /// Consumes the value of the `dogstatsd_mapper_profiles` key.
    fn consume_dogstatsd_mapper_profiles(&mut self, value: Vec<::serde_json::Value>);
    /// Consumes the value of the `dogstatsd_metrics_stats_enable` key.
    fn consume_dogstatsd_metrics_stats_enable(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_no_aggregation_pipeline` key.
    fn consume_dogstatsd_no_aggregation_pipeline(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_non_local_traffic` key.
    fn consume_dogstatsd_non_local_traffic(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_origin_detection` key.
    fn consume_dogstatsd_origin_detection(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_origin_detection_client` key.
    fn consume_dogstatsd_origin_detection_client(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_origin_optout_enabled` key.
    fn consume_dogstatsd_origin_optout_enabled(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_port` key.
    fn consume_dogstatsd_port(&mut self, value: i64);
    /// Consumes the value of the `dogstatsd_so_rcvbuf` key.
    fn consume_dogstatsd_so_rcvbuf(&mut self, value: i64);
    /// Consumes the value of the `dogstatsd_socket` key.
    fn consume_dogstatsd_socket(&mut self, value: Option<String>);
    /// Consumes the value of the `dogstatsd_stream_log_too_big` key.
    fn consume_dogstatsd_stream_log_too_big(&mut self, value: bool);
    /// Consumes the value of the `dogstatsd_stream_socket` key.
    fn consume_dogstatsd_stream_socket(&mut self, value: String);
    /// Consumes the value of the `dogstatsd_string_interner_size` key.
    fn consume_dogstatsd_string_interner_size(&mut self, value: i64);
    /// Consumes the value of the `dogstatsd_tag_cardinality` key.
    fn consume_dogstatsd_tag_cardinality(&mut self, value: String);
    /// Consumes the value of the `dogstatsd_tags` key.
    fn consume_dogstatsd_tags(&mut self, value: Vec<String>);
    /// Consumes the value of the `enable_payloads.events` key.
    fn consume_enable_payloads_events(&mut self, value: bool);
    /// Consumes the value of the `enable_payloads.series` key.
    fn consume_enable_payloads_series(&mut self, value: bool);
    /// Consumes the value of the `enable_payloads.service_checks` key.
    fn consume_enable_payloads_service_checks(&mut self, value: bool);
    /// Consumes the value of the `enable_payloads.sketches` key.
    fn consume_enable_payloads_sketches(&mut self, value: bool);
    /// Consumes the value of the `env` key.
    fn consume_env(&mut self, value: String);
    /// Consumes the value of the `forwarder_apikey_validation_interval` key.
    fn consume_forwarder_apikey_validation_interval(&mut self, value: i64);
    /// Consumes the value of the `forwarder_backoff_base` key.
    fn consume_forwarder_backoff_base(&mut self, value: i64);
    /// Consumes the value of the `forwarder_backoff_factor` key.
    fn consume_forwarder_backoff_factor(&mut self, value: i64);
    /// Consumes the value of the `forwarder_backoff_max` key.
    fn consume_forwarder_backoff_max(&mut self, value: i64);
    /// Consumes the value of the `forwarder_connection_reset_interval` key.
    fn consume_forwarder_connection_reset_interval(&mut self, value: i64);
    /// Consumes the value of the `forwarder_flush_to_disk_mem_ratio` key.
    fn consume_forwarder_flush_to_disk_mem_ratio(&mut self, value: f64);
    /// Consumes the value of the `forwarder_high_prio_buffer_size` key.
    fn consume_forwarder_high_prio_buffer_size(&mut self, value: i64);
    /// Consumes the value of the `forwarder_http_protocol` key.
    fn consume_forwarder_http_protocol(&mut self, value: String);
    /// Consumes the value of the `forwarder_max_concurrent_requests` key.
    fn consume_forwarder_max_concurrent_requests(&mut self, value: i64);
    /// Consumes the value of the `forwarder_num_workers` key.
    fn consume_forwarder_num_workers(&mut self, value: i64);
    /// Consumes the value of the `forwarder_outdated_file_in_days` key.
    fn consume_forwarder_outdated_file_in_days(&mut self, value: i64);
    /// Consumes the value of the `forwarder_recovery_interval` key.
    fn consume_forwarder_recovery_interval(&mut self, value: i64);
    /// Consumes the value of the `forwarder_recovery_reset` key.
    fn consume_forwarder_recovery_reset(&mut self, value: bool);
    /// Consumes the value of the `forwarder_retry_queue_capacity_time_interval_sec` key.
    fn consume_forwarder_retry_queue_capacity_time_interval_sec(&mut self, value: i64);
    /// Consumes the value of the `forwarder_retry_queue_max_size` key.
    fn consume_forwarder_retry_queue_max_size(&mut self, value: i64);
    /// Consumes the value of the `forwarder_retry_queue_payloads_max_size` key.
    fn consume_forwarder_retry_queue_payloads_max_size(&mut self, value: i64);
    /// Consumes the value of the `forwarder_stop_timeout` key.
    fn consume_forwarder_stop_timeout(&mut self, value: i64);
    /// Consumes the value of the `forwarder_storage_max_disk_ratio` key.
    fn consume_forwarder_storage_max_disk_ratio(&mut self, value: f64);
    /// Consumes the value of the `forwarder_storage_max_size_in_bytes` key.
    fn consume_forwarder_storage_max_size_in_bytes(&mut self, value: i64);
    /// Consumes the value of the `forwarder_storage_path` key.
    fn consume_forwarder_storage_path(&mut self, value: String);
    /// Consumes the value of the `forwarder_timeout` key.
    fn consume_forwarder_timeout(&mut self, value: i64);
    /// Consumes the value of the `histogram_aggregates` key.
    fn consume_histogram_aggregates(&mut self, value: Vec<String>);
    /// Consumes the value of the `histogram_copy_to_distribution` key.
    fn consume_histogram_copy_to_distribution(&mut self, value: bool);
    /// Consumes the value of the `histogram_copy_to_distribution_prefix` key.
    fn consume_histogram_copy_to_distribution_prefix(&mut self, value: String);
    /// Consumes the value of the `log_format_rfc3339` key.
    fn consume_log_format_rfc3339(&mut self, value: bool);
    /// Consumes the value of the `log_level` key.
    fn consume_log_level(&mut self, value: String);
    /// Consumes the value of the `log_payloads` key.
    fn consume_log_payloads(&mut self, value: bool);
    /// Consumes the value of the `metric_filterlist` key.
    fn consume_metric_filterlist(&mut self, value: Vec<String>);
    /// Consumes the value of the `metric_filterlist_match_prefix` key.
    fn consume_metric_filterlist_match_prefix(&mut self, value: bool);
    /// Consumes the value of the `min_tls_version` key.
    fn consume_min_tls_version(&mut self, value: String);
    /// Consumes the value of the `multi_region_failover.api_key` key.
    fn consume_multi_region_failover_api_key(&mut self, value: String);
    /// Consumes the value of the `multi_region_failover.dd_url` key.
    fn consume_multi_region_failover_dd_url(&mut self, value: String);
    /// Consumes the value of the `multi_region_failover.enabled` key.
    fn consume_multi_region_failover_enabled(&mut self, value: bool);
    /// Consumes the value of the `multi_region_failover.failover_metrics` key.
    fn consume_multi_region_failover_failover_metrics(&mut self, value: bool);
    /// Consumes the value of the `multi_region_failover.metric_allowlist` key.
    fn consume_multi_region_failover_metric_allowlist(&mut self, value: Vec<String>);
    /// Consumes the value of the `multi_region_failover.site` key.
    fn consume_multi_region_failover_site(&mut self, value: String);
    /// Consumes the value of the `no_proxy_nonexact_match` key.
    fn consume_no_proxy_nonexact_match(&mut self, value: bool);
    /// Consumes the value of the `observability_pipelines_worker.metrics.enabled` key.
    fn consume_observability_pipelines_worker_metrics_enabled(&mut self, value: bool);
    /// Consumes the value of the `observability_pipelines_worker.metrics.url` key.
    fn consume_observability_pipelines_worker_metrics_url(&mut self, value: String);
    /// Consumes the value of the `origin_detection_unified` key.
    fn consume_origin_detection_unified(&mut self, value: bool);
    /// Consumes the value of the `otlp_config.logs.enabled` key.
    fn consume_otlp_config_logs_enabled(&mut self, value: bool);
    /// Consumes the value of the `otlp_config.metrics.enabled` key.
    fn consume_otlp_config_metrics_enabled(&mut self, value: bool);
    /// Consumes the value of the `otlp_config.receiver.protocols.grpc.endpoint` key.
    fn consume_otlp_config_receiver_protocols_grpc_endpoint(&mut self, value: String);
    /// Consumes the value of the `otlp_config.receiver.protocols.grpc.max_recv_msg_size_mib` key.
    fn consume_otlp_config_receiver_protocols_grpc_max_recv_msg_size_mib(&mut self, value: i64);
    /// Consumes the value of the `otlp_config.receiver.protocols.grpc.transport` key.
    fn consume_otlp_config_receiver_protocols_grpc_transport(&mut self, value: String);
    /// Consumes the value of the `otlp_config.receiver.protocols.http.endpoint` key.
    fn consume_otlp_config_receiver_protocols_http_endpoint(&mut self, value: String);
    /// Consumes the value of the `otlp_config.traces.enabled` key.
    fn consume_otlp_config_traces_enabled(&mut self, value: bool);
    /// Consumes the value of the `otlp_config.traces.internal_port` key.
    fn consume_otlp_config_traces_internal_port(&mut self, value: i64);
    /// Consumes the value of the `otlp_config.traces.probabilistic_sampler.sampling_percentage` key.
    fn consume_otlp_config_traces_probabilistic_sampler_sampling_percentage(&mut self, value: f64);
    /// Consumes the value of the `provider_kind` key.
    fn consume_provider_kind(&mut self, value: String);
    /// Consumes the value of the `proxy.http` key.
    fn consume_proxy_http(&mut self, value: String);
    /// Consumes the value of the `proxy.https` key.
    fn consume_proxy_https(&mut self, value: String);
    /// Consumes the value of the `proxy.no_proxy` key.
    fn consume_proxy_no_proxy(&mut self, value: Vec<String>);
    /// Consumes the value of the `serializer_compressor_kind` key.
    fn consume_serializer_compressor_kind(&mut self, value: String);
    /// Consumes the value of the `serializer_max_payload_size` key.
    fn consume_serializer_max_payload_size(&mut self, value: i64);
    /// Consumes the value of the `serializer_max_series_payload_size` key.
    fn consume_serializer_max_series_payload_size(&mut self, value: i64);
    /// Consumes the value of the `serializer_max_series_points_per_payload` key.
    fn consume_serializer_max_series_points_per_payload(&mut self, value: i64);
    /// Consumes the value of the `serializer_max_series_uncompressed_payload_size` key.
    fn consume_serializer_max_series_uncompressed_payload_size(&mut self, value: i64);
    /// Consumes the value of the `serializer_max_uncompressed_payload_size` key.
    fn consume_serializer_max_uncompressed_payload_size(&mut self, value: i64);
    /// Consumes the value of the `serializer_zstd_compressor_level` key.
    fn consume_serializer_zstd_compressor_level(&mut self, value: i64);
    /// Consumes the value of the `site` key.
    fn consume_site(&mut self, value: String);
    /// Consumes the value of the `skip_ssl_validation` key.
    fn consume_skip_ssl_validation(&mut self, value: bool);
    /// Consumes the value of the `sslkeylogfile` key.
    fn consume_sslkeylogfile(&mut self, value: String);
    /// Consumes the value of the `statsd_forward_host` key.
    fn consume_statsd_forward_host(&mut self, value: String);
    /// Consumes the value of the `statsd_forward_port` key.
    fn consume_statsd_forward_port(&mut self, value: i64);
    /// Consumes the value of the `statsd_metric_blocklist` key.
    fn consume_statsd_metric_blocklist(&mut self, value: Vec<String>);
    /// Consumes the value of the `statsd_metric_blocklist_match_prefix` key.
    fn consume_statsd_metric_blocklist_match_prefix(&mut self, value: bool);
    /// Consumes the value of the `statsd_metric_namespace` key.
    fn consume_statsd_metric_namespace(&mut self, value: String);
    /// Consumes the value of the `statsd_metric_namespace_blacklist` key.
    fn consume_statsd_metric_namespace_blacklist(&mut self, value: Vec<String>);
    /// Consumes the value of the `syslog_rfc` key.
    fn consume_syslog_rfc(&mut self, value: bool);
    /// Consumes the value of the `syslog_uri` key.
    fn consume_syslog_uri(&mut self, value: String);
    /// Consumes the value of the `use_proxy_for_cloud_metadata` key.
    fn consume_use_proxy_for_cloud_metadata(&mut self, value: bool);
    /// Consumes the value of the `use_v2_api.series` key.
    fn consume_use_v2_api_series(&mut self, value: bool);
    /// Consumes the value of the `vector.metrics.enabled` key.
    fn consume_vector_metrics_enabled(&mut self, value: bool);
    /// Consumes the value of the `vector.metrics.url` key.
    fn consume_vector_metrics_url(&mut self, value: String);
    /// Consumes the value of the `vsock_addr` key.
    fn consume_vsock_addr(&mut self, value: String);

    /// Returns the first translation error recorded while consuming, if any.
    fn translate_error(&mut self) -> Option<TranslateError> {
        None
    }
}

/// Materializes a generated section struct from an empty object so absent optional sections
/// still yield their schema defaults when driven.
fn section_defaults<T: serde::de::DeserializeOwned>() -> T {
    serde_json::from_value(serde_json::Value::Object(serde_json::Map::new()))
        .expect("generated section defaults must deserialize from an empty object")
}

/// Drives a consumer over every supported key in `config`, calling each `consume_<key>` exactly
/// once with the value navigated from `config` (absent optional sections materialize defaults).
///
/// # Errors
///
/// Returns the first [`TranslateError`] the consumer recorded, surfaced after all keys are
/// consumed.
pub fn drive(config: &DatadogConfiguration, consumer: &mut impl DatadogConfigConsumer) -> Result<(), TranslateError> {
    let agent_ipc = config.agent_ipc.clone().unwrap_or_else(section_defaults);
    let apm_config = config.apm_config.clone().unwrap_or_else(section_defaults);
    let apm_config_obfuscation = apm_config.obfuscation.clone().unwrap_or_else(section_defaults);
    let apm_config_obfuscation_credit_cards = apm_config_obfuscation
        .credit_cards
        .clone()
        .unwrap_or_else(section_defaults);
    let apm_config_obfuscation_elasticsearch = apm_config_obfuscation
        .elasticsearch
        .clone()
        .unwrap_or_else(section_defaults);
    let apm_config_obfuscation_http = apm_config_obfuscation.http.clone().unwrap_or_else(section_defaults);
    let apm_config_obfuscation_memcached = apm_config_obfuscation
        .memcached
        .clone()
        .unwrap_or_else(section_defaults);
    let apm_config_obfuscation_mongodb = apm_config_obfuscation.mongodb.clone().unwrap_or_else(section_defaults);
    let apm_config_obfuscation_opensearch = apm_config_obfuscation
        .opensearch
        .clone()
        .unwrap_or_else(section_defaults);
    let apm_config_obfuscation_redis = apm_config_obfuscation.redis.clone().unwrap_or_else(section_defaults);
    let apm_config_obfuscation_valkey = apm_config_obfuscation.valkey.clone().unwrap_or_else(section_defaults);
    let data_plane = config.data_plane.clone().unwrap_or_else(section_defaults);
    let data_plane_dogstatsd = data_plane.dogstatsd.clone().unwrap_or_else(section_defaults);
    let data_plane_otlp = data_plane.otlp.clone().unwrap_or_else(section_defaults);
    let data_plane_otlp_proxy = data_plane_otlp.proxy.clone().unwrap_or_else(section_defaults);
    let data_plane_otlp_proxy_logs = data_plane_otlp_proxy.logs.clone().unwrap_or_else(section_defaults);
    let data_plane_otlp_proxy_metrics = data_plane_otlp_proxy.metrics.clone().unwrap_or_else(section_defaults);
    let data_plane_otlp_proxy_traces = data_plane_otlp_proxy.traces.clone().unwrap_or_else(section_defaults);
    let enable_payloads = config.enable_payloads.clone().unwrap_or_else(section_defaults);
    let multi_region_failover = config.multi_region_failover.clone().unwrap_or_else(section_defaults);
    let observability_pipelines_worker = config
        .observability_pipelines_worker
        .clone()
        .unwrap_or_else(section_defaults);
    let observability_pipelines_worker_metrics = observability_pipelines_worker
        .metrics
        .clone()
        .unwrap_or_else(section_defaults);
    let otlp_config = config.otlp_config.clone().unwrap_or_else(section_defaults);
    let otlp_config_logs = otlp_config.logs.clone().unwrap_or_else(section_defaults);
    let otlp_config_metrics = otlp_config.metrics.clone().unwrap_or_else(section_defaults);
    let otlp_config_receiver = otlp_config.receiver.clone().unwrap_or_else(section_defaults);
    let otlp_config_receiver_protocols = otlp_config_receiver.protocols.clone().unwrap_or_else(section_defaults);
    let otlp_config_receiver_protocols_grpc = otlp_config_receiver_protocols
        .grpc
        .clone()
        .unwrap_or_else(section_defaults);
    let otlp_config_receiver_protocols_http = otlp_config_receiver_protocols
        .http
        .clone()
        .unwrap_or_else(section_defaults);
    let otlp_config_traces = otlp_config.traces.clone().unwrap_or_else(section_defaults);
    let otlp_config_traces_probabilistic_sampler = otlp_config_traces
        .probabilistic_sampler
        .clone()
        .unwrap_or_else(section_defaults);
    let proxy = config.proxy.clone().unwrap_or_else(section_defaults);
    let use_v2_api = config.use_v2_api.clone().unwrap_or_else(section_defaults);
    let vector = config.vector.clone().unwrap_or_else(section_defaults);
    let vector_metrics = vector.metrics.clone().unwrap_or_else(section_defaults);

    consumer.consume_additional_endpoints(config.additional_endpoints.clone());
    consumer.consume_agent_ipc_grpc_max_message_size(agent_ipc.grpc_max_message_size.clone());
    consumer.consume_aggregator_stop_timeout(config.aggregator_stop_timeout.clone());
    consumer.consume_allow_arbitrary_tags(config.allow_arbitrary_tags.clone());
    consumer.consume_api_key(config.api_key.clone());
    consumer.consume_apm_config_obfuscation_credit_cards_enabled(apm_config_obfuscation_credit_cards.enabled.clone());
    consumer.consume_apm_config_obfuscation_credit_cards_keep_values(
        apm_config_obfuscation_credit_cards.keep_values.clone(),
    );
    consumer.consume_apm_config_obfuscation_credit_cards_luhn(apm_config_obfuscation_credit_cards.luhn.clone());
    consumer.consume_apm_config_obfuscation_elasticsearch_enabled(apm_config_obfuscation_elasticsearch.enabled.clone());
    consumer.consume_apm_config_obfuscation_elasticsearch_keep_values(
        apm_config_obfuscation_elasticsearch.keep_values.clone(),
    );
    consumer.consume_apm_config_obfuscation_elasticsearch_obfuscate_sql_values(
        apm_config_obfuscation_elasticsearch.obfuscate_sql_values.clone(),
    );
    consumer.consume_apm_config_obfuscation_http_remove_paths_with_digits(
        apm_config_obfuscation_http.remove_paths_with_digits.clone(),
    );
    consumer.consume_apm_config_obfuscation_http_remove_query_string(
        apm_config_obfuscation_http.remove_query_string.clone(),
    );
    consumer.consume_apm_config_obfuscation_memcached_enabled(apm_config_obfuscation_memcached.enabled.clone());
    consumer
        .consume_apm_config_obfuscation_memcached_keep_command(apm_config_obfuscation_memcached.keep_command.clone());
    consumer.consume_apm_config_obfuscation_mongodb_enabled(apm_config_obfuscation_mongodb.enabled.clone());
    consumer.consume_apm_config_obfuscation_mongodb_keep_values(apm_config_obfuscation_mongodb.keep_values.clone());
    consumer.consume_apm_config_obfuscation_mongodb_obfuscate_sql_values(
        apm_config_obfuscation_mongodb.obfuscate_sql_values.clone(),
    );
    consumer.consume_apm_config_obfuscation_opensearch_enabled(apm_config_obfuscation_opensearch.enabled.clone());
    consumer
        .consume_apm_config_obfuscation_opensearch_keep_values(apm_config_obfuscation_opensearch.keep_values.clone());
    consumer.consume_apm_config_obfuscation_opensearch_obfuscate_sql_values(
        apm_config_obfuscation_opensearch.obfuscate_sql_values.clone(),
    );
    consumer.consume_apm_config_obfuscation_redis_enabled(apm_config_obfuscation_redis.enabled.clone());
    consumer.consume_apm_config_obfuscation_redis_remove_all_args(apm_config_obfuscation_redis.remove_all_args.clone());
    consumer.consume_apm_config_obfuscation_valkey_enabled(apm_config_obfuscation_valkey.enabled.clone());
    consumer
        .consume_apm_config_obfuscation_valkey_remove_all_args(apm_config_obfuscation_valkey.remove_all_args.clone());
    consumer.consume_bind_host(config.bind_host.clone());
    consumer.consume_cmd_port(config.cmd_port.clone());
    consumer.consume_cri_connection_timeout(config.cri_connection_timeout.clone());
    consumer.consume_cri_query_timeout(config.cri_query_timeout.clone());
    consumer.consume_data_plane_api_listen_address(data_plane.api_listen_address.clone());
    consumer.consume_data_plane_dogstatsd_aggregator_tag_filter_cache_capacity(
        data_plane_dogstatsd.aggregator_tag_filter_cache_capacity.clone(),
    );
    consumer.consume_data_plane_log_file(data_plane.log_file.clone());
    consumer.consume_data_plane_otlp_proxy_logs_enabled(data_plane_otlp_proxy_logs.enabled.clone());
    consumer.consume_data_plane_otlp_proxy_metrics_enabled(data_plane_otlp_proxy_metrics.enabled.clone());
    consumer.consume_data_plane_otlp_proxy_traces_enabled(data_plane_otlp_proxy_traces.enabled.clone());
    consumer.consume_data_plane_remote_agent_enabled(data_plane.remote_agent_enabled.clone());
    consumer.consume_data_plane_secure_api_listen_address(data_plane.secure_api_listen_address.clone());
    consumer.consume_data_plane_use_new_config_stream_endpoint(data_plane.use_new_config_stream_endpoint.clone());
    consumer.consume_dd_url(config.dd_url.clone());
    consumer.consume_dogstatsd_buffer_size(config.dogstatsd_buffer_size.clone());
    consumer.consume_dogstatsd_capture_depth(config.dogstatsd_capture_depth.clone());
    consumer.consume_dogstatsd_capture_path(config.dogstatsd_capture_path.clone());
    consumer.consume_dogstatsd_context_expiry_seconds(config.dogstatsd_context_expiry_seconds.clone());
    consumer.consume_dogstatsd_entity_id_precedence(config.dogstatsd_entity_id_precedence.clone());
    consumer.consume_dogstatsd_eol_required(config.dogstatsd_eol_required.clone());
    consumer.consume_dogstatsd_flush_incomplete_buckets(config.dogstatsd_flush_incomplete_buckets.clone());
    consumer.consume_dogstatsd_log_file(config.dogstatsd_log_file.clone());
    consumer.consume_dogstatsd_log_file_max_rolls(config.dogstatsd_log_file_max_rolls.clone());
    consumer.consume_dogstatsd_log_file_max_size(config.dogstatsd_log_file_max_size.clone());
    consumer.consume_dogstatsd_logging_enabled(config.dogstatsd_logging_enabled.clone());
    consumer.consume_dogstatsd_mapper_cache_size(config.dogstatsd_mapper_cache_size.clone());
    consumer.consume_dogstatsd_mapper_profiles(config.dogstatsd_mapper_profiles.clone());
    consumer.consume_dogstatsd_metrics_stats_enable(config.dogstatsd_metrics_stats_enable.clone());
    consumer.consume_dogstatsd_no_aggregation_pipeline(config.dogstatsd_no_aggregation_pipeline.clone());
    consumer.consume_dogstatsd_non_local_traffic(config.dogstatsd_non_local_traffic.clone());
    consumer.consume_dogstatsd_origin_detection(config.dogstatsd_origin_detection.clone());
    consumer.consume_dogstatsd_origin_detection_client(config.dogstatsd_origin_detection_client.clone());
    consumer.consume_dogstatsd_origin_optout_enabled(config.dogstatsd_origin_optout_enabled.clone());
    consumer.consume_dogstatsd_port(config.dogstatsd_port.clone());
    consumer.consume_dogstatsd_so_rcvbuf(config.dogstatsd_so_rcvbuf.clone());
    consumer.consume_dogstatsd_socket(config.dogstatsd_socket.clone());
    consumer.consume_dogstatsd_stream_log_too_big(config.dogstatsd_stream_log_too_big.clone());
    consumer.consume_dogstatsd_stream_socket(config.dogstatsd_stream_socket.clone());
    consumer.consume_dogstatsd_string_interner_size(config.dogstatsd_string_interner_size.clone());
    consumer.consume_dogstatsd_tag_cardinality(config.dogstatsd_tag_cardinality.clone());
    consumer.consume_dogstatsd_tags(config.dogstatsd_tags.clone());
    consumer.consume_enable_payloads_events(enable_payloads.events.clone());
    consumer.consume_enable_payloads_series(enable_payloads.series.clone());
    consumer.consume_enable_payloads_service_checks(enable_payloads.service_checks.clone());
    consumer.consume_enable_payloads_sketches(enable_payloads.sketches.clone());
    consumer.consume_env(config.env.clone());
    consumer.consume_forwarder_apikey_validation_interval(config.forwarder_apikey_validation_interval.clone());
    consumer.consume_forwarder_backoff_base(config.forwarder_backoff_base.clone());
    consumer.consume_forwarder_backoff_factor(config.forwarder_backoff_factor.clone());
    consumer.consume_forwarder_backoff_max(config.forwarder_backoff_max.clone());
    consumer.consume_forwarder_connection_reset_interval(config.forwarder_connection_reset_interval.clone());
    consumer.consume_forwarder_flush_to_disk_mem_ratio(config.forwarder_flush_to_disk_mem_ratio.clone());
    consumer.consume_forwarder_high_prio_buffer_size(config.forwarder_high_prio_buffer_size.clone());
    consumer.consume_forwarder_http_protocol(config.forwarder_http_protocol.clone());
    consumer.consume_forwarder_max_concurrent_requests(config.forwarder_max_concurrent_requests.clone());
    consumer.consume_forwarder_num_workers(config.forwarder_num_workers.clone());
    consumer.consume_forwarder_outdated_file_in_days(config.forwarder_outdated_file_in_days.clone());
    consumer.consume_forwarder_recovery_interval(config.forwarder_recovery_interval.clone());
    consumer.consume_forwarder_recovery_reset(config.forwarder_recovery_reset.clone());
    consumer.consume_forwarder_retry_queue_capacity_time_interval_sec(
        config.forwarder_retry_queue_capacity_time_interval_sec.clone(),
    );
    consumer.consume_forwarder_retry_queue_max_size(config.forwarder_retry_queue_max_size.clone());
    consumer.consume_forwarder_retry_queue_payloads_max_size(config.forwarder_retry_queue_payloads_max_size.clone());
    consumer.consume_forwarder_stop_timeout(config.forwarder_stop_timeout.clone());
    consumer.consume_forwarder_storage_max_disk_ratio(config.forwarder_storage_max_disk_ratio.clone());
    consumer.consume_forwarder_storage_max_size_in_bytes(config.forwarder_storage_max_size_in_bytes.clone());
    consumer.consume_forwarder_storage_path(config.forwarder_storage_path.clone());
    consumer.consume_forwarder_timeout(config.forwarder_timeout.clone());
    consumer.consume_histogram_aggregates(config.histogram_aggregates.clone());
    consumer.consume_histogram_copy_to_distribution(config.histogram_copy_to_distribution.clone());
    consumer.consume_histogram_copy_to_distribution_prefix(config.histogram_copy_to_distribution_prefix.clone());
    consumer.consume_log_format_rfc3339(config.log_format_rfc3339.clone());
    consumer.consume_log_level(config.log_level.clone());
    consumer.consume_log_payloads(config.log_payloads.clone());
    consumer.consume_metric_filterlist(config.metric_filterlist.clone());
    consumer.consume_metric_filterlist_match_prefix(config.metric_filterlist_match_prefix.clone());
    consumer.consume_min_tls_version(config.min_tls_version.clone());
    consumer.consume_multi_region_failover_api_key(multi_region_failover.api_key.clone());
    consumer.consume_multi_region_failover_dd_url(multi_region_failover.dd_url.clone());
    consumer.consume_multi_region_failover_enabled(multi_region_failover.enabled.clone());
    consumer.consume_multi_region_failover_failover_metrics(multi_region_failover.failover_metrics.clone());
    consumer.consume_multi_region_failover_metric_allowlist(multi_region_failover.metric_allowlist.clone());
    consumer.consume_multi_region_failover_site(multi_region_failover.site.clone());
    consumer.consume_no_proxy_nonexact_match(config.no_proxy_nonexact_match.clone());
    consumer
        .consume_observability_pipelines_worker_metrics_enabled(observability_pipelines_worker_metrics.enabled.clone());
    consumer.consume_observability_pipelines_worker_metrics_url(observability_pipelines_worker_metrics.url.clone());
    consumer.consume_origin_detection_unified(config.origin_detection_unified.clone());
    consumer.consume_otlp_config_logs_enabled(otlp_config_logs.enabled.clone());
    consumer.consume_otlp_config_metrics_enabled(otlp_config_metrics.enabled.clone());
    consumer.consume_otlp_config_receiver_protocols_grpc_endpoint(otlp_config_receiver_protocols_grpc.endpoint.clone());
    consumer.consume_otlp_config_receiver_protocols_grpc_max_recv_msg_size_mib(
        otlp_config_receiver_protocols_grpc.max_recv_msg_size_mib.clone(),
    );
    consumer
        .consume_otlp_config_receiver_protocols_grpc_transport(otlp_config_receiver_protocols_grpc.transport.clone());
    consumer.consume_otlp_config_receiver_protocols_http_endpoint(otlp_config_receiver_protocols_http.endpoint.clone());
    consumer.consume_otlp_config_traces_enabled(otlp_config_traces.enabled.clone());
    consumer.consume_otlp_config_traces_internal_port(otlp_config_traces.internal_port.clone());
    consumer.consume_otlp_config_traces_probabilistic_sampler_sampling_percentage(
        otlp_config_traces_probabilistic_sampler.sampling_percentage.clone(),
    );
    consumer.consume_provider_kind(config.provider_kind.clone());
    consumer.consume_proxy_http(proxy.http.clone());
    consumer.consume_proxy_https(proxy.https.clone());
    consumer.consume_proxy_no_proxy(proxy.no_proxy.clone());
    consumer.consume_serializer_compressor_kind(config.serializer_compressor_kind.clone());
    consumer.consume_serializer_max_payload_size(config.serializer_max_payload_size.clone());
    consumer.consume_serializer_max_series_payload_size(config.serializer_max_series_payload_size.clone());
    consumer.consume_serializer_max_series_points_per_payload(config.serializer_max_series_points_per_payload.clone());
    consumer.consume_serializer_max_series_uncompressed_payload_size(
        config.serializer_max_series_uncompressed_payload_size.clone(),
    );
    consumer.consume_serializer_max_uncompressed_payload_size(config.serializer_max_uncompressed_payload_size.clone());
    consumer.consume_serializer_zstd_compressor_level(config.serializer_zstd_compressor_level.clone());
    consumer.consume_site(config.site.clone());
    consumer.consume_skip_ssl_validation(config.skip_ssl_validation.clone());
    consumer.consume_sslkeylogfile(config.sslkeylogfile.clone());
    consumer.consume_statsd_forward_host(config.statsd_forward_host.clone());
    consumer.consume_statsd_forward_port(config.statsd_forward_port.clone());
    consumer.consume_statsd_metric_blocklist(config.statsd_metric_blocklist.clone());
    consumer.consume_statsd_metric_blocklist_match_prefix(config.statsd_metric_blocklist_match_prefix.clone());
    consumer.consume_statsd_metric_namespace(config.statsd_metric_namespace.clone());
    consumer.consume_statsd_metric_namespace_blacklist(config.statsd_metric_namespace_blacklist.clone());
    consumer.consume_syslog_rfc(config.syslog_rfc.clone());
    consumer.consume_syslog_uri(config.syslog_uri.clone());
    consumer.consume_use_proxy_for_cloud_metadata(config.use_proxy_for_cloud_metadata.clone());
    consumer.consume_use_v2_api_series(use_v2_api.series.clone());
    consumer.consume_vector_metrics_enabled(vector_metrics.enabled.clone());
    consumer.consume_vector_metrics_url(vector_metrics.url.clone());
    consumer.consume_vsock_addr(config.vsock_addr.clone());

    match consumer.translate_error() {
        Some(e) => Err(e),
        None => Ok(()),
    }
}
