include:
  - .gitlab/*.yml

stages:
  - test
  - build
  - correctness
  - benchmark
  - release
  - internal

# Our workflow rules let us override specific variables, in a consistent way, depending on whether this is an "internal"
# run (we consider all non-tagged pipeline triggers to be "internal") or a "release" run.
#
# This mostly controls how we tag our ADP container images, and the base image we use when building those ADP container
# images.
workflow:
  rules:
    - if: $CI_COMMIT_TAG == null
      variables:
        ADP_APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}
        BASE_ADP_IMAGE_VERSION: "v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"
        APP_DEV_BUILD: "true"

    - if: $CI_COMMIT_TAG
      variables:
        ADP_APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}
        BASE_ADP_IMAGE_VERSION: ${CI_COMMIT_TAG}
        APP_DEV_BUILD: "false"

variables:
  # High-level repository paths we build off of, and dedicated images needed for various jobs.
  IMAGE_REGISTRY: "registry.ddbuild.io"
  DOCKER_BUILD_IMAGE: "registry.ddbuild.io/docker:24.0.4-jammy"
  GBI_BASE_IMAGE: "${IMAGE_REGISTRY}/images/base/gbi-ubuntu_2204:release"
  PUBLIC_BASE_IMAGE: "${IMAGE_REGISTRY}/images/mirror/ubuntu:24.04"

  # Base repository paths for where our CI images go, whether they're helper images or actual
  # output artifacts like ADP itself.
  SALUKI_IMAGE_REPO_PREFIX: "saluki"
  SALUKI_IMAGE_REPO_BASE: "${IMAGE_REGISTRY}/${SALUKI_IMAGE_REPO_PREFIX}"
  SALUKI_BUILD_CI_IMAGE: "${SALUKI_IMAGE_REPO_BASE}/build-ci:latest"
  SALUKI_GENERAL_CI_IMAGE: "${SALUKI_IMAGE_REPO_BASE}/general-ci:latest"
  SALUKI_SMP_CI_IMAGE: "${SALUKI_IMAGE_REPO_BASE}/smp-ci:latest"

  # Converged Datadog Agent-specific variables, which control how we build the converged Datadog Agent image that we
  # publicly publish.
  PUBLIC_DSD_VERSION: "7.67.1"
  PUBLIC_DD_AGENT_VERSION: "7.67.1-jmx"

  # Base images to copy Agent Data Plane into, depending on whether the image is meant for our internal environment or
  # public registries.
  ADP_INTERNAL_BASE_IMAGE: "${GBI_BASE_IMAGE}"
  ADP_PUBLIC_BASE_IMAGE: "${PUBLIC_BASE_IMAGE}"

  # We use our specific build image as it's built to have the right (specifically: old enough) version of glibc, and
  # other necessary tooling, to build ADP for the target platforms we need it to be able to run on.
  ADP_BUILD_IMAGE: "${SALUKI_BUILD_CI_IMAGE}"

  ADP_IMAGE_REPO_NAME: "${SALUKI_IMAGE_REPO_PREFIX}/agent-data-plane"
  CHECKS_AGENT_IMAGE_REPO_NAME: "${SALUKI_IMAGE_REPO_PREFIX}/checks-agent"

  # The image version depending on whether this is an official release or not: v3727183-d55fef5a (not official) va
  # 0.1.10 (official), etc.
  ADP_IMAGE_VERSION: "${BASE_ADP_IMAGE_VERSION}"
  ADP_IMAGE_VERSION_FIPS: "${BASE_ADP_IMAGE_VERSION}-fips"

  # The tagged image, minus the registry portion.
  #
  # Used for specifying the image repository to use when publishing the ADP container images, as the registry will be
  # varied depending on where it's being pushed.
  ADP_IMAGE_TAG: "agent-data-plane:${ADP_IMAGE_VERSION}"
  ADP_IMAGE_TAG_FIPS: "agent-data-plane:${ADP_IMAGE_VERSION_FIPS}"

  # The full image path.
  #
  # Used to specifically reference the built ADP image in certain jobs.
  ADP_FULL_IMAGE_TAG: "${IMAGE_REGISTRY}/saluki/agent-data-plane:${ADP_IMAGE_VERSION}"
  ADP_FULL_IMAGE_TAG_FIPS: "${IMAGE_REGISTRY}/saluki/agent-data-plane:${ADP_IMAGE_VERSION_FIPS}"
  CHECKS_AGENT_FULL_IMAGE_TAG: "${IMAGE_REGISTRY}/saluki/checks-agent:${ADP_IMAGE_VERSION}"

default:
  tags: ["arch:amd64"]

# Run a job on official releases (i.e. tagged).
.on_official_release:
  rules:
    if: $CI_COMMIT_TAG

# Common build-specific variables that need to be shared across stages.
.build-common-variables:
  variables:
    BUILD_PROFILE: "optimized-release"
    BUILD_FEATURES: "default"
    FIPS_ENABLED: "false"

.linux-test-job:
  image: "${SALUKI_BUILD_CI_IMAGE}"

.linux-amd64-test-job:
  extends: .linux-test-job
  tags: ["arch:amd64"]

.linux-amd64-test-job-heavy:
  extends: .linux-amd64-test-job
  variables:
    # Compiling Saluki is intensive, so we want to make sure we get
    # a beefy-enough runner.
    KUBERNETES_CPU_REQUEST: "16"
    KUBERNETES_MEMORY_REQUEST: "8Gi"
    KUBERNETES_MEMORY_LIMIT: "12Gi"

.linux-arm64-test-job:
  extends: .linux-test-job
  tags: ["arch:arm64"]

.linux-arm64-test-job-heavy:
  extends: .linux-arm64-test-job
  variables:
    # Compiling Saluki is intensive, so we want a beefy runner.
    KUBERNETES_CPU_REQUEST: "16"
    KUBERNETES_MEMORY_REQUEST: "8Gi"
    KUBERNETES_MEMORY_LIMIT: "12Gi"

.macos-amd64-test-job:
  tags: ["macos:ventura-amd64", "specific:true"]

.macos-arm64-test-job:
  tags: ["macos:ventura-arm64", "specific:true"]
