include:
  - .gitlab/*.yml

stages:
  - test
  - build
  - correctness
  - benchmark
  - release
  - internal

variables:
  # High-level repository paths we build off of, and dedicated images needed for various jobs.
  IMAGE_REGISTRY: "registry.ddbuild.io"
  DOCKER_BUILD_IMAGE: "486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:20.10-py3"
  GBI_BASE_IMAGE: "${IMAGE_REGISTRY}/images/base/gbi-ubuntu_2204:release"

  # Base repository paths for where our CI images go, whether they're helper images or actual
  # output artifacts like ADP itself.
  SALUKI_IMAGE_REPO_BASE: "${IMAGE_REGISTRY}/saluki"
  SALUKI_BUILD_CI_IMAGE: "${SALUKI_IMAGE_REPO_BASE}/build-ci:latest"
  SALUKI_SMP_CI_IMAGE: "${SALUKI_IMAGE_REPO_BASE}/smp-ci:latest"

  # ADP-specific variables, controlling how we build ADP images, how we version them, and where we push them.
  ADP_IMAGE_BASE: "${SALUKI_IMAGE_REPO_BASE}/agent-data-plane"

  # Converged Datadog Agent-specific variables, which control how we build the converged Datadog Agent image, both for
  # internal and public releases.
  BASE_DD_AGENT_VERSION: "7.59.0"
  BASE_DD_AGENT_VERSION_INTERNAL: "7-59-0"

  INTERNAL_DD_AGENT_IMAGE: "${IMAGE_REGISTRY}/datadog-agent:${BASE_DD_AGENT_VERSION_INTERNAL}-jmx"
  PUBLIC_DD_AGENT_IMAGE_BASE: "gcr.io/datadoghq/agent"
  PUBLIC_DD_AGENT_IMAGE: "${PUBLIC_DD_AGENT_IMAGE_BASE}:${BASE_DD_AGENT_VERSION}-jmx"

default:
  tags: ["arch:amd64"]

# Run a job on official releases (i.e. tagged)
.on_official_release:
  rules:
    if: $CI_COMMIT_TAG
