include:
  - .gitlab/*.yml

stages:
  - test
  - build
  - internal

variables:
  VERSION_BASE: "0.1.0"
  IMAGE_REGISTRY: "registry.ddbuild.io"
  IMAGE_REPO_BASE: "${IMAGE_REGISTRY}/saluki"
  BUILD_CI_IMAGE: "${IMAGE_REPO_BASE}/build-ci:v31870615-026a2093"
  DOCKER_BUILD_IMAGE: "486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:20.10-py3"
  # Compiling Rust is intensive. ¯\_(ツ)_/¯
  KUBERNETES_CPU_REQUEST: "16"
  KUBERNETES_MEMORY_REQUEST: "8Gi"
  KUBERNETES_MEMORY_LIMIT: "12Gi"

default:
  tags: ["arch:amd64"]
