include:
  - .gitlab/*.yml

stages:
  - test
  - build
  - correctness
  - benchmark
  - internal

variables:
  # High-level repository paths we build off of, and dedicated images needed for various jobs.
  IMAGE_REGISTRY: "registry.ddbuild.io"
  DOCKER_BUILD_IMAGE: "486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:20.10-py3"
  GBI_BASE_IMAGE: "${IMAGE_REGISTRY}/images/base/gbi-ubuntu_2204:release"

  # Base repository paths for where our CI images go, whether they're helper images or actual
  # output artifacts like ADP itself.
  SALUKI_IMAGE_REPO_BASE: "${IMAGE_REGISTRY}/saluki"
  SALUKI_BUILD_CI_IMAGE: "${SALUKI_IMAGE_REPO_BASE}/build-ci:v42220630-6ad1da61"
  SALUKI_SMP_CI_IMAGE: "${SALUKI_IMAGE_REPO_BASE}/smp-ci:v40512394-da9e8d37"

  # ADP-specific variables, controlling how we build ADP images, how we version them, and where we push them.
  ADP_VERSION_BASE: "0.1.0"
  ADP_IMAGE_BASE: "${SALUKI_IMAGE_REPO_BASE}/agent-data-plane"

  # Converged Datadog Agent-specific variables, which control how we build the converged Datadog Agent image
  # used internally for testing.
  DD_AGENT_VERSION: "7-57-0-rc-4-jmx"
  DD_AGENT_IMAGE_BASE: "${IMAGE_REGISTRY}/datadog-agent"
  DD_AGENT_IMAGE: "${DD_AGENT_IMAGE_BASE}:${DD_AGENT_VERSION}"

  # Version of the Datadog Agent/standalone DogStatsD server that we'll use both when running SMP benchmarks
  # as well as correctness tests, to ensure we're always running our various comparisons against the same version.
  #
  # TODO: We should unify this with `DD_AGENT_VERSION`, even if it means we have two versions of the variable
  # to hold the dot-separated and dash-separated versions.
  DD_AGENT_TEST_VERSION: "7.58.0"

.setup-env: &setup-env
  - 'export ADP_VERSION="${ADP_VERSION_BASE}"'
  - '[ -z "$CI_COMMIT_TAG" ] && export ADP_VERSION="${ADP_VERSION_BASE}-beta-${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"'
  - '[ "$CI_PIPELINE_SOURCE" == "schedule" ] && export ADP_VERSION="${ADP_VERSION_BASE}-nightly-${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"'
  - echo $ADP_VERSION

default:
  tags: ["arch:amd64"]
  before_script:
    - *setup-env
