StylesPath = .vale/styles
MinAlertLevel = suggestion
Packages = Google
Vocab = technical

[formats]
# Rust + Markdown
rs = md

# Per-section settings:
# - `Vale.Terms`: disabled because it's driven by `accept.txt` casing, which conflicts
#   with our preferred forms. Required-case enforcement is handled by `Saluki/Terms.yml`.
# - `Google.Acronyms`: disabled because requiring acronyms to be introduced as
#   `Spelled Out (FOO)` is overzealous for docs aimed at engineers familiar with the domain.

[*.md]
BasedOnStyles = Saluki, Vale, Google
Vale.Terms = NO
Google.Acronyms = NO

# Looser expectations around code documentation since it's not prose, and
# we specifically want to target doc comments, not all comments, so we use
# a custom view that extracts only doc comments.
[*.rs]
BasedOnStyles = Saluki, Vale, Google
View = RustDocComments
Vale.Terms = NO
Google.Acronyms = NO
