too-many-arguments-threshold = 8

disallowed-methods = [
  { path = "std::str::from_utf8", reason = "Use simdutf8::basic::from_utf8 instead" },
  { path = "core::str::from_utf8", reason = "Use simdutf8::basic::from_utf8 instead" },
]
