[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = []

[bans]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "0BSD",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "Unicode-DFS-2016",
  "Zlib",
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[sources]
allow-git = [
  # Git dependency for `containerd-client` to:
  # - add specific `prost-build` settings that allow type-erased payloads in containerd events to be decoded
  # - update to tonic 0.12/prost 0.13 to eliminate having both hyper 0.14/hyper 1.0 in the the dep tree
  #
  # Will be removed once all work is upstreamed and a release is published.
  "https://github.com/tobz/rust-extensions",
]
