[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = []

[bans]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "Unicode-DFS-2016",
  "Zlib"
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
allow-git = [
    # Git dependency for `containerd-client` to add specific `prost-build` settings that allow type-erased payloads in
    # containerd events to be decoded.
    #
    # Will be removed once a new release (current is 0.5.0) is published.
    "https://github.com/containerd/rust-extensions",
    # Git dependency for `async-compression` to add support to access `total_in`/`total_out` for determining
    # the amount of compressed data when building requests.
    #
    # Still need to submit a pull request.
   "https://github.com/tobz/async-compression.git"
]
