[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = [
  { id = "RUSTSEC-2024-0436", reason = "paste is a stable crate and we do not consider it being unmaintained as a security risk" },
]

[bans]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "0BSD",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "Unicode-3.0",
  "Zlib",
]

[sources]
allow-git = [
  # Git dependency for `lading_payload`, which isn't published on crates.io. We use a tagged version, though, so this
  # is reasonable from our perspective... especially considering the fact that we're the ones who own the repository.
  "https://github.com/DataDog/lading",

  # Git dependency for `triomphe`, due to needing unreleased support for `Arc::into_unique`.
  "https://github.com/Manishearth/triomphe",

  # Git dependency for `containerd-client`, to pull in an updated version that uses more recent transitive dependencies,
  # and isn't yet released.
  "https://github.com/containerd/rust-extensions"
]
