[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = []

[bans]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "Unicode-DFS-2016",
  "Zlib"
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
allow-git = [
    # Fork of `socket2` being used for SO_PASSCRED/out-of-band support on Unix domain sockets.
    #
    # Will be removed once https://github.com/rust-lang/socket2/pull/506 is merged.
    "https://github.com/tobz/socket2.git",
]
