//! The hand-edited expectations for the corpus replay. Edit this table directly.
//!
//! An entry pins ADP's exact result for one check where ADP does not match the recorded Agent;
//! see `expectations.rs` for the rules. A fix in ADP makes its entry fail with "remove this
//! check's expectation". Entries are written as [`Entry`] data and sorted by check identity:
//! origin, tier, checkpoint, getter, key. Entries whose [`Cause`] is `agent-load-write`,
//! `translator-rejects-value`, `wire-number-loss` or `raw-json-representation` are `intentional`:
//! the Agent writes the value only while starting up, ADP deliberately rejects an invalid enum or
//! size string, the Agent's wire format loses the number, or the compared getter reads a raw
//! string where ADP decodes structure (see `RAW_JSON_REPRESENTATION`). Every other entry is a
//! `known_bug`. Causes link tracking issues without changing which individual checks they explain.

use super::expectations::Tier::{Bootstrap, Derived, Deserialize, Leaf, Translate};
use super::expectations::{intentional, known_bug, Adp, Cause, Entry, Expectation};

/// Returns the table of expectations.
pub(crate) fn expectations() -> Vec<Expectation> {
    vec![
        intentional(Entry {
            origin: "api-key-whitespace-yaml",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "api_key",
            adp: Adp::value("\" cr-key \""),
            cause: AGENT_LOAD_WRITE,
        }),
        known_bug(Entry {
            origin: "baseline-default",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "container_cgroup_root",
            adp: Adp::value("\"/host/sys/fs/cgroup/\""),
            cause: UNRESOLVED_AGENT_DEFAULT,
        }),
        known_bug(Entry {
            origin: "baseline-default",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "container_proc_root",
            adp: Adp::value("\"/host/proc\""),
            cause: UNRESOLVED_AGENT_DEFAULT,
        }),
        known_bug(Entry {
            origin: "baseline-default",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "data_plane.log_file",
            adp: Adp::value("\"${log_path}/agent-data-plane.log\""),
            cause: UNRESOLVED_AGENT_DEFAULT,
        }),
        known_bug(Entry {
            origin: "baseline-default",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "dogstatsd_log_file",
            adp: Adp::value("\"${log_path}/dogstatsd_info/dogstatsd-stats.log\""),
            cause: UNRESOLVED_AGENT_DEFAULT,
        }),
        known_bug(Entry {
            origin: "baseline-default",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "dogstatsd_socket",
            adp: Adp::value("None"),
            cause: UNRESOLVED_AGENT_DEFAULT,
        }),
        known_bug(Entry {
            origin: "baseline-default",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "forwarder_storage_path",
            adp: Adp::value("\"${run_path}/transactions_to_retry\""),
            cause: UNRESOLVED_AGENT_DEFAULT,
        }),
        known_bug(Entry {
            origin: "baseline-default",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "run_path",
            adp: Adp::value("\"${run_path}\""),
            cause: RUN_PATH_DEFAULT,
        }),
        intentional(Entry {
            origin: "baseline-default",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "proxy.no_proxy",
            adp: Adp::value("[]"),
            cause: AGENT_LOAD_WRITE,
        }),
        known_bug(Entry {
            origin: "breadth-env",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "metric_tag_filterlist",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "breadth-env",
            tier: Bootstrap,
            at: "snapshot",
            getter: "-",
            key: "<boot>",
            adp: Adp::error(
                "failed to build the configuration base: environment variable `DD_METRIC_TAG_FILTERLIST` (metric_tag_filterlist): invalid JSON: expected value at line 1 column 1",
            ),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "breadth-env",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "metric_tag_filterlist",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_log_file_max_size",
            adp: Adp::error(
                "error translating config key `dogstatsd_log_file_max_size`, couldn't parse \"cr-a\" into a ByteSize, cannot parse float from empty string",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error(
                "error translating config key `dogstatsd_mapper_profiles`: invalid type: string \"cr-a\", expected struct RawProfile",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_tag_cardinality",
            adp: Adp::error(
                "error translating config key `dogstatsd_tag_cardinality`: unknown tag cardinality `cr-a`; expected low, orch, orchestrator, high, or none",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "log_file_max_size",
            adp: Adp::error(
                "error translating config key `log_file_max_size`, couldn't parse \"cr-a\" into a ByteSize, cannot parse float from empty string",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.histograms.mode",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.histograms.mode`: unknown histogram mode `cr-a`; expected `nobuckets`, `counters`, or `distributions`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.summaries.mode",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.summaries.mode`: unknown summary mode `cr-a`; expected `gauges` or `noquantiles`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.sums.cumulative_monotonic_mode",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.sums.cumulative_monotonic_mode`: unknown cumulative monotonic sum mode `cr-a`; expected `to_delta` or `raw_value`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.sums.initial_cumulative_monotonic_value",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.sums.initial_cumulative_monotonic_value`: unknown initial cumulative monotonic value `cr-a`; expected `auto`, `drop`, or `keep`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.tag_cardinality",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.tag_cardinality`: unknown tag cardinality `cr-a`; expected low, orch, orchestrator, high, or none",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-env",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.receiver.protocols.grpc.transport",
            adp: Adp::error(
                "error translating config key `otlp_config.receiver.protocols.grpc.transport`: unknown gRPC transport `cr-a`; expected `tcp` or `unix`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "proxy.no_proxy",
            adp: Adp::value("[\"cr-a\", \"cr-b\"]"),
            cause: AGENT_LOAD_WRITE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_log_file_max_size",
            adp: Adp::error(
                "error translating config key `dogstatsd_log_file_max_size`, couldn't parse \"cr-a\" into a ByteSize, cannot parse float from empty string",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error(
                "error translating config key `dogstatsd_mapper_profiles`: invalid type: string \"cr-a\", expected struct RawProfile",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_tag_cardinality",
            adp: Adp::error(
                "error translating config key `dogstatsd_tag_cardinality`: unknown tag cardinality `cr-a`; expected low, orch, orchestrator, high, or none",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "log_file_max_size",
            adp: Adp::error(
                "error translating config key `log_file_max_size`, couldn't parse \"cr-a\" into a ByteSize, cannot parse float from empty string",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "metric_tag_filterlist",
            adp: Adp::error(
                "error translating config key `metric_tag_filterlist`: invalid type: string \"cr-a\", expected struct RawEntry\nerror translating config key `metric_tag_filterlist`: invalid type: string \"cr-b\", expected struct RawEntry",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.histograms.mode",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.histograms.mode`: unknown histogram mode `cr-a`; expected `nobuckets`, `counters`, or `distributions`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.summaries.mode",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.summaries.mode`: unknown summary mode `cr-a`; expected `gauges` or `noquantiles`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.sums.cumulative_monotonic_mode",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.sums.cumulative_monotonic_mode`: unknown cumulative monotonic sum mode `cr-a`; expected `to_delta` or `raw_value`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.sums.initial_cumulative_monotonic_value",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.sums.initial_cumulative_monotonic_value`: unknown initial cumulative monotonic value `cr-a`; expected `auto`, `drop`, or `keep`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.tag_cardinality",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.tag_cardinality`: unknown tag cardinality `cr-a`; expected low, orch, orchestrator, high, or none",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.receiver.protocols.grpc.transport",
            adp: Adp::error(
                "error translating config key `otlp_config.receiver.protocols.grpc.transport`: unknown gRPC transport `cr-a`; expected `tcp` or `unix`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update dogstatsd_log_file_max_size #1",
            getter: "-",
            key: "dogstatsd_log_file_max_size",
            adp: Adp::error(
                "error translating config key `dogstatsd_log_file_max_size`, couldn't parse \"cr-b\" into a ByteSize, cannot parse float from empty string",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update dogstatsd_mapper_profiles #1",
            getter: "-",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error(
                "error translating config key `dogstatsd_mapper_profiles`: invalid type: string \"cr-c\", expected struct RawProfile",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update dogstatsd_tag_cardinality #1",
            getter: "-",
            key: "dogstatsd_tag_cardinality",
            adp: Adp::error(
                "error translating config key `dogstatsd_tag_cardinality`: unknown tag cardinality `cr-b`; expected low, orch, orchestrator, high, or none",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update log_file_max_size #1",
            getter: "-",
            key: "log_file_max_size",
            adp: Adp::error(
                "error translating config key `log_file_max_size`, couldn't parse \"cr-b\" into a ByteSize, cannot parse float from empty string",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update metric_tag_filterlist #1",
            getter: "-",
            key: "metric_tag_filterlist",
            adp: Adp::error(
                "error translating config key `metric_tag_filterlist`: invalid type: string \"cr-c\", expected struct RawEntry",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update otlp_config.metrics.histograms.mode #1",
            getter: "-",
            key: "otlp_config.metrics.histograms.mode",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.histograms.mode`: unknown histogram mode `cr-b`; expected `nobuckets`, `counters`, or `distributions`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update otlp_config.metrics.summaries.mode #1",
            getter: "-",
            key: "otlp_config.metrics.summaries.mode",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.summaries.mode`: unknown summary mode `cr-b`; expected `gauges` or `noquantiles`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update otlp_config.metrics.sums.cumulative_monotonic_mode #1",
            getter: "-",
            key: "otlp_config.metrics.sums.cumulative_monotonic_mode",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.sums.cumulative_monotonic_mode`: unknown cumulative monotonic sum mode `cr-b`; expected `to_delta` or `raw_value`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update otlp_config.metrics.sums.initial_cumulative_monotonic_value #1",
            getter: "-",
            key: "otlp_config.metrics.sums.initial_cumulative_monotonic_value",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.sums.initial_cumulative_monotonic_value`: unknown initial cumulative monotonic value `cr-b`; expected `auto`, `drop`, or `keep`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update otlp_config.metrics.tag_cardinality #1",
            getter: "-",
            key: "otlp_config.metrics.tag_cardinality",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.tag_cardinality`: unknown tag cardinality `cr-b`; expected low, orch, orchestrator, high, or none",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        intentional(Entry {
            origin: "breadth-yaml",
            tier: Translate,
            at: "update otlp_config.receiver.protocols.grpc.transport #1",
            getter: "-",
            key: "otlp_config.receiver.protocols.grpc.transport",
            adp: Adp::error(
                "error translating config key `otlp_config.receiver.protocols.grpc.transport`: unknown gRPC transport `cr-b`; expected `tcp` or `unix`",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        known_bug(Entry {
            origin: "cli-stop-timeout-not-recomputed",
            tier: Derived,
            at: "snapshot",
            getter: "GetInt",
            key: "data_plane.stop_timeout",
            adp: Adp::value("8"),
            cause: STOP_TIMEOUT_RECOMPUTED,
        }),
        intentional(Entry {
            origin: "core-agent-disabled-payloads",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetBool",
            key: "enable_payloads.events",
            adp: Adp::value("true"),
            cause: AGENT_LOAD_WRITE,
        }),
        intentional(Entry {
            origin: "core-agent-disabled-payloads",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetBool",
            key: "enable_payloads.series",
            adp: Adp::value("true"),
            cause: AGENT_LOAD_WRITE,
        }),
        intentional(Entry {
            origin: "core-agent-disabled-payloads",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetBool",
            key: "enable_payloads.service_checks",
            adp: Adp::value("true"),
            cause: AGENT_LOAD_WRITE,
        }),
        intentional(Entry {
            origin: "core-agent-disabled-payloads",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetBool",
            key: "enable_payloads.sketches",
            adp: Adp::value("true"),
            cause: AGENT_LOAD_WRITE,
        }),
        known_bug(Entry {
            origin: "depth-env-bool-words",
            tier: Leaf,
            at: "snapshot",
            getter: "GetBool",
            key: "allow_arbitrary_tags",
            adp: Adp::error("invalid value: string \"on\", expected a boolean, a boolean string, or a number"),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-bool-words",
            tier: Bootstrap,
            at: "snapshot",
            getter: "-",
            key: "<boot>",
            adp: Adp::error(
                "failed to build the configuration base: environment variable `DD_ALLOW_ARBITRARY_TAGS` (allow_arbitrary_tags): invalid boolean `on`",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-bool-words",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "allow_arbitrary_tags",
            adp: Adp::error(
                "invalid value: string \"on\", expected a boolean, a boolean string, or a number",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-float",
            tier: Leaf,
            at: "snapshot",
            getter: "GetInt",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error(
                "invalid value: string \"1.342177295e+08\", expected an integer, a numeric string, or a boolean",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-float",
            tier: Leaf,
            at: "snapshot",
            getter: "GetInt64",
            key: "cri_connection_timeout",
            adp: Adp::error("invalid value: string \"2.5\", expected an integer, a numeric string, or a boolean"),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-float",
            tier: Bootstrap,
            at: "snapshot",
            getter: "-",
            key: "<boot>",
            adp: Adp::error(
                "failed to build the configuration base: environment variable `DD_AGENT_IPC_GRPC_MAX_MESSAGE_SIZE` (agent_ipc.grpc_max_message_size): invalid integer `1.342177295e+08`",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-float",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error(
                "invalid value: string \"1.342177295e+08\", expected an integer, a numeric string, or a boolean",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-float",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "cri_connection_timeout",
            adp: Adp::error(
                "invalid value: string \"2.5\", expected an integer, a numeric string, or a boolean",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-hex",
            tier: Bootstrap,
            at: "snapshot",
            getter: "-",
            key: "<boot>",
            adp: Adp::error(
                "failed to build the configuration base: environment variable `DD_AGENT_IPC_GRPC_MAX_MESSAGE_SIZE` (agent_ipc.grpc_max_message_size): invalid integer `0x10`",
            ),
            cause: BOOTSTRAP_ENV_PARSING,
        }),
        known_bug(Entry {
            origin: "depth-env-json-list",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "apm_config.replace_tags",
            adp: Adp::error("data did not match any variant of untagged enum JsonArrayOrString"),
            cause: NULL_COLLECTION,
        }),
        intentional(Entry {
            origin: "depth-env-json-list",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "metric_tag_filterlist",
            adp: Adp::value("[\"cr-a\",\"cr-b\"]"),
            cause: RAW_JSON_REPRESENTATION,
        }),
        known_bug(Entry {
            origin: "depth-env-json-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "Get",
            key: "apm_config.replace_tags",
            adp: Adp::error("data did not match any variant of untagged enum JsonArrayOrString"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        intentional(Entry {
            origin: "depth-env-json-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "Get",
            key: "metric_tag_filterlist",
            adp: Adp::value("[\"cr-a\",\"cr-b\"]"),
            cause: RAW_JSON_REPRESENTATION,
        }),
        known_bug(Entry {
            origin: "depth-env-json-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "apm_config.obfuscation.elasticsearch.keep_values",
            adp: Adp::value("[\"[\\\"cr-a\\\",\\\"cr-b\\\"]\"]"),
            cause: BOOTSTRAP_ENV_PARSING,
        }),
        known_bug(Entry {
            origin: "depth-env-json-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.replace_tags",
            adp: Adp::error(
                "data did not match any variant of untagged enum JsonArrayOrString",
            ),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-env-mixed-string",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "apm_config.replace_tags",
            adp: Adp::error("data did not match any variant of untagged enum JsonArrayOrString"),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-env-mixed-string",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "metric_tag_filterlist",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-mixed-string",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "apm_config.peer_tags",
            adp: Adp::error("invalid type: null, expected a sequence or a space-separated string"),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-env-mixed-string",
            tier: Bootstrap,
            at: "snapshot",
            getter: "-",
            key: "<boot>",
            adp: Adp::error(
                "failed to build the configuration base: environment variable `DD_APM_PEER_TAGS` (apm_config.peer_tags): invalid JSON: expected value at line 1 column 1",
            ),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-mixed-string",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.peer_tags",
            adp: Adp::error(
                "invalid type: null, expected a sequence or a space-separated string",
            ),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-env-mixed-string",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.replace_tags",
            adp: Adp::error(
                "data did not match any variant of untagged enum JsonArrayOrString",
            ),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-env-mixed-string",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "metric_tag_filterlist",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-not-json",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapString",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error("invalid JSON-encoded map: expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-not-json",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid JSON-encoded map: expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-not-json",
            tier: Bootstrap,
            at: "snapshot",
            getter: "-",
            key: "<boot>",
            adp: Adp::error(
                "failed to build the configuration base: environment variable `DD_ADDITIONAL_ENDPOINTS` (additional_endpoints): invalid JSON: expected value at line 1 column 1",
            ),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-not-json",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "additional_endpoints",
            adp: Adp::error(
                "invalid JSON-encoded map: expected value at line 1 column 1",
            ),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-env-not-json",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error(
                "invalid JSON-encoded map: expected value at line 1 column 1",
            ),
            cause: MALFORMED_JSON_STRING,
        }),
        intentional(Entry {
            origin: "depth-env-secondary-name",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "otlp_config.metrics.tag_cardinality",
            adp: Adp::error(
                "error translating config key `otlp_config.metrics.tag_cardinality`: unknown tag cardinality `cr-a`; expected low, orch, orchestrator, high, or none",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        known_bug(Entry {
            origin: "depth-set-bool-words",
            tier: Leaf,
            at: "final",
            getter: "GetBool",
            key: "allow_arbitrary_tags",
            adp: Adp::error("invalid value: string \"on\", expected a boolean, a boolean string, or a number"),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-bool-words",
            tier: Deserialize,
            at: "update allow_arbitrary_tags #1",
            getter: "-",
            key: "allow_arbitrary_tags",
            adp: Adp::error(
                "invalid value: string \"on\", expected a boolean, a boolean string, or a number",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-list",
            tier: Leaf,
            at: "final",
            getter: "GetStringMapString",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-list",
            tier: Leaf,
            at: "final",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-list",
            tier: Leaf,
            at: "final",
            getter: "GetStringSlice",
            key: "apm_config.features",
            adp: Adp::error("invalid type: null, expected a sequence or a space-separated string"),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-list",
            tier: Deserialize,
            at: "update additional_endpoints #1",
            getter: "-",
            key: "additional_endpoints",
            adp: Adp::error(
                "invalid type: sequence, expected a map or a JSON-encoded map string",
            ),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-list",
            tier: Deserialize,
            at: "update apm_config.features #1",
            getter: "-",
            key: "apm_config.features",
            adp: Adp::error(
                "invalid type: null, expected a sequence or a space-separated string",
            ),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-list",
            tier: Deserialize,
            at: "update use_v3_api.series.endpoints #1",
            getter: "-",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error(
                "invalid type: sequence, expected a map or a JSON-encoded map string",
            ),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-string",
            tier: Leaf,
            at: "final",
            getter: "GetBool",
            key: "allow_arbitrary_tags",
            adp: Adp::error("invalid value: string \"\", expected a boolean, a boolean string, or a number"),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-string",
            tier: Leaf,
            at: "final",
            getter: "GetFloat64",
            key: "apm_config.errors_per_second",
            adp: Adp::error("invalid value: string \"\", expected a number, a numeric string, or a boolean"),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-string",
            tier: Leaf,
            at: "final",
            getter: "GetInt",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error("invalid value: string \"\", expected an integer, a numeric string, or a boolean"),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-string",
            tier: Deserialize,
            at: "update agent_ipc.grpc_max_message_size #1",
            getter: "-",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error(
                "invalid value: string \"\", expected an integer, a numeric string, or a boolean",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-string",
            tier: Deserialize,
            at: "update allow_arbitrary_tags #1",
            getter: "-",
            key: "allow_arbitrary_tags",
            adp: Adp::error(
                "invalid value: string \"\", expected a boolean, a boolean string, or a number",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-empty-string",
            tier: Deserialize,
            at: "update apm_config.errors_per_second #1",
            getter: "-",
            key: "apm_config.errors_per_second",
            adp: Adp::error(
                "invalid value: string \"\", expected a number, a numeric string, or a boolean",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-mixed-string",
            tier: Leaf,
            at: "final",
            getter: "Get",
            key: "apm_config.replace_tags",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-mixed-string",
            tier: Leaf,
            at: "final",
            getter: "Get",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-mixed-string",
            tier: Deserialize,
            at: "update apm_config.replace_tags #1",
            getter: "-",
            key: "apm_config.replace_tags",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-set-mixed-string",
            tier: Deserialize,
            at: "update dogstatsd_mapper_profiles #1",
            getter: "-",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetBool",
            key: "allow_arbitrary_tags",
            adp: Adp::error("invalid type: sequence, expected a boolean, a boolean string, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetDuration",
            key: "expected_tags_duration",
            adp: Adp::error(
                "invalid type: sequence, expected a duration as integer nanoseconds, a Go duration string (for example \"10s\"), or a bare number of nanoseconds as a string",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetFloat64",
            key: "apm_config.errors_per_second",
            adp: Adp::error("invalid type: sequence, expected a number, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetInt",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error("invalid type: sequence, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetInt64",
            key: "cri_connection_timeout",
            adp: Adp::error("invalid type: sequence, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetString",
            key: "api_key",
            adp: Adp::error("invalid type: sequence, expected a string, a boolean, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapString",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "apm_config.features",
            adp: Adp::error("invalid type: null, expected a sequence or a space-separated string"),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetBool",
            key: "allow_arbitrary_tags",
            adp: Adp::error("invalid type: sequence, expected a boolean, a boolean string, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetDuration",
            key: "expected_tags_duration",
            adp: Adp::error(
                "invalid type: sequence, expected a duration as integer nanoseconds, a Go duration string (for example \"10s\"), or a bare number of nanoseconds as a string",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetFloat64",
            key: "apm_config.errors_per_second",
            adp: Adp::error("invalid type: sequence, expected a number, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetInt",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error("invalid type: sequence, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetInt64",
            key: "cri_connection_timeout",
            adp: Adp::error("invalid type: sequence, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "api_key",
            adp: Adp::error("invalid type: sequence, expected a string, a boolean, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringMapString",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "additional_endpoints",
            adp: Adp::error(
                "invalid type: sequence, expected a map or a JSON-encoded map string",
            ),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error(
                "invalid type: sequence, expected an integer, a numeric string, or a boolean",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "allow_arbitrary_tags",
            adp: Adp::error(
                "invalid type: sequence, expected a boolean, a boolean string, or a number",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "api_key",
            adp: Adp::error(
                "invalid type: sequence, expected a string, a boolean, or a number",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.errors_per_second",
            adp: Adp::error(
                "invalid type: sequence, expected a number, a numeric string, or a boolean",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.features",
            adp: Adp::error(
                "invalid type: null, expected a sequence or a space-separated string",
            ),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "cri_connection_timeout",
            adp: Adp::error(
                "invalid type: sequence, expected an integer, a numeric string, or a boolean",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "expected_tags_duration",
            adp: Adp::error(
                "invalid type: sequence, expected a duration as integer nanoseconds, a Go duration string (for example \"10s\"), or a bare number of nanoseconds as a string",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error(
                "invalid type: sequence, expected a map or a JSON-encoded map string",
            ),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "apm_config.replace_tags",
            adp: Adp::error("data did not match any variant of untagged enum JsonArrayOrString"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error("data did not match any variant of untagged enum JsonArrayOrString"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Leaf,
            at: "snapshot",
            getter: "GetBool",
            key: "allow_arbitrary_tags",
            adp: Adp::error("invalid type: map, expected a boolean, a boolean string, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Leaf,
            at: "snapshot",
            getter: "GetDuration",
            key: "expected_tags_duration",
            adp: Adp::error(
                "invalid type: map, expected a duration as integer nanoseconds, a Go duration string (for example \"10s\"), or a bare number of nanoseconds as a string",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Leaf,
            at: "snapshot",
            getter: "GetFloat64",
            key: "apm_config.errors_per_second",
            adp: Adp::error("invalid type: map, expected a number, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Leaf,
            at: "snapshot",
            getter: "GetInt",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error("invalid type: map, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Leaf,
            at: "snapshot",
            getter: "GetInt64",
            key: "cri_connection_timeout",
            adp: Adp::error("invalid type: map, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Leaf,
            at: "snapshot",
            getter: "GetString",
            key: "api_key",
            adp: Adp::error("invalid type: map, expected a string, a boolean, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "apm_config.features",
            adp: Adp::error("invalid type: map, expected a sequence or a space-separated string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Bootstrap,
            at: "snapshot",
            getter: "Get",
            key: "apm_config.replace_tags",
            adp: Adp::error("data did not match any variant of untagged enum JsonArrayOrString"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Bootstrap,
            at: "snapshot",
            getter: "Get",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error("data did not match any variant of untagged enum JsonArrayOrString"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetBool",
            key: "allow_arbitrary_tags",
            adp: Adp::error("invalid type: map, expected a boolean, a boolean string, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetDuration",
            key: "expected_tags_duration",
            adp: Adp::error(
                "invalid type: map, expected a duration as integer nanoseconds, a Go duration string (for example \"10s\"), or a bare number of nanoseconds as a string",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetFloat64",
            key: "apm_config.errors_per_second",
            adp: Adp::error("invalid type: map, expected a number, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetInt",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error("invalid type: map, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetInt64",
            key: "cri_connection_timeout",
            adp: Adp::error("invalid type: map, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "api_key",
            adp: Adp::error("invalid type: map, expected a string, a boolean, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "apm_config.features",
            adp: Adp::error("invalid type: map, expected a sequence or a space-separated string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error(
                "invalid type: map, expected an integer, a numeric string, or a boolean",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "allow_arbitrary_tags",
            adp: Adp::error(
                "invalid type: map, expected a boolean, a boolean string, or a number",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "api_key",
            adp: Adp::error(
                "invalid type: map, expected a string, a boolean, or a number",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.errors_per_second",
            adp: Adp::error(
                "invalid type: map, expected a number, a numeric string, or a boolean",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.features",
            adp: Adp::error(
                "invalid type: map, expected a sequence or a space-separated string",
            ),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.replace_tags",
            adp: Adp::error(
                "data did not match any variant of untagged enum JsonArrayOrString",
            ),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "cri_connection_timeout",
            adp: Adp::error(
                "invalid type: map, expected an integer, a numeric string, or a boolean",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error(
                "data did not match any variant of untagged enum JsonArrayOrString",
            ),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-empty-map",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "expected_tags_duration",
            adp: Adp::error(
                "invalid type: map, expected a duration as integer nanoseconds, a Go duration string (for example \"10s\"), or a bare number of nanoseconds as a string",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-map-int-values",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("data did not match any variant of untagged enum ScalarOrSeq"),
            cause: NON_STRING_MAP_VALUE,
        }),
        known_bug(Entry {
            origin: "depth-yaml-map-int-values",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("data did not match any variant of untagged enum ScalarOrSeq"),
            cause: NON_STRING_MAP_VALUE,
        }),
        known_bug(Entry {
            origin: "depth-yaml-map-int-values",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "additional_endpoints",
            adp: Adp::error(
                "data did not match any variant of untagged enum ScalarOrSeq",
            ),
            cause: NON_STRING_MAP_VALUE,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "apm_config.replace_tags",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapString",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error("invalid JSON-encoded map: expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid JSON-encoded map: expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Bootstrap,
            at: "snapshot",
            getter: "Get",
            key: "apm_config.replace_tags",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Bootstrap,
            at: "snapshot",
            getter: "Get",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringMapString",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error("invalid JSON-encoded map: expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid JSON-encoded map: expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "additional_endpoints",
            adp: Adp::error(
                "invalid JSON-encoded map: expected value at line 1 column 1",
            ),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.replace_tags",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error("expected value at line 1 column 1"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-mixed-string",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error(
                "invalid JSON-encoded map: expected value at line 1 column 1",
            ),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetBool",
            key: "allow_arbitrary_tags",
            adp: Adp::error("invalid type: sequence, expected a boolean, a boolean string, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetDuration",
            key: "expected_tags_duration",
            adp: Adp::error(
                "invalid type: sequence, expected a duration as integer nanoseconds, a Go duration string (for example \"10s\"), or a bare number of nanoseconds as a string",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetFloat64",
            key: "apm_config.errors_per_second",
            adp: Adp::error("invalid type: sequence, expected a number, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetInt",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error("invalid type: sequence, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetInt64",
            key: "cri_connection_timeout",
            adp: Adp::error("invalid type: sequence, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetString",
            key: "api_key",
            adp: Adp::error("invalid type: sequence, expected a string, a boolean, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapString",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetBool",
            key: "allow_arbitrary_tags",
            adp: Adp::error("invalid type: sequence, expected a boolean, a boolean string, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetDuration",
            key: "expected_tags_duration",
            adp: Adp::error(
                "invalid type: sequence, expected a duration as integer nanoseconds, a Go duration string (for example \"10s\"), or a bare number of nanoseconds as a string",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetFloat64",
            key: "apm_config.errors_per_second",
            adp: Adp::error("invalid type: sequence, expected a number, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetInt",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error("invalid type: sequence, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetInt64",
            key: "cri_connection_timeout",
            adp: Adp::error("invalid type: sequence, expected an integer, a numeric string, or a boolean"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "api_key",
            adp: Adp::error("invalid type: sequence, expected a string, a boolean, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringMapString",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid type: sequence, expected a map or a JSON-encoded map string"),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "additional_endpoints",
            adp: Adp::error(
                "invalid type: sequence, expected a map or a JSON-encoded map string",
            ),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "agent_ipc.grpc_max_message_size",
            adp: Adp::error(
                "invalid type: sequence, expected an integer, a numeric string, or a boolean",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "allow_arbitrary_tags",
            adp: Adp::error(
                "invalid type: sequence, expected a boolean, a boolean string, or a number",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "api_key",
            adp: Adp::error(
                "invalid type: sequence, expected a string, a boolean, or a number",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "apm_config.errors_per_second",
            adp: Adp::error(
                "invalid type: sequence, expected a number, a numeric string, or a boolean",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "cri_connection_timeout",
            adp: Adp::error(
                "invalid type: sequence, expected an integer, a numeric string, or a boolean",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "expected_tags_duration",
            adp: Adp::error(
                "invalid type: sequence, expected a duration as integer nanoseconds, a Go duration string (for example \"10s\"), or a bare number of nanoseconds as a string",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "depth-yaml-one-item-list",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "use_v3_api.series.endpoints",
            adp: Adp::error(
                "invalid type: sequence, expected a map or a JSON-encoded map string",
            ),
            cause: COLLECTION_SHAPE_MISMATCH,
        }),
        known_bug(Entry {
            origin: "derived-stop-timeout-default-source",
            tier: Derived,
            at: "final",
            getter: "GetInt",
            key: "data_plane.stop_timeout",
            adp: Adp::value("16"),
            cause: STOP_TIMEOUT_RECOMPUTED,
        }),
        intentional(Entry {
            origin: "derived-stop-timeout-default-source",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetInt",
            key: "data_plane.stop_timeout",
            adp: Adp::value("4"),
            cause: AGENT_LOAD_WRITE,
        }),
        known_bug(Entry {
            origin: "docker-dd-agent-env-only",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "container_cgroup_root",
            adp: Adp::value("\"/host/sys/fs/cgroup/\""),
            cause: UNRESOLVED_AGENT_DEFAULT,
        }),
        known_bug(Entry {
            origin: "docker-dd-agent-env-only",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "container_proc_root",
            adp: Adp::value("\"/host/proc\""),
            cause: UNRESOLVED_AGENT_DEFAULT,
        }),
        known_bug(Entry {
            origin: "empty-list-yaml-and-env",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "histogram_aggregates",
            adp: Adp::error("invalid type: null, expected a sequence or a space-separated string"),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "empty-list-yaml-and-env",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "histogram_aggregates",
            adp: Adp::error(
                "invalid type: null, expected a sequence or a space-separated string",
            ),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "env-bool-unparseable-kept-raw",
            tier: Leaf,
            at: "snapshot",
            getter: "GetBool",
            key: "dogstatsd_origin_detection",
            adp: Adp::error("invalid value: string \"yes\", expected a boolean, a boolean string, or a number"),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "env-bool-unparseable-kept-raw",
            tier: Bootstrap,
            at: "snapshot",
            getter: "-",
            key: "<boot>",
            adp: Adp::error(
                "failed to build the configuration base: environment variable `DD_DOGSTATSD_ORIGIN_DETECTION` (dogstatsd_origin_detection): invalid boolean `yes`",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        known_bug(Entry {
            origin: "env-bool-unparseable-kept-raw",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_origin_detection",
            adp: Adp::error(
                "invalid value: string \"yes\", expected a boolean, a boolean string, or a number",
            ),
            cause: UNPARSEABLE_SCALAR_STRING,
        }),
        intentional(Entry {
            origin: "env-list-of-maps-raw-string",
            tier: Leaf,
            at: "snapshot",
            getter: "Get",
            key: "metric_tag_filterlist",
            adp: Adp::value("[{\"metric_name\":\"m\",\"tags\":[\"t\"]}]"),
            cause: RAW_JSON_REPRESENTATION,
        }),
        intentional(Entry {
            origin: "env-list-of-maps-raw-string",
            tier: Bootstrap,
            at: "snapshot",
            getter: "Get",
            key: "metric_tag_filterlist",
            adp: Adp::value("[{\"metric_name\":\"m\",\"tags\":[\"t\"]}]"),
            cause: RAW_JSON_REPRESENTATION,
        }),
        known_bug(Entry {
            origin: "env-map-bad-json",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid JSON-encoded map: key must be a string at line 1 column 2"),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "env-map-bad-json",
            tier: Bootstrap,
            at: "snapshot",
            getter: "-",
            key: "<boot>",
            adp: Adp::error(
                "failed to build the configuration base: environment variable `DD_ADDITIONAL_ENDPOINTS` (additional_endpoints): invalid JSON: key must be a string at line 1 column 2",
            ),
            cause: MALFORMED_JSON_STRING,
        }),
        known_bug(Entry {
            origin: "env-map-bad-json",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "additional_endpoints",
            adp: Adp::error(
                "invalid JSON-encoded map: key must be a string at line 1 column 2",
            ),
            cause: MALFORMED_JSON_STRING,
        }),
        intentional(Entry {
            origin: "fips-proxy-endpoints",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetBool",
            key: "skip_ssl_validation",
            adp: Adp::value("false"),
            cause: AGENT_LOAD_WRITE,
        }),
        intentional(Entry {
            origin: "fips-proxy-endpoints",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "dd_url",
            adp: Adp::value("\"https://app.datadoghq.com\""),
            cause: AGENT_LOAD_WRITE,
        }),
        known_bug(Entry {
            origin: "int-string-base-prefix",
            tier: Derived,
            at: "snapshot",
            getter: "GetSizeInBytes",
            key: "log_file_max_size",
            adp: Adp::error(
                "1 config translation error(s):\n  - error translating config key `log_file_max_size`, couldn't parse \"x10KB\" into a known SI unit, Failed to parse unit \"x10...\"",
            ),
            cause: BYTE_SIZE_PARSE,
        }),
        known_bug(Entry {
            origin: "int-string-base-prefix",
            tier: Bootstrap,
            at: "snapshot",
            getter: "-",
            key: "<boot>",
            adp: Adp::error(
                "failed to build the configuration base: environment variable `DD_DOGSTATSD_PORT` (dogstatsd_port): invalid integer `0x10`",
            ),
            cause: BOOTSTRAP_ENV_PARSING,
        }),
        known_bug(Entry {
            origin: "int-string-base-prefix",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "log_file_max_size",
            adp: Adp::error(
                "error translating config key `log_file_max_size`, couldn't parse \"x10KB\" into a known SI unit, Failed to parse unit \"x10...\"",
            ),
            cause: BYTE_SIZE_PARSE,
        }),
        known_bug(Entry {
            origin: "mapper-profiles-wrong-field-type",
            tier: Translate,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_mapper_profiles",
            adp: Adp::error(
                "error translating config key `dogstatsd_mapper_profiles`: invalid type: integer `123`, expected a string",
            ),
            cause: STRUCT_DECODE,
        }),
        intentional(Entry {
            origin: "proxy-env-bare-lowercase",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "proxy.no_proxy",
            adp: Adp::value("[]"),
            cause: AGENT_LOAD_WRITE,
        }),
        intentional(Entry {
            origin: "proxy-env-empty-dd-var-overrides",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "proxy.http",
            adp: Adp::value("\"http://bare.test:3128\""),
            cause: AGENT_LOAD_WRITE,
        }),
        intentional(Entry {
            origin: "proxy-env-empty-dd-var-overrides",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "proxy.no_proxy",
            adp: Adp::value("[\"a.test\", \"b.test,c.test\"]"),
            cause: AGENT_LOAD_WRITE,
        }),
        intentional(Entry {
            origin: "proxy-runtime-cloud-metadata-not-recomputed",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "proxy.no_proxy",
            adp: Adp::value("[]"),
            cause: AGENT_LOAD_WRITE,
        }),
        known_bug(Entry {
            origin: "proxy-yaml-source-post-init",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringSlice",
            key: "proxy.no_proxy",
            adp: Adp::error("invalid type: null, expected a sequence or a space-separated string"),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "proxy-yaml-source-post-init",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "proxy.no_proxy",
            adp: Adp::error(
                "invalid type: null, expected a sequence or a space-separated string",
            ),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "set-nil-map-key",
            tier: Leaf,
            at: "final",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::error("invalid type: null, expected a map or a JSON-encoded map string"),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "set-nil-map-key",
            tier: Deserialize,
            at: "update additional_endpoints #1",
            getter: "-",
            key: "additional_endpoints",
            adp: Adp::error(
                "invalid type: null, expected a map or a JSON-encoded map string",
            ),
            cause: NULL_COLLECTION,
        }),
        known_bug(Entry {
            origin: "size-in-bytes-kb",
            tier: Derived,
            at: "snapshot",
            getter: "GetSizeInBytes",
            key: "dogstatsd_log_file_max_size",
            adp: Adp::value("5000"),
            cause: SIZE_UNIT_BASE,
        }),
        known_bug(Entry {
            origin: "size-in-bytes-kb",
            tier: Derived,
            at: "snapshot",
            getter: "GetSizeInBytes",
            key: "log_file_max_size",
            adp: Adp::value("10000000"),
            cause: SIZE_UNIT_BASE,
        }),
        known_bug(Entry {
            origin: "size-in-bytes-units",
            tier: Derived,
            at: "snapshot",
            getter: "GetSizeInBytes",
            key: "dogstatsd_log_file_max_size",
            adp: Adp::value("10000000"),
            cause: SIZE_UNIT_BASE,
        }),
        known_bug(Entry {
            origin: "size-in-bytes-units",
            tier: Derived,
            at: "snapshot",
            getter: "GetSizeInBytes",
            key: "log_file_max_size",
            adp: Adp::value("10000000"),
            cause: SIZE_UNIT_BASE,
        }),
        intentional(Entry {
            origin: "valid-stream-updates",
            tier: Translate,
            at: "update dogstatsd_tag_cardinality #2",
            getter: "-",
            key: "dogstatsd_tag_cardinality",
            adp: Adp::error(
                "error translating config key `dogstatsd_tag_cardinality`: unknown tag cardinality `bogus`; expected low, orch, orchestrator, high, or none",
            ),
            cause: TRANSLATOR_REJECTS_VALUE,
        }),
        known_bug(Entry {
            origin: "yaml-bool-word-string-key",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "env",
            adp: Adp::value("\"yes\""),
            cause: BOOTSTRAP_YAML_LOADING,
        }),
        known_bug(Entry {
            origin: "yaml-dotted-keys",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "data_plane.api_listen_address",
            adp: Adp::value("\"tcp://0.0.0.0:5100\""),
            cause: BOOTSTRAP_YAML_LOADING,
        }),
        intentional(Entry {
            origin: "yaml-float-nan",
            tier: Leaf,
            at: "snapshot",
            getter: "GetFloat64",
            key: "forwarder_backoff_factor",
            adp: Adp::value("2.0"),
            cause: WIRE_NUMBER_LOSS,
        }),
        known_bug(Entry {
            origin: "yaml-float-nan",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetFloat64",
            key: "forwarder_backoff_factor",
            adp: Adp::value("2.0"),
            cause: BOOTSTRAP_YAML_LOADING,
        }),
        intentional(Entry {
            origin: "yaml-int-above-2-53",
            tier: Leaf,
            at: "snapshot",
            getter: "GetInt64",
            key: "cri_connection_timeout",
            adp: Adp::value("9007199254740992"),
            cause: WIRE_NUMBER_LOSS,
        }),
        intentional(Entry {
            origin: "yaml-int-above-2-53",
            tier: Leaf,
            at: "snapshot",
            getter: "GetStringMapString",
            key: "use_v3_api.series.endpoints",
            adp: Adp::value("{\"cr_a\": \"9007199254740992\"}"),
            cause: WIRE_NUMBER_LOSS,
        }),
        known_bug(Entry {
            origin: "yaml-map-for-string-key",
            tier: Leaf,
            at: "snapshot",
            getter: "GetString",
            key: "dogstatsd_socket",
            adp: Adp::error("invalid type: map, expected a string, a boolean, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "yaml-map-for-string-key",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "dogstatsd_socket",
            adp: Adp::error("invalid type: map, expected a string, a boolean, or a number"),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "yaml-map-for-string-key",
            tier: Deserialize,
            at: "snapshot",
            getter: "-",
            key: "dogstatsd_socket",
            adp: Adp::error(
                "invalid type: map, expected a string, a boolean, or a number",
            ),
            cause: SCALAR_GIVEN_COLLECTION,
        }),
        known_bug(Entry {
            origin: "yaml-noncanonical-map-keys",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetStringMapStringSlice",
            key: "additional_endpoints",
            adp: Adp::value("{\"010\": [\"j\"], \"true\": [\"k\"]}"),
            cause: BOOTSTRAP_YAML_LOADING,
        }),
        known_bug(Entry {
            origin: "yaml-plain-octal",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetInt",
            key: "dogstatsd_buffer_size",
            adp: Adp::value("10"),
            cause: BOOTSTRAP_YAML_LOADING,
        }),
        known_bug(Entry {
            origin: "yaml-plain-octal",
            tier: Bootstrap,
            at: "snapshot",
            getter: "GetString",
            key: "env",
            adp: Adp::value("\"0755\""),
            cause: BOOTSTRAP_YAML_LOADING,
        }),
    ]
}
const AGENT_LOAD_WRITE: Cause = Cause {
    name: "agent-load-write",
    why: "the Agent writes the value while loading (proxy from env, FIPS endpoints, payload switches, api_key trim, stop timeout); only the stream carries it",
    issue: None,
};

const BOOTSTRAP_ENV_PARSING: Cause = Cause {
    name: "bootstrap-env-parsing",
    why: "ADP's own DD_* reader rejects base-prefixed integers and does not match the Agent's per-key list separators",
    issue: Some(2753),
};

const BOOTSTRAP_YAML_LOADING: Cause = Cause {
    name: "bootstrap-yaml-loading",
    why: "ADP's own datadog.yaml reader has no YAML 1.1 resolution (octal, yes/no), no dotted-key split, and loses NaN",
    issue: Some(2754),
};

const COLLECTION_SHAPE_MISMATCH: Cause = Cause {
    name: "collection-shape-mismatch",
    why: "a collection key given the wrong collection (a list for a map, strings for a list of maps); the Agent casts, ADP rejects",
    issue: Some(2756),
};

const RAW_JSON_REPRESENTATION: Cause = Cause {
    name: "raw-json-representation",
    why: "the environment variable holds JSON text: ADP's reader decodes it into the structured value, \
while the Agent's raw `Get` returns the string verbatim; `Get` is not how an Agent consumer reads \
this key, so the difference is one of representation, not behavior",
    issue: None,
};

const MALFORMED_JSON_STRING: Cause = Cause {
    name: "malformed-json-string",
    why: "a non-JSON string for a map or JSON-list key; the Agent's getter returns empty with a warning, ADP rejects",
    issue: Some(2756),
};

const NON_STRING_MAP_VALUE: Cause = Cause {
    name: "non-string-map-value",
    why: "a non-string value in a string map; the Agent's getter stringifies it, ADP rejects",
    issue: Some(2752),
};

const NULL_COLLECTION: Cause = Cause {
    name: "null-collection",
    why: "the stream carries null for an empty or unset list or map; the Agent's getter reads empty, ADP rejects",
    issue: Some(2750),
};

const SCALAR_GIVEN_COLLECTION: Cause = Cause {
    name: "scalar-given-collection",
    why: "a map or list for a scalar key; the Agent's getter casts it to the zero value, ADP rejects",
    issue: Some(2755),
};

const SIZE_UNIT_BASE: Cause = Cause {
    name: "size-unit-base",
    why: "ADP parses KB, MB and GB byte sizes as powers of 1000; the Agent's GetSizeInBytes uses powers of 1024",
    issue: Some(2751),
};

const STOP_TIMEOUT_RECOMPUTED: Cause = Cause {
    name: "stop-timeout-recomputed",
    why: "the Agent computes data_plane.stop_timeout once at load; ADP recomputes it from later inputs",
    issue: Some(2757),
};

const BYTE_SIZE_PARSE: Cause = Cause {
    name: "byte-size-parse",
    why: "the translator rejects a base-prefixed size the Agent's getter accepts",
    issue: Some(2751),
};

const STRUCT_DECODE: Cause = Cause {
    name: "struct-decode",
    why:
        "the translator rejects a number for a string field; the corpus records raw Get, not the Agent's struct decode",
    issue: Some(2758),
};

const TRANSLATOR_REJECTS_VALUE: Cause = Cause {
    name: "translator-rejects-value",
    why: "the translator rejects a string that is not a valid enum or size value, and with it the whole update; the Agent's getter passes it through",
    issue: None,
};

const UNPARSEABLE_SCALAR_STRING: Cause = Cause {
    name: "unparseable-scalar-string",
    why: "a string that does not parse as the key's bool or number (on, yes, empty, 2.5); the Agent's getter reads zero, ADP rejects",
    issue: Some(2755),
};

const UNRESOLVED_AGENT_DEFAULT: Cause = Cause {
    name: "unresolved-agent-default",
    why: "ADP's defaults differ from the Agent's resolved defaults (unexpanded ${log_path} and ${run_path}, container paths, no DogStatsD socket)",
    issue: Some(1802),
};

const RUN_PATH_DEFAULT: Cause = Cause {
    name: "run-path-default",
    why: "ADP's local source model keeps the ${run_path} placeholder; the runtime fallback is tracked separately",
    issue: Some(2484),
};

const WIRE_NUMBER_LOSS: Cause = Cause {
    name: "wire-number-loss",
    why: "NaN and integers above 2^53 do not survive the protobuf stream; ADP cannot recover them",
    issue: None,
};
