//! ADP-only configuration keys that are not in the Datadog Agent schema.
//! Shared between registry_gen.rs (for config registry annotations) and doc_gen.rs (for the
//! ADP-Only documentation section).

pub struct SalukiKey {
    pub yaml_path: &'static str,
    pub description: &'static str,
    pub default: &'static str,
    /// Multi-line documentation rendered as a prose section below the ADP-Only table.
    /// If the text starts with `#`, the heading is taken from the text itself.
    pub documentation: Option<&'static str>,
    // Fields used only by registry_gen:
    pub value_type: &'static str,
    pub schema_default: Option<&'static str>,
    pub env_vars: &'static [&'static str],
    pub env_var_override: Option<&'static [&'static str]>,
    pub additional_yaml_paths: &'static [&'static str],
    pub used_by: &'static [&'static str],
    pub test_json: Option<&'static str>,
    pub pipeline_affinity: &'static str,
    pub filename: &'static str,
}

pub static SALUKI_KEYS: &[SalukiKey] = &[
    // ── data_plane.rs ────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "data_plane.otlp.receiver_grpc_endpoint_temporary",
        description: "ADP OTLP gRPC listen endpoint",
        default: "localhost:6317",
        documentation: Some(
            "Temporary development key for setting ADP's OTLP listen endpoints independently from the Agent's.",
        ),
        value_type: "ValueType::String",
        schema_default: Some("localhost:6317"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "data_plane.rs",
    },
    SalukiKey {
        yaml_path: "data_plane.otlp.receiver_http_endpoint_temporary",
        description: "ADP OTLP HTTP listen endpoint",
        default: "localhost:6318",
        documentation: Some(
            "Temporary development key for setting ADP's OTLP listen endpoints independently from the Agent's.",
        ),
        value_type: "ValueType::String",
        schema_default: Some("localhost:6318"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "data_plane.rs",
    },
    SalukiKey {
        yaml_path: "data_plane.serializer_zstd_compressor_level",
        description: "ADP zstd compression level",
        default: "3",
        documentation: Some(
            "ADP-specific zstd compression level, taking precedence over the Core Agent's \
             `serializer_zstd_compressor_level`. When this key is unset, ADP falls back to \
             `serializer_zstd_compressor_level` if you set that key explicitly, and otherwise uses its \
             own default of 3. Level 3 achieves ~6% smaller payloads (65.3 MB vs \
             69.3 MB) without a net CPU increase, since ADP is more efficient than the Agent and can \
             afford higher compression. Configure via `DD_DATA_PLANE_SERIALIZER_ZSTD_COMPRESSOR_LEVEL` \
             or in ADP-specific configuration.",
        ),
        value_type: "ValueType::Integer",
        schema_default: Some("3"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::CrossCutting",
        filename: "data_plane.rs",
    },
    SalukiKey {
        yaml_path: "data_plane.stop_timeout",
        description: "ADP graceful shutdown timeout (s)",
        default: "derived",
        documentation: Some(
            "### `data_plane.stop_timeout`

\
             ADP uses `data_plane.stop_timeout` as the topology-wide graceful shutdown timeout. \
             If this key is unset, ADP defaults to `aggregator_stop_timeout + forwarder_stop_timeout`.",
        ),
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["GET_TYPED"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::CrossCutting",
        filename: "data_plane.rs",
    },
    // ── dogstatsd.rs ─────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "dogstatsd_allow_context_heap_allocs",
        description: "Allow heap allocations for contexts",
        default: "true",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: Some("true"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_autoscale_udp_listeners",
        description: "Bind multiple UDP sockets via SO_REUSEPORT",
        default: "false",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: Some("false"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_buffer_count",
        description: "Baseline receive buffers",
        default: "128",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: Some("128"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_buffer_count_max",
        description: "Maximum receive buffer count",
        default: "32768",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: Some("32768"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_cached_contexts_limit",
        description: "Max cached metric contexts",
        default: "500000",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: Some("500000"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_cached_tagsets_limit",
        description: "Max cached tagsets",
        default: "500000",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: Some("500000"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_minimum_sample_rate",
        description: "Floor for metric sample rates",
        default: "0.000000003845",
        documentation: Some(
            "ADP enforces a minimum sample rate on incoming metrics to prevent memory exhaustion \
             from extremely low sample rates on histograms and sketches. Sending metrics with a \
             very high inverse sample rate (for example `@0.0000001`) can cause unbounded memory \
             growth in a sketch; this setting prevents that. The default is conservative enough \
             that normal clients are unaffected.",
        ),
        value_type: "ValueType::Float",
        schema_default: Some("0.000000003845"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "metric_tag_value_allowlist",
        description: "Per-metric tag value allow-list",
        default: "[]",
        documentation: Some(concat!(
            "### `metric_tag_value_allowlist`\n\n",
            "Use `metric_tag_value_allowlist` to bound metric cardinality by retaining selected values for a tag. ",
            "Configure each list item with a `metric_prefix`, a `tag_name`, and the `values` to retain. The rule ",
            "applies to every metric whose name starts with the prefix. Values not in the list lose the tag by default. To aggregate them under a sentinel instead, set ",
            "`on_miss: replace` and configure `replacement`; the replacement defaults to `other`.\n\n",
            "```yaml\n",
            "metric_tag_value_allowlist:\n",
            "  - metric_prefix: requests.\n",
            "    tag_name: customer_id\n",
            "    values: [customer-1, customer-2]\n",
            "    on_miss: replace\n",
            "    replacement: other\n",
            "```\n\n",
            "This ADP-only key is independent from `metric_tag_filterlist`. Remote Config updates to ",
            "`metric_tag_filterlist` therefore do not replace locally configured value allow-lists. Value allow-list ",
            "changes require an ADP restart in this initial implementation. Rules apply to counters and sketch-backed ",
            "metrics before aggregation, including instrumented and origin tags. ADP matches `metric_prefix` after ",
            "DogStatsD mapper rewrites and `statsd_metric_namespace` prefixing, so configure the final metric name ",
            "produced by those steps.\n\n",
            "Whole-tag filtering runs first. If `metric_tag_filterlist` uses `action: include`, add the value-filtered ",
            "tag key to its `tags` list or the whole-tag rule removes it before value filtering. Value rules do not ",
            "operate on bare tags such as `customer_id`, because they have no value. An empty string in a key/value ",
            "tag such as `customer_id:` is a value and is subject to the allow-list; include `\"\"` in `values` to ",
            "retain it. An empty `values` list treats every key/value tag as a mismatch.\n\n",
            "Distinct metric prefixes must not overlap, even when the rules target different tags. Multiple rules may ",
            "use the same prefix when they target different tags. ADP rejects overlapping rules at startup so each ",
            "metric matches at most one prefix. ADP also rejects empty metric prefixes and tag names, duplicate prefix ",
            "and tag pairs, and tag names containing `:`. As with ",
            "`metric_tag_filterlist`, ADP does not trim configured strings: prefixes, tag names, values, and replacements ",
            "preserve whitespace and match exactly. Configure a replacement that cannot collide with a real tag value.",
        )),
        value_type: "ValueType::String",
        schema_default: Some("[]"),
        env_vars: &[],
        env_var_override: Some(&[]),
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: Some(
            r#"[{"metric_prefix":"smoke.","tag_name":"customer_id","values":["customer-1"],"on_miss":"replace","replacement":"other"}]"#,
        ),
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "tag_filterlist.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_permissive_decoding",
        description: "Relaxes decoder strictness",
        default: "true",
        documentation: Some(
            "By default, ADP parses DogStatsD packets with the same leniency as the core agent, \
             accepting packets that technically violate the spec. Setting this to `false` enables \
             strict mode, which rejects non-conformant packets. Strict mode is not available in \
             the core agent.",
        ),
        value_type: "ValueType::Bool",
        schema_default: Some("true"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_string_interner_size_bytes",
        description: "Explicit byte budget for context interner",
        default: "",
        documentation: Some(
            "Accepts a bare integer number of bytes or a human-readable byte-size string such as `12MiB`. \
             When unset, ADP derives the byte budget from `dogstatsd_string_interner_size`.",
        ),
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: Some(r#""12MiB""#),
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_tcp_port",
        description: "DogStatsD TCP listen port; 0 disables TCP",
        default: "0",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: Some("0"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    // ── otlp.rs ──────────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "otlp_config.traces.enable_otlp_compute_top_level_by_span_kind",
        description: "Enable OTLP top-level-by-span-kind",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: Some("true"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_config.traces.ignore_missing_datadog_fields",
        description: "Ignore missing Datadog fields in OTLP",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_config.traces.string_interner_size",
        description: "OTLP trace string interner capacity",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_config.receiver.protocols.http.transport",
        description: "OTLP HTTP receiver transport",
        default: "",
        documentation: None,
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_allow_context_heap_allocs",
        description: "Allow heap allocations for OTLP contexts",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: Some("true"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_cached_contexts_limit",
        description: "Max cached OTLP metric contexts",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_cached_tagsets_limit",
        description: "Max cached OTLP tagsets",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_string_interner_size",
        description: "OTLP context interner capacity",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    // ── aggregate.rs ─────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "aggregate_window_duration_seconds",
        description: "Aggregation window size",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    SalukiKey {
        yaml_path: "metric_aggregation_intervals",
        description: "Per-prefix DogStatsD aggregation windows",
        default: "[]",
        documentation: Some(
            r#"Each entry selects an aggregation window from 1 through 60 seconds for a non-empty, case-sensitive metric-name prefix. Prefixes must not overlap. Rules apply after mapper rewrites and metric namespace prefixing.

```yaml
metric_aggregation_intervals:
  - metric_prefix: high_resolution.
    interval_seconds: 1
  - metric_prefix: archival.
    interval_seconds: 60
```"#,
        ),
        value_type: "ValueType::String",
        schema_default: Some("[]"),
        env_vars: &[],
        env_var_override: Some(&[]),
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: Some(r#"[{"metric_prefix":"smoke.","interval_seconds":5}]"#),
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "aggregate.rs",
    },
    SalukiKey {
        yaml_path: "aggregate_flush_interval",
        description: "Aggregator flush period",
        default: "",
        documentation: None,
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: Some(r#"{"secs": 42, "nanos": 0}"#),
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    SalukiKey {
        yaml_path: "aggregate_context_limit",
        description: "Max contexts across aggregation windows",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    SalukiKey {
        yaml_path: "counter_expiry_seconds",
        description: "Idle counter keep-alive duration",
        default: "300",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &["dogstatsd_expiry_seconds"],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    SalukiKey {
        yaml_path: "aggregate_passthrough_idle_flush_timeout",
        description: "Passthrough buffer flush delay",
        default: "",
        documentation: None,
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: Some(r#"{"secs": 42, "nanos": 0}"#),
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    // ── trace_obfuscation.rs ─────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.dbms",
        description: "SQL obfuscation DBMS dialect",
        default: "",
        documentation: None,
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.dollar_quoted_func",
        description: "Preserve dollar-quoted SQL functions",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.keep_sql_alias",
        description: "Preserve SQL aliases in obfuscation",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.replace_digits",
        description: "Replace digits in SQL obfuscation",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.table_names",
        description: "Collect table names during obfuscation",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    // ── encoders.rs ──────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "flush_timeout_secs",
        description: "Encoder flush timeout (secs)",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::Traces, Pipeline::DogStatsD])",
        filename: "encoders.rs",
    },
    SalukiKey {
        yaml_path: "serializer_max_metrics_per_payload",
        description: "Max metrics per payload",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD])",
        filename: "encoders.rs",
    },
    // ── dogstatsd_mapper.rs ──────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "dogstatsd_mapper_string_interner_size",
        description: "Mapper string interner byte capacity",
        default: "64KiB",
        documentation: Some(
            "Controls the pre-allocated byte capacity for interning mapped metric names and tags. The default is \
             `64KiB`. Set this to a nonzero byte count; you can use a bare number of bytes or a human-readable \
             byte-size string such as `64KiB`. Larger values increase memory usage.",
        ),
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TYPED_CONFIG_SYSTEM"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd_mapper.rs",
    },
    // ── accounting.rs ────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "memory_limit",
        description: "Process memory limit",
        default: "",
        documentation: Some(
            "### `memory_limit` / `memory_slop_factor`

\
             ADP uses an explicit process memory limit (`memory_limit`) rather than relying on \
             Go's garbage collector. The `memory_slop_factor` reserves a fraction of the limit \
             to account for allocations not tracked by ADP's internal accounting. When memory \
             usage approaches `memory_limit`, ADP's global limiter begins exerting backpressure \
             (see `enable_global_limiter`).",
        ),
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &[],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::CrossCutting",
        filename: "accounting.rs",
    },
    SalukiKey {
        yaml_path: "memory_slop_factor",
        description: "Memory accounting slop fraction",
        default: "0.25",
        documentation: Some("See `memory_limit` above."),
        value_type: "ValueType::Float",
        schema_default: Some("0.25"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &[],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::CrossCutting",
        filename: "accounting.rs",
    },
];
