//! ADP-only configuration keys that are not in the Datadog Agent schema.
//! Shared between registry_gen.rs (for config registry annotations) and doc_gen.rs (for the
//! ADP-Only documentation section).

pub struct SalukiKey {
    pub yaml_path: &'static str,
    pub description: &'static str,
    pub default: &'static str,
    /// Multi-line documentation rendered as a prose section below the ADP-Only table.
    /// If the text starts with `#`, the heading is taken from the text itself.
    pub documentation: Option<&'static str>,
    // Fields used only by registry_gen:
    pub value_type: &'static str,
    pub schema_default: Option<&'static str>,
    pub env_vars: &'static [&'static str],
    pub env_var_override: Option<&'static [&'static str]>,
    pub additional_yaml_paths: &'static [&'static str],
    pub used_by: &'static [&'static str],
    pub test_json: Option<&'static str>,
    pub pipeline_affinity: &'static str,
    pub filename: &'static str,
}

pub static SALUKI_KEYS: &[SalukiKey] = &[
    // ── dogstatsd.rs ─────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "dogstatsd_allow_context_heap_allocs",
        description: "Allow heap allocations for contexts",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: Some("true"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_autoscale_udp_listeners",
        description: "Bind multiple UDP sockets via SO_REUSEPORT",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: Some("false"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_buffer_count",
        description: "Number of receive buffers",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_cached_contexts_limit",
        description: "Max cached metric contexts",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_cached_tagsets_limit",
        description: "Max cached tagsets",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_minimum_sample_rate",
        description: "Floor for metric sample rates",
        default: "",
        documentation: Some(
            "ADP enforces a minimum sample rate on incoming metrics to prevent memory exhaustion \
             from extremely low sample rates on histograms and sketches. Sending metrics with a \
             very high inverse sample rate (for example `@0.0000001`) can cause unbounded memory \
             growth in a sketch; this setting prevents that. The default is conservative enough \
             that normal clients are unaffected.",
        ),
        value_type: "ValueType::Float",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_permissive_decoding",
        description: "Relaxes decoder strictness",
        default: "true",
        documentation: Some(
            "By default, ADP parses DogStatsD packets with the same leniency as the core agent, \
             accepting packets that technically violate the spec. Setting this to `false` enables \
             strict mode, which rejects non-conformant packets. Strict mode is not available in \
             the core agent.",
        ),
        value_type: "ValueType::Bool",
        schema_default: Some("true"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_string_interner_size_bytes",
        description: "Explicit byte budget for context interner",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    SalukiKey {
        yaml_path: "dogstatsd_tcp_port",
        description: "TCP listen port for DSD",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd.rs",
    },
    // ── otlp.rs ──────────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "otlp_config.traces.enable_otlp_compute_top_level_by_span_kind",
        description: "Enable OTLP top-level-by-span-kind",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: Some("true"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["OTLP_DECODER_CONFIGURATION", "OTLP_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_config.traces.ignore_missing_datadog_fields",
        description: "Ignore missing Datadog fields in OTLP",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["OTLP_DECODER_CONFIGURATION", "OTLP_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_config.traces.string_interner_size",
        description: "OTLP trace string interner capacity",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["OTLP_DECODER_CONFIGURATION", "OTLP_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_config.receiver.protocols.http.transport",
        description: "OTLP HTTP receiver transport",
        default: "",
        documentation: None,
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["OTLP_RELAY_CONFIGURATION", "OTLP_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_allow_context_heap_allocs",
        description: "Allow heap allocations for OTLP contexts",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: Some("true"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["OTLP_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_cached_contexts_limit",
        description: "Max cached OTLP metric contexts",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["OTLP_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_cached_tagsets_limit",
        description: "Max cached OTLP tagsets",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["OTLP_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    SalukiKey {
        yaml_path: "otlp_string_interner_size",
        description: "OTLP context interner capacity",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["OTLP_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Otlp])",
        filename: "otlp.rs",
    },
    // ── aggregate.rs ─────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "aggregate_window_duration_seconds",
        description: "Aggregation window size",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["AGGREGATE_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    SalukiKey {
        yaml_path: "aggregate_flush_interval",
        description: "Aggregator flush period",
        default: "",
        documentation: None,
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["AGGREGATE_CONFIGURATION"],
        test_json: Some(r#"{"secs": 42, "nanos": 0}"#),
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    SalukiKey {
        yaml_path: "aggregate_context_limit",
        description: "Max contexts per aggregation window",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["AGGREGATE_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    SalukiKey {
        yaml_path: "counter_expiry_seconds",
        description: "Idle counter keep-alive duration",
        default: "300",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &["dogstatsd_expiry_seconds"],
        used_by: &["AGGREGATE_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    SalukiKey {
        yaml_path: "aggregate_passthrough_idle_flush_timeout",
        description: "Passthrough buffer flush delay",
        default: "",
        documentation: None,
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["AGGREGATE_CONFIGURATION"],
        test_json: Some(r#"{"secs": 42, "nanos": 0}"#),
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks])",
        filename: "aggregate.rs",
    },
    // ── trace_obfuscation.rs ─────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.dbms",
        description: "SQL obfuscation DBMS dialect",
        default: "",
        documentation: None,
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TRACE_OBFUSCATION_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.dollar_quoted_func",
        description: "Preserve dollar-quoted SQL functions",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TRACE_OBFUSCATION_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.keep_sql_alias",
        description: "Preserve SQL aliases in obfuscation",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TRACE_OBFUSCATION_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.replace_digits",
        description: "Replace digits in SQL obfuscation",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TRACE_OBFUSCATION_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    SalukiKey {
        yaml_path: "apm_config.obfuscation.sql.table_names",
        description: "Collect table names during obfuscation",
        default: "",
        documentation: None,
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["TRACE_OBFUSCATION_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Traces])",
        filename: "trace_obfuscation.rs",
    },
    // ── encoders.rs ──────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "flush_timeout_secs",
        description: "Encoder flush timeout (secs)",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &[
            "DATADOG_APM_STATS_ENCODER_CONFIGURATION",
            "DATADOG_METRICS_CONFIGURATION",
            "DATADOG_TRACE_CONFIGURATION",
        ],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::Traces, Pipeline::DogStatsD])",
        filename: "encoders.rs",
    },
    SalukiKey {
        yaml_path: "serializer_max_metrics_per_payload",
        description: "Max metrics per payload",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DATADOG_METRICS_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD])",
        filename: "encoders.rs",
    },
    // ── dogstatsd_mapper.rs ──────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "dogstatsd_mapper_string_interner_size",
        description: "Mapper string interner capacity",
        default: "",
        documentation: None,
        value_type: "ValueType::Integer",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &["DOGSTATSD_MAPPER_CONFIGURATION"],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::Pipelines(&[Pipeline::DogStatsD])",
        filename: "dogstatsd_mapper.rs",
    },
    // ── accounting.rs ────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "memory_limit",
        description: "Process memory limit",
        default: "",
        documentation: Some(
            "### `memory_limit` / `memory_slop_factor`

\
             ADP uses an explicit process memory limit (`memory_limit`) rather than relying on \
             Go's garbage collector. The `memory_slop_factor` reserves a fraction of the limit \
             to account for allocations not tracked by ADP's internal accounting. When memory \
             usage approaches `memory_limit`, ADP's global limiter begins exerting backpressure \
             (see `enable_global_limiter`).",
        ),
        value_type: "ValueType::String",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &[],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::CrossCutting",
        filename: "accounting.rs",
    },
    SalukiKey {
        yaml_path: "memory_slop_factor",
        description: "Memory accounting slop fraction",
        default: "0.25",
        documentation: Some("See `memory_limit` above."),
        value_type: "ValueType::Float",
        schema_default: Some("0.25"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &[],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::CrossCutting",
        filename: "accounting.rs",
    },
    // ── data_plane.rs ────────────────────────────────────────────────────────
    SalukiKey {
        yaml_path: "data_plane.remote_agent_enabled",
        description: "Enable remote agent mode",
        default: "true",
        documentation: Some(
            "### `data_plane.remote_agent_enabled` / `data_plane.use_new_config_stream_endpoint`

\
             These two keys are transitional flags being phased out. Both will be implied by \
             `data_plane.standalone_mode=false` in a future release. Do not rely on them for \
             new deployments.",
        ),
        value_type: "ValueType::Bool",
        schema_default: Some("true"),
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &[],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::CrossCutting",
        filename: "data_plane.rs",
    },
    SalukiKey {
        yaml_path: "data_plane.use_new_config_stream_endpoint",
        description: "Use new config stream endpoint",
        default: "",
        documentation: Some("See `data_plane.remote_agent_enabled` above."),
        value_type: "ValueType::Bool",
        schema_default: None,
        env_vars: &[],
        env_var_override: None,
        additional_yaml_paths: &[],
        used_by: &[],
        test_json: None,
        pipeline_affinity: "PipelineAffinity::CrossCutting",
        filename: "data_plane.rs",
    },
];
