name: Bug Report
description: File a bug report.
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report! Please be sure to read through carefully and provide as much detail as possible.
  - type: input
    id: saluki-version
    attributes:
      label: Saluki Version
      description: What version of Saluki was used? This can be a Git commit hash or tag.
    validations:
      required: true
  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: What version of Rust was used to build Saluki?
      placeholder: ex. 1.77, nightly-2024-04-10
    validations:
      required: true
  - type: input
    id: os-arch
    attributes:
      label: Operating System / Architecture
      description: What operating system and architecture was used? This can also include containerized deployments.
      placeholder: ex. Ubuntu 22.04 ARM64, Kubernetes 1.27 x86-64
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: What went wrong? What did you expect to happen? How can we reproduce the bug?
    validations:
      required: true
  - type: textarea
    id: logs-errors-etc
    attributes:
      label: Relevant log output, compilation errors, etc
      description: Please copy and paste any relevant log output, compilation errors, etc. This will be automatically formatted into code, so no need for backticks.
      render: shell
