(*
Dogstatsd packets, with the following alterations
- we can send multiple metrics together. Metrics a separated by newline, a double newline is EOF
- metric & tag names are limited to a restricted set for readability
*)
start = payload "\n" ;

payload = message | message "\n" message ;

message = metric;

metric = name ":" value "|" mtype [ "|@" srate ] [ "|#" tags ]  ;

mtype = "c" | "g" | "ms" | "h" | "s" | "d" ;

srate = "0.1" | "0.01" | "1.0" ;

value = ["-"] digits ["." digits] ;

tags = tag | tag "," tags ;
tag = tagname [ ":" tagval ] ;
tagname = name ;
tagval = name | value ;

name = letter [ letter ] [ letter ] [letter] ;

digits = digit | digit digits ;
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
letter = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j"
       | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t"
       | "u" | "v" | "w" | "x" | "y" | "z" ;
