ARG DD_AGENT_VERSION=7.77.2-jmx
ARG DD_AGENT_IMAGE=registry.datadoghq.com/agent:${DD_AGENT_VERSION}
ARG ADP_IMAGE=saluki-images/agent-data-plane:testing-devel
ARG DD_DATA_PLANE_ENABLED=
ARG DD_DATA_PLANE_STANDALONE_MODE=
ARG DD_DATA_PLANE_USE_NEW_CONFIG_STREAM_ENDPOINT=
ARG DD_DATA_PLANE_REMOTE_AGENT_ENABLED=
ARG DD_DATA_PLANE_DOGSTATSD_ENABLED=
ARG DD_CLUSTER_AGENT_CLUSTER_TAGGER_GRPC_MAX_MESSAGE_SIZE=
ARG ADP_DD_DATA_PLANE_TELEMETRY_ENABLED=
ARG ADP_DD_DATA_PLANE_TELEMETRY_LISTEN_ADDR=
ARG ADP_DD_AGGREGATE_CONTEXT_LIMIT=
ARG ADP_DD_DOGSTATSD_STRING_INTERNER_SIZE=
# Reference the ADP image so we can copy the relevant bits out of it.
FROM ${ADP_IMAGE} AS adp

# Build off of the official Datadog Agent image.
FROM ${DD_AGENT_IMAGE}

ARG DD_DATA_PLANE_ENABLED=
ARG DD_DATA_PLANE_STANDALONE_MODE=
ARG DD_DATA_PLANE_USE_NEW_CONFIG_STREAM_ENDPOINT=
ARG DD_DATA_PLANE_REMOTE_AGENT_ENABLED=
ARG DD_DATA_PLANE_DOGSTATSD_ENABLED=
ARG DD_CLUSTER_AGENT_CLUSTER_TAGGER_GRPC_MAX_MESSAGE_SIZE=
ARG ADP_DD_DATA_PLANE_TELEMETRY_ENABLED=
ARG ADP_DD_DATA_PLANE_TELEMETRY_LISTEN_ADDR=
ARG ADP_DD_AGGREGATE_CONTEXT_LIMIT=
ARG ADP_DD_DOGSTATSD_STRING_INTERNER_SIZE=

ENV DD_DATA_PLANE_ENABLED=${DD_DATA_PLANE_ENABLED} \
    DD_DATA_PLANE_STANDALONE_MODE=${DD_DATA_PLANE_STANDALONE_MODE} \
    DD_DATA_PLANE_USE_NEW_CONFIG_STREAM_ENDPOINT=${DD_DATA_PLANE_USE_NEW_CONFIG_STREAM_ENDPOINT} \
    DD_DATA_PLANE_REMOTE_AGENT_ENABLED=${DD_DATA_PLANE_REMOTE_AGENT_ENABLED} \
    DD_DATA_PLANE_DOGSTATSD_ENABLED=${DD_DATA_PLANE_DOGSTATSD_ENABLED} \
    DD_CLUSTER_AGENT_CLUSTER_TAGGER_GRPC_MAX_MESSAGE_SIZE=${DD_CLUSTER_AGENT_CLUSTER_TAGGER_GRPC_MAX_MESSAGE_SIZE} \
    ADP_DD_DATA_PLANE_TELEMETRY_ENABLED=${ADP_DD_DATA_PLANE_TELEMETRY_ENABLED} \
    ADP_DD_DATA_PLANE_TELEMETRY_LISTEN_ADDR=${ADP_DD_DATA_PLANE_TELEMETRY_LISTEN_ADDR} \
    ADP_DD_AGGREGATE_CONTEXT_LIMIT=${ADP_DD_AGGREGATE_CONTEXT_LIMIT} \
    ADP_DD_DOGSTATSD_STRING_INTERNER_SIZE=${ADP_DD_DOGSTATSD_STRING_INTERNER_SIZE}

# Copy the ADP binary and all of the required licensing bits.
COPY --from=adp /usr/local/bin/agent-data-plane /opt/datadog-agent/embedded/bin/agent-data-plane
COPY --from=adp /opt/datadog/agent-data-plane /opt/datadog/agent-data-plane

# Add the s6 service files for Agent Data Plane.
#
# ADP will only run when the `DD_DATA_PLANE_ENABLED` environment variable is set to `true`.
COPY docker/cont-init.d /etc/cont-init.d/
COPY docker/s6-services /etc/services.d/

COPY --chmod=755 docker/entrypoint.sh /entrypoint.sh

# Remove default check configuration to ensure no checks end up running by default.
RUN rm -rf /etc/datadog-agent/conf.d/*

# Use an updated healthcheck since the default healthcheck from `datadog/agent` is wildly overconservative.
HEALTHCHECK --interval=60s --timeout=5s --retries=2 --start-period=30s --start-interval=1s \
    CMD ["/probe.sh"]

# Everything else we'll leave at the defaults of the Datadog Agent image.
