[package]
name = "metrics-intake"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
axum = { workspace = true, features = ["http1", "json", "tokio"] }
datadog-protos = { workspace = true }
protobuf = { workspace = true }
saluki-app = { workspace = true, features = ["logging"] }
saluki-error = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stele = { path = "../stele" }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
tower = { workspace = true }
tower-http = { workspace = true, features = ["compression-zstd", "decompression-deflate", "decompression-zstd"] }
tracing = { workspace = true }

[lints]
workspace = true
