.build-adp-definition:
  stage: build
  image: ${SALUKI_BUILD_IMAGE}
  needs:
    - calculate-build-metadata
  retry: 2
  timeout: 15m
  variables:
    DDCI_CONFIGURE_OTEL_EXPORTER: true
    BUILD_FEATURES: "default"
    FIPS_ENABLED: "false"
  script:
    - ADP_BUILD_PROFILE=${BUILD_PROFILE}
      ADP_BUILD_FEATURES=${BUILD_FEATURES}
      ADP_IMAGE_OUTPUT="push-by-digest=true,type=image,push=true"
      ADP_APP_IMAGE=${APP_IMAGE}
      ADP_APP_VERSION=${ADP_IMAGE_VERSION}
      ADP_APP_BUILD_TIME=${CI_PIPELINE_CREATED_AT}
      make build-adp-image
  artifacts:
    paths:
      - build-metadata.*

.build-adp-multi-arch-definition:
  stage: build
  image: ${DOCKER_BUILD_IMAGE}
  script:
    # Collect the manifest list digests for our AMD64 and ARM64 images, and then build a multi-arch manifest from them.
    - export AMD64_DIGEST=$(jq -r '."containerimage.digest"' build-metadata.amd64)
    - export ARM64_DIGEST=$(jq -r '."containerimage.digest"' build-metadata.arm64)
    - docker buildx imagetools create --tag ${IMAGE_TAG}
      ${ADP_IMAGE_REPO_BASE}@${AMD64_DIGEST}
      ${ADP_IMAGE_REPO_BASE}@${ARM64_DIGEST}

calculate-build-metadata:
  stage: build
  image: ${SALUKI_BUILD_CI_IMAGE}
  needs: []
  script:
    - make emit-build-metadata >> build.env
  artifacts:
    reports:
      dotenv: build.env

build-adp-image-amd64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["arch:amd64"]
  variables:
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}

build-adp-image-arm64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["arch:arm64"]
  variables:
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}

build-adp-image:
  extends: [.build-common-variables, .build-adp-multi-arch-definition]
  needs:
    - build-adp-image-amd64
    - build-adp-image-arm64
  variables:
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG}

build-adp-image-fips-amd64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["arch:amd64"]
  variables:
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

build-adp-image-fips-arm64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["arch:arm64"]
  variables:
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

build-adp-image-fips:
  extends: [.build-common-variables, .build-adp-multi-arch-definition]
  needs:
    - build-adp-image-fips-amd64
    - build-adp-image-fips-arm64
  variables:
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG_FIPS}

# Internal-specific build variants that use a GBI-compliant base image.
build-adp-image-internal-amd64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["arch:amd64"]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  variables:
    ARCH_TAG: amd64
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}

build-adp-image-internal-arm64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["arch:arm64"]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  variables:
    ARCH_TAG: arm64
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}

build-adp-image-internal:
  extends: [.build-common-variables, .build-adp-multi-arch-definition]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-internal-amd64
    - build-adp-image-internal-arm64
  variables:
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG}-internal

build-adp-image-fips-internal-amd64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["arch:amd64"]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  variables:
    ARCH_TAG: amd64
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

build-adp-image-fips-internal-arm64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["arch:arm64"]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  variables:
    ARCH_TAG: arm64
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

build-adp-image-fips-internal:
  extends: [.build-common-variables, .build-adp-multi-arch-definition]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-fips-internal-amd64
    - build-adp-image-fips-internal-arm64
  variables:
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG_FIPS}-internal

# Finally, we publish our internal images after running through a small build process to add some necessary tooling
# required for the images to be deployed/used internally.
#
# These takes them from the sort of temporary holding ground of `registry.ddbuild.io/saluki/agent-data-plane`, adds the
# necessary pieces, and then publishes them to `registry.ddbuild.io/agent-data-plane` as a first-class citizen.
#
# We specifically duplicate our `ADP_INTERNAL_IMAGE_TAG` (and FIPS-specific variant) tag and construct the same value
# manually because otherwise, the variable is evaluated in the downstream job, leading to the wrong values being
# substituted.
publish-adp-image-internal:
  stage: build
  extends: [.build-common-variables]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-internal
  trigger:
    project: DataDog/images
    branch: master
    strategy: depend
  variables:
    IMAGE_NAME: agent-data-plane
    IMAGE_VERSION: tmpl-v3
    TMPL_SRC_REPO: ${ADP_IMAGE_REPO_NAME}
    TMPL_SRC_IMAGE: ${ADP_IMAGE_VERSION}-internal
    RELEASE_TAG: ${ADP_IMAGE_VERSION}
    BUILD_TAG: "${ADP_IMAGE_VERSION}-build"
    RELEASE_STAGING: "true"
    RELEASE_PROD: "true"
    ENABLE_NYDUS_PREVIEW: "true"

publish-adp-image-internal-fips:
  stage: build
  extends: [.build-common-variables]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-fips-internal
  trigger:
    project: DataDog/images
    branch: master
    strategy: depend
  variables:
    IMAGE_NAME: agent-data-plane
    IMAGE_VERSION: tmpl-v3
    TMPL_SRC_REPO: ${ADP_IMAGE_REPO_NAME}
    TMPL_SRC_IMAGE: ${ADP_IMAGE_VERSION_FIPS}-internal
    RELEASE_TAG: ${ADP_IMAGE_VERSION_FIPS}
    BUILD_TAG: "${ADP_IMAGE_VERSION_FIPS}-build"
    RELEASE_STAGING: "true"
    RELEASE_PROD: "true"
    ENABLE_NYDUS_PREVIEW: "true"

display-image-tags:
  extends: [.build-common-variables]
  stage: build
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-internal
    - build-adp-image-fips-internal
    - publish-adp-image-internal
    - publish-adp-image-internal-fips
  script:
    - |-
      cat <<EOF
      # Image Tags

      ## Agent Data Plane (suitable for internal deployments, GBI-based)
      Non-FIPS: ${IMAGE_REGISTRY}/${ADP_IMAGE_TAG}
      FIPS:     ${IMAGE_REGISTRY}/${ADP_IMAGE_TAG_FIPS}
      EOF
