.build-adp-definition:
  stage: build
  image: ${DOCKER_BUILD_IMAGE}
  needs:
    - calculate-build-metadata
  retry: 2
  timeout: 15m
  variables:
    APP_BUILD_TIME: ${CI_PIPELINE_CREATED_AT}
    DDCI_CONFIGURE_OTEL_EXPORTER: true
  script:
    - docker buildx create --name adp-builder --driver docker-container --use
    - 'echo "Building ADP image... (arch: ${ARCH_TAG}, image version: ${ADP_IMAGE_VERSION}, build concurrency: ${CARGO_BUILD_JOBS}, profile: ${BUILD_PROFILE})..."'
    - docker buildx build
      --file ./docker/Dockerfile.agent-data-plane
      --output push-by-digest=true,type=image,push=true
      --metadata-file ./build-metadata.${ARCH_TAG}
      --tag ${ADP_IMAGE_REPO_BASE}
      --build-arg BUILD_IMAGE=${ALPINE_BUILD_IMAGE}
      --build-arg APP_IMAGE=${APP_IMAGE}
      --build-arg BUILD_PROFILE=${BUILD_PROFILE}
      --build-arg BUILD_FEATURES=${BUILD_FEATURES}
      --build-arg BUILDER_BASE=${BUILDER_BASE}
      --build-arg APP_FULL_NAME="${APP_FULL_NAME}"
      --build-arg APP_SHORT_NAME=${APP_SHORT_NAME}
      --build-arg APP_IDENTIFIER=${APP_IDENTIFIER}
      --build-arg APP_VERSION=${APP_VERSION}
      --build-arg APP_GIT_HASH=${APP_GIT_HASH}
      --build-arg APP_BUILD_TIME=${APP_BUILD_TIME}
      --build-arg APP_DEV_BUILD=${APP_DEV_BUILD}
      --label "org.opencontainers.image.authors=Datadog <package@datadoghq.com>"
      --label "org.opencontainers.image.base.name=${APP_IMAGE}"
      --label "org.opencontainers.image.created=${CI_PIPELINE_CREATED_AT}"
      --label "org.opencontainers.image.ref.name=agent-data-plane"
      --label "org.opencontainers.image.revision=${CI_COMMIT_SHA}"
      --label "org.opencontainers.image.source=https://github.com/DataDog/saluki"
      --label "org.opencontainers.image.title=Agent Data Plane"
      --label "org.opencontainers.image.vendor=Datadog, Inc."
      --label "org.opencontainers.image.version=${ADP_IMAGE_VERSION}"
      --push
      .
  artifacts:
    paths:
      - build-metadata.*

.build-adp-multi-arch-definition:
  stage: build
  image: ${DOCKER_BUILD_IMAGE}
  script:
    # Collect the manifest list digests for our AMD64 and ARM64 images, and then build a multi-arch manifest from them.
    - export AMD64_DIGEST=$(jq -r '."containerimage.digest"' build-metadata.amd64)
    - export ARM64_DIGEST=$(jq -r '."containerimage.digest"' build-metadata.arm64)
    - docker buildx imagetools create --tag ${IMAGE_TAG}
      ${ADP_IMAGE_REPO_BASE}@${AMD64_DIGEST}
      ${ADP_IMAGE_REPO_BASE}@${ARM64_DIGEST}

calculate-build-metadata:
  stage: build
  image: ${SALUKI_BUILD_CI_IMAGE}
  needs: []
  script:
    - make emit-build-metadata >> build.env
  artifacts:
    reports:
      dotenv: build.env

build-adp-image-amd64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["docker-in-docker:amd64"]
  variables:
    ARCH_TAG: amd64
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}

build-adp-image-arm64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["docker-in-docker:arm64"]
  variables:
    ARCH_TAG: arm64
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}

build-adp-image:
  extends: [.build-common-variables, .build-adp-multi-arch-definition]
  needs:
    - build-adp-image-amd64
    - build-adp-image-arm64
  variables:
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG}

build-adp-image-fips-amd64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["docker-in-docker:amd64"]
  variables:
    ARCH_TAG: amd64
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

build-adp-image-fips-arm64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["docker-in-docker:arm64"]
  variables:
    ARCH_TAG: arm64
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

build-adp-image-fips:
  extends: [.build-common-variables, .build-adp-multi-arch-definition]
  needs:
    - build-adp-image-fips-amd64
    - build-adp-image-fips-arm64
  variables:
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG_FIPS}

# Internal-specific build variants that use a GBI-compliant base image.
build-adp-image-internal-amd64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["docker-in-docker:amd64"]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  variables:
    ARCH_TAG: amd64
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}

build-adp-image-internal-arm64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["docker-in-docker:arm64"]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  variables:
    ARCH_TAG: arm64
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}

build-adp-image-internal:
  extends: [.build-common-variables, .build-adp-multi-arch-definition]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-internal-amd64
    - build-adp-image-internal-arm64
  variables:
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG}-internal

build-adp-image-fips-internal-amd64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["docker-in-docker:amd64"]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  variables:
    ARCH_TAG: amd64
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

build-adp-image-fips-internal-arm64:
  extends: [.build-common-variables, .build-adp-definition]
  tags: ["docker-in-docker:arm64"]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  variables:
    ARCH_TAG: arm64
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

build-adp-image-fips-internal:
  extends: [.build-common-variables, .build-adp-multi-arch-definition]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-fips-internal-amd64
    - build-adp-image-fips-internal-arm64
  variables:
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG_FIPS}-internal

# Finally, we publish our internal images after running through a small build process to add some necessary tooling
# required for the images to be deployed/used internally.
#
# These takes them from the sort of temporary holding ground of `registry.ddbuild.io/saluki/agent-data-plane`, adds the
# necessary pieces, and then publishes them to `registry.ddbuild.io/agent-data-plane` as a first-class citizen.
#
# We specifically duplicate our `ADP_INTERNAL_IMAGE_TAG` (and FIPS-specific variant) tag and construct the same value
# manually because otherwise, the variable is evaluated in the downstream job, leading to the wrong values being
# substituted.
publish-adp-image-internal:
  stage: build
  extends: [.build-common-variables]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-internal
  trigger:
    project: DataDog/images
    branch: master
    strategy: depend
  variables:
    IMAGE_NAME: agent-data-plane
    IMAGE_VERSION: tmpl-v3
    TMPL_SRC_REPO: ${ADP_IMAGE_REPO_NAME}
    TMPL_SRC_IMAGE: ${ADP_IMAGE_VERSION}-internal
    RELEASE_TAG: ${ADP_IMAGE_VERSION}
    BUILD_TAG: "${ADP_IMAGE_VERSION}-build"
    RELEASE_STAGING: "true"
    RELEASE_PROD: "true"

publish-adp-image-internal-fips:
  stage: build
  extends: [.build-common-variables]
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-fips-internal
  trigger:
    project: DataDog/images
    branch: master
    strategy: depend
  variables:
    IMAGE_NAME: agent-data-plane
    IMAGE_VERSION: tmpl-v3
    TMPL_SRC_REPO: ${ADP_IMAGE_REPO_NAME}
    TMPL_SRC_IMAGE: ${ADP_IMAGE_VERSION_FIPS}-internal
    RELEASE_TAG: ${ADP_IMAGE_VERSION_FIPS}
    BUILD_TAG: "${ADP_IMAGE_VERSION_FIPS}-build"
    RELEASE_STAGING: "true"
    RELEASE_PROD: "true"

display-image-tags:
  extends: [.build-common-variables]
  stage: build
  rules:
    - if: !reference [.on_mq_branch, rules, if]
      when: never
    - when: always
  needs:
    - build-adp-image-internal
    - build-adp-image-fips-internal
    - publish-adp-image-internal
    - publish-adp-image-internal-fips
  script:
    - |-
      cat <<EOF
      # Image Tags

      ## Agent Data Plane (suitable for internal deployments, GBI-based)
      Non-FIPS: ${IMAGE_REGISTRY}/${ADP_IMAGE_TAG}
      FIPS:     ${IMAGE_REGISTRY}/${ADP_IMAGE_TAG_FIPS}
      EOF
