calculate-build-metadata:
  stage: build
  image: ${SALUKI_BUILD_CI_IMAGE}
  needs: []
  script:
    - make emit-build-metadata >> build.env
  artifacts:
    reports:
      dotenv: build.env

build-adp-image:
  stage: build
  image: ${DOCKER_BUILD_IMAGE}
  needs:
    - calculate-build-metadata
  variables:
    # Compiling Rust is intensive. ¯\_(ツ)_/¯
    KUBERNETES_CPU_REQUEST: "16"
    KUBERNETES_MEMORY_REQUEST: "8Gi"
    KUBERNETES_MEMORY_LIMIT: "12Gi"
  script:
    # As it turns out, doing the multi-platform build in a single step means we're sacrificing build performance. For
    # example, building the ARM64 image on an AMD64 runner is anywhere between 2-3x slower, which then slows downs
    # things like the correctness test.
    #
    # We should consider bringing back the individual build steps, and then constructing the multi-image manifest
    # ourselves.
    - docker buildx build
      --platform linux/amd64,linux/arm64
      --file ./docker/Dockerfile.agent-data-plane
      --tag ${ADP_IMAGE_BASE}:${CI_COMMIT_SHA}
      --build-arg BUILD_IMAGE=${SALUKI_BUILD_CI_IMAGE}
      --build-arg APP_IMAGE=${GBI_BASE_IMAGE}
      --build-arg BUILD_PROFILE=optimized-debug-release
      --build-arg APP_NAME=${APP_NAME}
      --build-arg APP_SHORT_NAME=${APP_SHORT_NAME}
      --build-arg APP_VERSION=${APP_VERSION}
      --build-arg APP_GIT_HASH=${APP_GIT_HASH}
      --build-arg APP_BUILD_TIME=${APP_BUILD_TIME}
      --label git.repository=${CI_PROJECT_NAME}
      --label git.branch=${CI_COMMIT_REF_NAME}
      --label git.commit=${CI_COMMIT_SHA}
      --label ci.pipeline_id=${CI_PIPELINE_ID}
      --label ci.job_id=${CI_JOB_ID}
      --push
      .

build-converged-adp-image:
  stage: build
  image: ${DOCKER_BUILD_IMAGE}
  needs:
    - build-adp-image
  variables:
    IMAGE_TAG: "${INTERNAL_DD_AGENT_IMAGE}-adp-${CI_COMMIT_SHA}"
  id_tokens:
    DDSIGN_ID_TOKEN:
      aud: image-integrity
  script:
    - docker buildx build
      --platform linux/amd64,linux/arm64
      --file ./docker/Dockerfile.datadog-agent
      --metadata-file	/tmp/build.metadata
      --build-arg "DD_AGENT_IMAGE=${INTERNAL_DD_AGENT_IMAGE}"
      --build-arg "ADP_IMAGE=${ADP_IMAGE_BASE}:${CI_COMMIT_SHA}"
      --tag "${IMAGE_TAG}"
      --label git.repository=${CI_PROJECT_NAME}
      --label git.branch=${CI_COMMIT_REF_NAME}
      --label git.commit=${CI_COMMIT_SHA}
      --label ci.pipeline_id=${CI_PIPELINE_ID}
      --label ci.job_id=${CI_JOB_ID}
      --push
      .
    - ddsign sign ${IMAGE_TAG} --docker-metadata-file /tmp/build.metadata
