build-agent-data-plane-docker:
  stage: build
  image: "${BUILD_CI_IMAGE}"
  script:
    - docker buildx build
      --platform linux/amd64,linux/arm64
      --file ./docker/Dockerfile.agent-data-plane
      --tag ${ADP_IMAGE_BASE}:${VERSION}
      --build-arg BUILD_IMAGE=${BUILD_CI_IMAGE}
      --build-arg APP_IMAGE=${ADP_APP_IMAGE}
      --label git.repository=${CI_PROJECT_NAME}
      --label git.branch=${CI_COMMIT_REF_NAME}
      --label git.commit=${CI_COMMIT_SHA}
      --label ci.pipeline_id=${CI_PIPELINE_ID}
      --label ci.job_id=${CI_JOB_ID}
      --push
      .
