.build-adp-definition:
  stage: build
  image: ${SALUKI_BUILD_CI_IMAGE}
  needs:
    - calculate-build-metadata
  retry: 2
  timeout: 15m
  variables:
    APP_BUILD_TIME: "${CI_PIPELINE_CREATED_AT}"
    DDCI_CONFIGURE_OTEL_EXPORTER: true
    # Try to limit build concurrency to avoid issues with hitting container cgroup limits.
    CARGO_BUILD_JOBS: 12
  script:
    - 'echo "Building ADP image ${IMAGE_TAG}... (image version: ${ADP_IMAGE_VERSION}, build concurrency: ${CARGO_BUILD_JOBS})..."'
    - aws configure list
    - docker buildx build
      --platform linux/amd64,linux/arm64
      --file ./docker/Dockerfile.agent-data-plane
      --metadata-file /tmp/build.metadata
      --tag ${IMAGE_TAG}
      --build-arg CARGO_BUILD_JOBS=${CARGO_BUILD_JOBS}
      --build-arg RUSTC_WRAPPER=sccache
      --build-arg SCCACHE_BUCKET=saluki-build-cache
      --build-arg SCCACHE_REGION=us-east-1
      --build-arg BUILD_IMAGE=${ALPINE_BUILD_IMAGE}
      --build-arg APP_IMAGE=${APP_IMAGE}
      --build-arg BUILD_PROFILE=${BUILD_PROFILE}
      --build-arg BUILD_FEATURES=${BUILD_FEATURES}
      --build-arg BUILDER_BASE=${BUILDER_BASE}
      --build-arg APP_FULL_NAME="${APP_FULL_NAME}"
      --build-arg APP_SHORT_NAME=${APP_SHORT_NAME}
      --build-arg APP_IDENTIFIER=${APP_IDENTIFIER}
      --build-arg APP_VERSION=${APP_VERSION}
      --build-arg APP_GIT_HASH=${APP_GIT_HASH}
      --build-arg APP_BUILD_TIME=${APP_BUILD_TIME}
      --build-arg APP_DEV_BUILD=${APP_DEV_BUILD}
      --label "org.opencontainers.image.authors=Datadog <package@datadoghq.com>"
      --label "org.opencontainers.image.base.name=${APP_IMAGE}"
      --label "org.opencontainers.image.created=${CI_PIPELINE_CREATED_AT}"
      --label "org.opencontainers.image.ref.name=agent-data-plane"
      --label "org.opencontainers.image.revision=${CI_COMMIT_SHA}"
      --label "org.opencontainers.image.source=https://github.com/DataDog/saluki"
      --label "org.opencontainers.image.title=Agent Data Plane"
      --label "org.opencontainers.image.vendor=Datadog, Inc."
      --label "org.opencontainers.image.version=${ADP_IMAGE_VERSION}"
      --push
      .

calculate-build-metadata:
  stage: build
  image: ${SALUKI_BUILD_CI_IMAGE}
  needs: []
  script:
    - make emit-build-metadata >> build.env
  artifacts:
    reports:
      dotenv: build.env

build-adp-image:
  extends: [.build-common-variables, .build-adp-definition]
  variables:
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG}

build-adp-image-fips:
  extends: [.build-common-variables, .build-adp-definition]
  variables:
    APP_IMAGE: ${ADP_PUBLIC_BASE_IMAGE}
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG_FIPS}
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

# Internal-specific build variants that use a GBI-compliant base image.
build-adp-image-internal:
  extends: [.build-common-variables, .build-adp-definition]
  variables:
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG}-internal

build-adp-image-fips-internal:
  extends: [.build-common-variables, .build-adp-definition]
  variables:
    APP_IMAGE: ${ADP_INTERNAL_BASE_IMAGE}
    IMAGE_TAG: ${ADP_FULL_IMAGE_TAG_FIPS}-internal
    BUILD_FEATURES: "fips"
    FIPS_ENABLED: "true"

# Finally, we publish our internal images after running through a small build process to add some necessary tooling
# required for the images to be deployed/used internally.
#
# These takes them from the sort of temporary holding ground of `registry.ddbuild.io/saluki/agent-data-plane`, adds the
# necessary pieces, and then publishes them to `registry.ddbuild.io/agent-data-plane` as a first-class citizen.
#
# We specifically duplicate our `ADP_INTERNAL_IMAGE_TAG` (and FIPS-specific variant) tag and construct the same value
# manually because otherwise, the variable is evaluated in the downstream job, leading to the wrong values being
# substituted.
publish-adp-image-internal:
  stage: build
  extends: [.build-common-variables]
  needs:
    - build-adp-image-internal
  trigger:
    project: DataDog/images
    branch: master
    strategy: depend
  variables:
    IMAGE_NAME: agent-data-plane
    IMAGE_VERSION: tmpl-v1
    TMPL_SRC_REPO: ${ADP_IMAGE_REPO_NAME}
    TMPL_SRC_IMAGE: ${ADP_IMAGE_VERSION}-internal
    RELEASE_TAG: ${ADP_IMAGE_VERSION}
    BUILD_TAG: "${ADP_IMAGE_VERSION}-build"
    RELEASE_STAGING: "true"
    RELEASE_PROD: "true"

publish-adp-image-internal-fips:
  stage: build
  extends: [.build-common-variables]
  needs:
    - build-adp-image-fips-internal
  trigger:
    project: DataDog/images
    branch: master
    strategy: depend
  variables:
    IMAGE_NAME: agent-data-plane
    IMAGE_VERSION: tmpl-v1
    TMPL_SRC_REPO: ${ADP_IMAGE_REPO_NAME}
    TMPL_SRC_IMAGE: ${ADP_IMAGE_VERSION_FIPS}-internal
    RELEASE_TAG: ${ADP_IMAGE_VERSION_FIPS}
    BUILD_TAG: "${ADP_IMAGE_VERSION_FIPS}-build"
    RELEASE_STAGING: "true"
    RELEASE_PROD: "true"

display-image-tags:
  extends: [.build-common-variables]
  stage: build
  needs:
    - build-adp-image-internal
    - build-adp-image-fips-internal
    - publish-adp-image-internal
    - publish-adp-image-internal-fips
  script:
    - |-
      cat <<EOF
      # Image Tags

      ## Agent Data Plane (suitable for internal deployments, GBI-based)
      Non-FIPS: ${IMAGE_REGISTRY}/${ADP_IMAGE_TAG}
      FIPS:     ${IMAGE_REGISTRY}/${ADP_IMAGE_TAG_FIPS}
      EOF
