[build]
rustflags = ["--cfg", "tokio_unstable"]

[env]
JEMALLOC_SYS_WITH_MALLOC_CONF = "abort_conf:true,max_background_threads:2,narenas:2,tcache_max:1024,oversize_threshold:65536,dirty_decay_ms:1000,muzzy_decay_ms:1000"
