use std::hint::black_box;

use criterion::{criterion_group, criterion_main, Bencher, Criterion, Throughput};
use saluki_components::bench::is_normalized_ascii_tag_scalar;

#[cfg(all(target_arch = "aarch64", not(miri)))]
use saluki_components::bench::is_normalized_ascii_tag_simd_neon;

#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
use saluki_components::bench::is_normalized_ascii_tag_simd_sse2;

// The following arrays are sample "realistic" tag and tag values generated by codex used for testing only.
const HTTP_ATTRIBUTE_VALUES: &[&str] = &[
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "200",
    "201",
    "204",
    "301",
    "302",
    "400",
    "401",
    "403",
    "404",
    "429",
    "500",
    "502",
    "503",
    "504",
    "/api/v1/users/12345",
    "/api/v2/orders?status=pending&limit=50",
    "/health",
    "/readyz",
    "/metrics",
    "https://api.example.com/v1/checkout",
    "https://internal.corp.net:8443/graphql",
    "http://10.0.3.42:8080/rpc/SubmitOrder",
    "application/json",
    "application/grpc",
    "text/html; charset=utf-8",
    "multipart/form-data; boundary=----WebKitFormBoundary",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "python-requests/2.31.0",
    "okhttp/4.12.0",
    "Go-http-client/2.0",
    "grpc-go/1.60.1",
    "gzip, deflate, br",
];

const GRPC_RPC_VALUES: &[&str] = &[
    "grpc",
    "grpc.health.v1.Health/Check",
    "/mycompany.payments.v1.PaymentService/Charge",
    "/opentelemetry.proto.collector.trace.v1.TraceService/Export",
    "OK",
    "CANCELLED",
    "UNKNOWN",
    "DEADLINE_EXCEEDED",
    "NOT_FOUND",
    "ALREADY_EXISTS",
    "PERMISSION_DENIED",
    "RESOURCE_EXHAUSTED",
    "UNIMPLEMENTED",
    "INTERNAL",
    "UNAVAILABLE",
    "DATA_LOSS",
    "UNAUTHENTICATED",
];

const DATABASE_VALUES: &[&str] = &[
    "postgresql",
    "mysql",
    "redis",
    "mongodb",
    "elasticsearch",
    "cassandra",
    "memcached",
    "mssql",
    "oracle",
    "cockroachdb",
    "SELECT * FROM users WHERE id = $1",
    "INSERT INTO orders (user_id, total, status) VALUES ($1, $2, $3) RETURNING id",
    "UPDATE inventory SET quantity = quantity - $1 WHERE sku = $2 AND quantity >= $1",
    "DELETE FROM sessions WHERE expires_at < NOW()",
    "BEGIN; SELECT ... FOR UPDATE; COMMIT",
    "SET user:session:abc123 EX 3600",
    "GET user:session:abc123",
    "HGETALL cart:user:98765",
    "ZADD leaderboard 1500 player42",
    "db.example.com:5432",
    "redis-cluster.internal.svc.cluster.local:6379",
    "mongodb+srv://analytics-cluster.abc12.mongodb.net",
    "users",
    "orders",
    "payments_ledger",
    "audit_logs",
    "session_store",
    "myapp_production",
    "analytics_warehouse",
];

const CLOUD_INFRA_VALUES: &[&str] = &[
    "aws",
    "gcp",
    "azure",
    "us-east-1",
    "us-west-2",
    "eu-west-1",
    "ap-southeast-1",
    "eu-central-1",
    "us-central1",
    "europe-west4",
    "eastus2",
    "westeurope",
    "i-0a1b2c3d4e5f67890",
    "i-09abcdef012345678",
    "arn:aws:ecs:us-east-1:123456789012:task/my-cluster/abc123def456",
    "arn:aws:lambda:us-west-2:123456789012:function:process-orders",
    "arn:aws:sqs:us-east-1:123456789012:order-events.fifo",
    "arn:aws:s3:::my-data-lake-bucket",
    "projects/my-gcp-project-123/zones/us-central1-a/instances/worker-node-01",
    "/subscriptions/a1b2c3d4-e5f6-7890-abcd-ef1234567890/resourceGroups/my-rg",
    "123456789012",
    "my-gcp-project-prod",
    "ec2",
    "ecs",
    "fargate",
    "lambda",
    "cloud-run",
    "cloud-functions",
    "azure-functions",
];

const KUBERNETES_VALUES: &[&str] = &[
    "payment-service-7b8f9c6d4-xk2lm",
    "api-gateway-5d4f8a9b2-q8r3n",
    "order-processor-6c7d8e9f0-abc12",
    "cache-warmer-cronjob-28432100-wt5pk",
    "istio-proxy",
    "envoy-sidecar",
    "default",
    "production",
    "staging",
    "kube-system",
    "istio-system",
    "monitoring",
    "cert-manager",
    "payment-service",
    "api-gateway",
    "order-processor",
    "user-service",
    "notification-worker",
    "ip-10-0-42-137.ec2.internal",
    "gke-prod-cluster-default-pool-abc12345-d6ef",
    "aks-nodepool1-12345678-vmss000001",
    "v1",
    "apps/v1",
    "batch/v1",
    "Deployment",
    "StatefulSet",
    "DaemonSet",
    "CronJob",
    "docker://sha256:abc123def456789012345678901234567890123456789012345678901234",
    "containerd://e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5",
];

const SERVICE_IDENTITY_VALUES: &[&str] = &[
    "checkout-service",
    "inventory-manager",
    "recommendation-engine",
    "fraud-detection",
    "email-sender",
    "analytics-pipeline",
    "auth-proxy",
    "rate-limiter",
    "1.42.0",
    "2.0.0-rc.3",
    "3.14.1-beta+build.2024",
    "v5.2.1",
    "0.9.0-alpha.1",
    "abc123de",
    "f47ac10b58cc4372a5670e02b2c3d479",
    "production",
    "staging",
    "canary",
    "blue",
    "green",
    "development",
    "load-test",
    "shadow",
];

const MESSAGING_VALUES: &[&str] = &[
    "kafka",
    "rabbitmq",
    "amazon_sqs",
    "google_pubsub",
    "azure_servicebus",
    "nats",
    "pulsar",
    "order-events",
    "user-signups",
    "payment-completed",
    "inventory-updates.fifo",
    "dead-letter-queue",
    "notifications.push.high-priority",
    "publish",
    "receive",
    "process",
    "consumer-group-checkout-v2",
    "partition-3",
    "0",
    "42",
    "107839452",
];

const ERROR_EXCEPTION_VALUES: &[&str] = &[
    "java.lang.NullPointerException",
    "java.util.concurrent.TimeoutException",
    "io.grpc.StatusRuntimeException",
    "org.postgresql.util.PSQLException",
    "com.amazonaws.services.s3.model.AmazonS3Exception",
    "RuntimeError",
    "ConnectionError",
    "TimeoutError",
    "ValueError",
    "KeyError",
    "requests.exceptions.ConnectionError",
    "sqlalchemy.exc.OperationalError",
    "TypeError: Cannot read properties of undefined (reading 'map')",
    "Error: ECONNREFUSED 10.0.3.42:5432",
    "ActiveRecord::ConnectionTimeoutError",
    "Npgsql.NpgsqlException",
    "System.Net.Http.HttpRequestException",
    "System.Threading.Tasks.TaskCanceledException",
    "Connection refused (os error 111)",
    "deadline exceeded after 30.000s",
    "context canceled",
    "connection pool exhausted: all 25 connections in use",
    "FATAL: too many connections for role \"app_user\"",
];

const NETWORK_PEER_VALUES: &[&str] = &[
    "10.0.3.42",
    "10.244.1.17",
    "192.168.1.100",
    "172.16.0.55",
    "2001:db8::1",
    "::1",
    "fe80::1%eth0",
    "api.example.com",
    "db-primary.internal.svc.cluster.local",
    "cache-001.abc123.0001.usw2.cache.amazonaws.com",
    "payments-lb-1234567890.us-east-1.elb.amazonaws.com",
    "8080",
    "5432",
    "6379",
    "27017",
    "443",
    "9092",
    "tcp",
    "udp",
    "unix",
];

const RUNTIME_PROCESS_VALUES: &[&str] = &[
    "CPython",
    "PyPy",
    "OpenJDK 64-Bit Server VM",
    "Node.js",
    "Go",
    "3.11.7",
    "21.0.1+12",
    "20.11.0",
    "1.21.6",
    "linux",
    "darwin",
    "windows",
    "amd64",
    "arm64",
    "x86_64",
];

const CUSTOM_BUSINESS_VALUES: &[&str] = &[
    "premium",
    "free-tier",
    "enterprise",
    "trial",
    "user-12345678-abcd-ef01-2345-6789abcdef01",
    "org_98765",
    "team-platform-infrastructure",
    "feature-flag:dark-mode-v2",
    "experiment:checkout-flow-b",
    "A/B test: new-pricing-page",
    "tenant:acme-corp",
    "region:emea",
    "shard:07",
    "circuit-breaker:open",
    "circuit-breaker:half-open",
    "circuit-breaker:closed",
    "retry-attempt:3",
    "cache:hit",
    "cache:miss",
    "sync",
    "async",
    "batch",
    "real-time",
    "idempotency-key:550e8400-e29b-41d4-a716-446655440000",
];

const TRACING_PROPAGATION_VALUES: &[&str] = &[
    "server",
    "client",
    "producer",
    "consumer",
    "internal",
    "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01",
    "parent",
    "child",
    "follows_from",
    "link",
];

const OTEL_RESOURCE_VALUES: &[&str] = &[
    "opentelemetry-java",
    "opentelemetry-python",
    "opentelemetry-go",
    "opentelemetry-dotnet",
    "opentelemetry-js",
    "1.33.0",
    "0.46b0",
    "otlp",
    "zipkin",
    "jaeger",
];

const EDGE_CASE_VALUES: &[&str] = &[
    "N/A",
    "null",
    "None",
    "undefined",
    "",
    " ",
    "true",
    "false",
    "<unknown>",
    "[redacted]",
    "***",
    "  leading-and-trailing-spaces  ",
    "value with  multiple   spaces",
    "path/to/something.min.js:42:17",
    "key=value&other=123",
    "José García",
    "日本語テスト",
    "München",
    "São Paulo",
    "naïve-café-résumé",
    "price: €42.50",
    "temperature: 98.6°F",
    "emoji-status: ✅",
    "queue: «high-priority»",
    "file:///var/log/app.log",
    "C:\\Users\\deploy\\app\\config.yaml",
    "/var/run/secrets/kubernetes.io/serviceaccount/token",
    "sha256:a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
    "1234567890",
    "-1",
    "3.14159",
    "1.706e+09",
    "2024-12-15T09:30:00.123456789Z",
    "2024-12-15 09:30:00 +0000 UTC",
    "PT30S",
    "500ms",
    "127.0.0.1:8080 -> 10.0.3.42:5432",
    "TLSv1.3",
    "ECDHE-RSA-AES256-GCM-SHA384",
];

const OTLP_TAG_VALUE_DATASETS: &[(&str, &[&str])] = &[
    ("http_attributes", HTTP_ATTRIBUTE_VALUES),
    ("grpc_rpc", GRPC_RPC_VALUES),
    ("database", DATABASE_VALUES),
    ("cloud_infrastructure", CLOUD_INFRA_VALUES),
    ("kubernetes", KUBERNETES_VALUES),
    ("service_identity", SERVICE_IDENTITY_VALUES),
    ("messaging", MESSAGING_VALUES),
    ("error_exception", ERROR_EXCEPTION_VALUES),
    ("network_peer", NETWORK_PEER_VALUES),
    ("runtime_process", RUNTIME_PROCESS_VALUES),
    ("custom_business", CUSTOM_BUSINESS_VALUES),
    ("tracing_propagation", TRACING_PROPAGATION_VALUES),
    ("otel_resource", OTEL_RESOURCE_VALUES),
    ("edge_cases", EDGE_CASE_VALUES),
];

fn bench_is_normalized<F>(is_normalized_fn: F) -> impl FnMut(&mut Bencher<'_>)
where
    F: Fn(&[u8]) -> bool,
{
    move |b| {
        b.iter(|| {
            for (_, values) in black_box(OTLP_TAG_VALUE_DATASETS) {
                for &value in values.iter() {
                    black_box(is_normalized_fn(value.as_bytes()));
                }
            }
        });
    }
}

fn bench_is_normalized_tag(c: &mut Criterion) {
    let mut group = c.benchmark_group("is_normalized_tag/realistic_otlp_values");
    let total_bytes = OTLP_TAG_VALUE_DATASETS
        .iter()
        .map(|(_, values)| values.iter().map(|value| value.len()).sum::<usize>())
        .sum::<usize>() as u64;
    group.throughput(Throughput::Bytes(total_bytes));

    group.bench_function("scalar", bench_is_normalized(is_normalized_ascii_tag_scalar));
    #[cfg(all(target_arch = "aarch64", not(miri)))]
    group.bench_function(
        "simd/neon",
        bench_is_normalized(|bytes| unsafe { is_normalized_ascii_tag_simd_neon(bytes) }),
    );
    #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
    group.bench_function(
        "simd/sse2",
        bench_is_normalized(|bytes| unsafe { is_normalized_ascii_tag_simd_sse2(bytes) }),
    );
    group.finish();
}

criterion_group!(benches, bench_is_normalized_tag);
criterion_main!(benches);
