[package]
name = "piecemeal-dd-proto-test"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Internal dependencies.
datadog-protos = { workspace = true }
piecemeal = { workspace = true }

# External dependencies.
base64 = { version = "0.22.1" }