# Docs: https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099/User+guide+dd-octo-sts
issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/saluki:ref:refs/heads/main

claim_pattern:
  event_name: push
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/saluki/\.github/workflows/docs\.yml@refs/heads/main

permissions:
  contents: write
