# Docs: https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099/User+guide+dd-octo-sts
issuer: https://token.actions.githubusercontent.com

subject_pattern: repo:DataDog/saluki:ref:refs/tags/[0-9]+\.[0-9]+\.[0-9]+

claim_pattern:
  event_name: (push|workflow_dispatch)
  ref: refs/tags/[0-9]+\.[0-9]+\.[0-9]+
  ref_protected: "false"
  job_workflow_ref: DataDog/saluki/\.github/workflows/bump-adp-version\.yml@refs/tags/[0-9]+\.[0-9]+\.[0-9]+

permissions:
  contents: write
  pull_requests: write
