[package]
name = "datadog-intake"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[dependencies]
axum = { workspace = true, features = ["http1", "json", "tokio"] }
datadog-protos = { workspace = true }
protobuf = { workspace = true }
saluki-error = { workspace = true }
stele = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "signal",
] }
tower-http = { workspace = true, features = [
  "compression-zstd",
  "decompression-deflate",
  "decompression-zstd",
] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
  "ansi",
  "env-filter",
  "fmt",
  "local-time",
  "registry",
  "std",
  "tracing-log",
] }
