use std::fmt::Write as _;
use std::path::PathBuf;

use datadog_agent_config_overlay_model::schema_gen::{self, FieldInfo, FieldType};
use datadog_agent_config_overlay_model::smoke_test_support::ConfigurationStruct;
use datadog_agent_config_overlay_model::{Files, KnownEntry, SchemaOverlay, TestSupport};
use indexmap::IndexMap;

fn main() {
    let files = Files::default();

    let schema_dir = files.schema.parent().expect("schema file must have a parent directory");
    println!("cargo:rerun-if-changed={}", schema_dir.display());
    println!("cargo:rerun-if-changed={}", files.overlay.display());
    println!("cargo:rerun-if-changed=build.rs");

    let schema_path = files.schema.clone();
    let overlay = SchemaOverlay::load(files).unwrap_or_else(|e| panic!("{e}"));
    let schema_map = schema_gen::load_schema(&schema_path);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    generate_smoke_tests(&overlay, &schema_map, &out_dir);
}

fn generate_smoke_tests(overlay: &SchemaOverlay, schema_map: &IndexMap<String, FieldInfo>, out_dir: &std::path::Path) {
    let mut keys: Vec<(&str, &TestSupport, &FieldInfo)> = Vec::new();

    for (yaml_path, entry) in &overlay.inventory {
        let ts = match entry {
            KnownEntry::Full(f) => &f.test_support,
            KnownEntry::Partial(p) => &p.test_support,
            _ => continue,
        };
        if !ts.used_by.contains(&ConfigurationStruct::MigratedToConfigSystem) {
            continue;
        }
        let field_info = schema_map
            .get(yaml_path.as_str())
            .unwrap_or_else(|| panic!("MigratedToConfigSystem key '{}' not found in schema", yaml_path));
        keys.push((yaml_path.as_str(), ts, field_info));
    }

    keys.sort_by_key(|(path, _, _)| *path);

    let mut out = String::new();
    writeln!(out, "// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT").unwrap();
    writeln!(out).unwrap();

    for (yaml_path, ts, field_info) in &keys {
        let fn_name = yaml_path.replace('.', "_");
        let test_value = resolve_test_value(yaml_path, ts, field_info);

        writeln!(out, "#[tokio::test]").unwrap();
        writeln!(out, "async fn smoke_{fn_name}() {{").unwrap();
        writeln!(out, "    assert_key_propagates(\"{yaml_path}\", {test_value}).await;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    let path = out_dir.join("translation_smoke_tests.rs");
    std::fs::write(&path, out).unwrap_or_else(|e| panic!("cannot write {}: {}", path.display(), e));
}

fn resolve_test_value(yaml_path: &str, ts: &TestSupport, field_info: &FieldInfo) -> String {
    if let Some(ref test_json) = ts.test_json {
        return format_json_literal(test_json);
    }

    let effective_type = ts
        .value_type_override
        .as_ref()
        .map_or(&field_info.value_type, |vt| match vt {
            datadog_agent_config_overlay_model::ValueType::Boolean => &FieldType::Bool,
            datadog_agent_config_overlay_model::ValueType::Integer => &FieldType::Integer,
            datadog_agent_config_overlay_model::ValueType::Float => &FieldType::Float,
            datadog_agent_config_overlay_model::ValueType::String => &FieldType::String,
            datadog_agent_config_overlay_model::ValueType::StringList => &FieldType::StringList,
        });

    match effective_type {
        FieldType::Bool => {
            let default_is_true = field_info
                .default
                .as_deref()
                .map(|d| d.trim() == "true")
                .unwrap_or(false);
            if default_is_true {
                "serde_json::json!(false)".to_string()
            } else {
                "serde_json::json!(true)".to_string()
            }
        }
        FieldType::Integer => "serde_json::json!(42i64)".to_string(),
        FieldType::Float => "serde_json::json!(1.5f64)".to_string(),
        FieldType::String => "serde_json::json!(\"http://smoke-test.example.com:3128\")".to_string(),
        FieldType::StringList => {
            "serde_json::json!([\"smoke-host-1.example.com\", \"smoke-host-2.example.com\"])".to_string()
        }
        FieldType::Unknown => {
            panic!("MigratedToConfigSystem key '{yaml_path}' has unknown type and no test_json override");
        }
    }
}

fn format_json_literal(raw: &str) -> String {
    if raw.contains('"') {
        format!("serde_json::from_str::<serde_json::Value>(r#\"{raw}\"#).unwrap()")
    } else {
        format!("serde_json::json!({raw})")
    }
}
