/// Datadog Agent configuration annotations, generated from `schema_overlay.yaml`.
///
/// Type definitions live here (hand-written); generated annotation constants and statics
/// live in `annotations_index.rs` (generated in-tree by `build.rs`).
pub use datadog_agent_config::classifier::{structs, Pipeline, PipelineAffinity, Severity};

/// Support level for a configuration key, as recorded in the testsupport annotation layer.
///
/// Unlike the prod [`datadog_agent_config::classifier::SupportLevel`], this enum includes
/// [`Full`][SupportLevel::Full] so that generated annotation constants can express keys that work
/// identically to the core agent. The prod classifier omits `Full` because fully supported keys
/// require no diagnostic action.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SupportLevel {
    /// Fully supported with identical behavior to the core agent.
    Full,
    /// Supported but with behavioral or default-value differences.
    Partial,
    /// Explicitly incompatible; ADP does not support this key.
    Incompatible(Severity),
    /// Intentionally ignored.
    #[allow(unused)]
    Ignored,
    /// Unrecognized by ADP.
    #[allow(unused)]
    Unrecognized,
}

/// Declares a set of [`SalukiAnnotation`] constants and generates a companion `ALL` slice.
///
/// Each entry declares one named `pub const` annotation. The macro also emits:
///
/// ```ignore
/// pub const ALL: &[&SalukiAnnotation] = &[&NAME1, &NAME2, ...];
/// ```
///
/// so that `annotations_index.rs` can aggregate submodules with a single
/// `v.extend_from_slice(my_module::ALL)` line rather than listing every constant by name.
#[macro_export]
macro_rules! declare_annotations {
    ( $( $(#[$attr:meta])* $name:ident = $val:expr ;)+ ) => {
        $(
            $(#[$attr])*
            pub const $name: $crate::config_registry::SalukiAnnotation = $val;
        )+

        /// All annotations declared in this module, in declaration order.
        pub const ALL: &[$crate::config_registry::SalukiAnnotationRef] = &[
            $( &$name, )+
        ];
    };
}

/// The shape of a configuration value.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ValueType {
    /// A boolean (`true` / `false`).
    Bool,
    /// A UTF-8 string.
    String,
    /// An unsigned integer.
    Integer,
    /// A floating-point number.
    Float,
    /// A list of strings (YAML sequence or space-separated env var string).
    StringList,
}

/// Which schema source of truth defined the `SchemaEntry`
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
#[repr(u8)]
pub(crate) enum Schema {
    /// Saluki defined the `SchemaEntry`.
    Saluki,
    /// The vendored Datadog config schema defines the `SchemaEntry`.
    Datadog,
}

/// Schema-derived metadata for a single configuration key.
#[derive(Debug)]
pub struct SchemaEntry {
    /// The source of truth from which this entry was derived.
    #[allow(dead_code)]
    pub(crate) schema: Schema,

    /// Canonical dot-separated YAML path for this key (for example, `"proxy.http"`).
    pub yaml_path: &'static str,

    /// Environment variables that deliver this value, as declared in the schema.
    pub env_vars: &'static [&'static str],

    /// Shape of the value.
    pub value_type: ValueType,

    /// JSON-encoded default value from the Agent schema, if present.
    pub default: Option<&'static str>,
}

/// Saluki-specific annotation for a single configuration key.
#[derive(Debug)]
pub struct SalukiAnnotation {
    /// The schema entry this annotation enriches.
    pub schema: &'static SchemaEntry,

    /// How well saluki supports this key.
    pub support_level: SupportLevel,

    /// Additional YAML paths beyond the canonical one in the schema (aliases).
    pub additional_yaml_paths: &'static [&'static str],

    /// Overrides the schema's `env_vars` list entirely when `Some`.
    pub env_var_override: Option<&'static [&'static str]>,

    /// Config structs that incorporate this key, as [`structs`] constants.
    pub used_by: &'static [&'static str],

    /// Overrides the schema's `value_type` when `Some`.
    pub value_type_override: Option<ValueType>,

    /// Overrides the smoke-test injected value entirely when `Some`.
    pub test_json: Option<&'static str>,

    /// Which pipelines this key affects.
    pub pipeline_affinity: PipelineAffinity,
}

/// A reference to a [`SalukiAnnotation`], used as the element type of `ALL` slices generated by
/// [`declare_annotations!`].
pub type SalukiAnnotationRef = &'static SalukiAnnotation;

impl SalukiAnnotation {
    /// The canonical YAML path for this key (from the schema).
    pub fn yaml_path(&self) -> &'static str {
        self.schema.yaml_path
    }

    /// All YAML paths for this key: canonical first, then any aliases.
    pub fn all_yaml_paths(&self) -> impl Iterator<Item = &'static str> {
        std::iter::once(self.schema.yaml_path).chain(self.additional_yaml_paths.iter().copied())
    }

    /// Effective env vars: the override list if set, otherwise the schema's list.
    pub fn effective_env_vars(&self) -> &'static [&'static str] {
        self.env_var_override.unwrap_or(self.schema.env_vars)
    }

    /// Shape of the value: override if set, otherwise from the schema.
    pub fn value_type(&self) -> ValueType {
        self.value_type_override.unwrap_or(self.schema.value_type)
    }
}

/// A fully resolved configuration key.
#[derive(Debug)]
pub struct ConfigKey {
    /// All dot-separated YAML paths that deliver this value.
    pub yaml_paths: Vec<&'static str>,

    /// All environment variables that deliver this value.
    pub env_vars: Vec<&'static str>,

    /// Shape of the value.
    pub value_type: ValueType,

    /// Config structs that incorporate this key, as [`structs`] constants.
    pub used_by: &'static [&'static str],
}

impl From<&SalukiAnnotation> for ConfigKey {
    fn from(a: &SalukiAnnotation) -> Self {
        ConfigKey {
            yaml_paths: a.all_yaml_paths().collect(),
            env_vars: a.effective_env_vars().to_vec(),
            value_type: a.value_type(),
            used_by: a.used_by,
        }
    }
}

// Generated module containing all annotation constants and the aggregation statics.
include!("annotations_index.rs");
