// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `dogstatsd_disable_verbose_logs`-Suppress noisy parse error logs
    DOGSTATSD_DISABLE_VERBOSE_LOGS = SalukiAnnotation {
        schema: &schema::DOGSTATSD_DISABLE_VERBOSE_LOGS,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_pipe_name`-Windows named pipe path
    DOGSTATSD_PIPE_NAME = SalukiAnnotation {
        schema: &schema::DOGSTATSD_PIPE_NAME,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_stats_buffer`-Internal stats buffer size
    DOGSTATSD_STATS_BUFFER = SalukiAnnotation {
        schema: &schema::DOGSTATSD_STATS_BUFFER,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_stats_enable`-Enable internal stats endpoint
    DOGSTATSD_STATS_ENABLE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_STATS_ENABLE,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_stats_port`-Internal stats endpoint port
    DOGSTATSD_STATS_PORT = SalukiAnnotation {
        schema: &schema::DOGSTATSD_STATS_PORT,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_telemetry_enabled_listener_id`-Per-listener telemetry tagging
    DOGSTATSD_TELEMETRY_ENABLED_LISTENER_ID = SalukiAnnotation {
        schema: &schema::DOGSTATSD_TELEMETRY_ENABLED_LISTENER_ID,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_windows_pipe_security_descriptor`-Windows named pipe ACL descriptor
    DOGSTATSD_WINDOWS_PIPE_SECURITY_DESCRIPTOR = SalukiAnnotation {
        schema: &schema::DOGSTATSD_WINDOWS_PIPE_SECURITY_DESCRIPTOR,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `forwarder_apikey_validation_interval`-API key check interval (minutes)
    FORWARDER_APIKEY_VALIDATION_INTERVAL = SalukiAnnotation {
        schema: &schema::FORWARDER_APIKEY_VALIDATION_INTERVAL,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_flush_to_disk_mem_ratio`-Mem-to-disk flush threshold
    FORWARDER_FLUSH_TO_DISK_MEM_RATIO = SalukiAnnotation {
        schema: &schema::FORWARDER_FLUSH_TO_DISK_MEM_RATIO,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_low_prio_buffer_size`-Low-priority request queue size
    FORWARDER_LOW_PRIO_BUFFER_SIZE = SalukiAnnotation {
        schema: &schema::FORWARDER_LOW_PRIO_BUFFER_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_max_concurrent_requests`-Max concurrent HTTP requests
    FORWARDER_MAX_CONCURRENT_REQUESTS = SalukiAnnotation {
        schema: &schema::FORWARDER_MAX_CONCURRENT_REQUESTS,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_retry_queue_capacity_time_interval_sec`-Retry queue time-based capacity
    FORWARDER_RETRY_QUEUE_CAPACITY_TIME_INTERVAL_SEC = SalukiAnnotation {
        schema: &schema::FORWARDER_RETRY_QUEUE_CAPACITY_TIME_INTERVAL_SEC,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `serializer_experimental_use_v3_api.compression_level`-V3 API zstd compression level
    SERIALIZER_EXPERIMENTAL_USE_V3_API_COMPRESSION_LEVEL = SalukiAnnotation {
        schema: &schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_COMPRESSION_LEVEL,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `serializer_experimental_use_v3_api.series.endpoints`-Endpoints enabled for V3 series API
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_ENDPOINTS = SalukiAnnotation {
        schema: &schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_ENDPOINTS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `serializer_experimental_use_v3_api.series.validate`-Dual-send v2+v3 series for validation
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_VALIDATE = SalukiAnnotation {
        schema: &schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_VALIDATE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `serializer_experimental_use_v3_api.sketches.endpoints`-Endpoints enabling v3 sketches API
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_ENDPOINTS = SalukiAnnotation {
        schema: &schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_ENDPOINTS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `serializer_experimental_use_v3_api.sketches.validate`-Dual-send v2+v3 sketches for validation
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_VALIDATE = SalukiAnnotation {
        schema: &schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_VALIDATE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `sslkeylogfile`-TLS key log file path
    SSLKEYLOGFILE = SalukiAnnotation {
        schema: &schema::SSLKEYLOGFILE,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `tls_handshake_timeout`-HTTP TLS handshake timeout
    TLS_HANDSHAKE_TIMEOUT = SalukiAnnotation {
        schema: &schema::TLS_HANDSHAKE_TIMEOUT,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `aggregator_buffer_size`-Channel buffer depth for aggregator queues
    AGGREGATOR_BUFFER_SIZE = SalukiAnnotation {
        schema: &schema::AGGREGATOR_BUFFER_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `aggregator_flush_metrics_and_serialize_in_parallel_buffer_size`-Parallel flush: series/sketch buffer size
    AGGREGATOR_FLUSH_METRICS_AND_SERIALIZE_IN_PARALLEL_BUFFER_SIZE = SalukiAnnotation {
        schema: &schema::AGGREGATOR_FLUSH_METRICS_AND_SERIALIZE_IN_PARALLEL_BUFFER_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `aggregator_flush_metrics_and_serialize_in_parallel_chan_size`-Parallel flush: channel size
    AGGREGATOR_FLUSH_METRICS_AND_SERIALIZE_IN_PARALLEL_CHAN_SIZE = SalukiAnnotation {
        schema: &schema::AGGREGATOR_FLUSH_METRICS_AND_SERIALIZE_IN_PARALLEL_CHAN_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `aggregator_stop_timeout`-Timeout (s) for aggregator flush on stop
    AGGREGATOR_STOP_TIMEOUT = SalukiAnnotation {
        schema: &schema::AGGREGATOR_STOP_TIMEOUT,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `aggregator_use_tags_store`-Enable shared tag deduplication store
    AGGREGATOR_USE_TAGS_STORE = SalukiAnnotation {
        schema: &schema::AGGREGATOR_USE_TAGS_STORE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `autoscaling.failover.enabled`-Enable autoscaling failover metric routing
    AUTOSCALING_FAILOVER_ENABLED = SalukiAnnotation {
        schema: &schema::AUTOSCALING_FAILOVER_ENABLED,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `autoscaling.failover.metrics`-Metric names forwarded to DCA for failover
    AUTOSCALING_FAILOVER_METRICS = SalukiAnnotation {
        schema: &schema::AUTOSCALING_FAILOVER_METRICS,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `dogstatsd_experimental_http.enabled`-Enable experimental HTTP/H2C DSD listener
    DOGSTATSD_EXPERIMENTAL_HTTP_ENABLED = SalukiAnnotation {
        schema: &schema::DOGSTATSD_EXPERIMENTAL_HTTP_ENABLED,
        support_level: SupportLevel::Incompatible(Severity::High),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_experimental_http.listen_address`-Bind address for experimental HTTP DSD listener
    DOGSTATSD_EXPERIMENTAL_HTTP_LISTEN_ADDRESS = SalukiAnnotation {
        schema: &schema::DOGSTATSD_EXPERIMENTAL_HTTP_LISTEN_ADDRESS,
        support_level: SupportLevel::Incompatible(Severity::High),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `forwarder_requeue_buffer_size`-In-memory re-queue buffer size
    FORWARDER_REQUEUE_BUFFER_SIZE = SalukiAnnotation {
        schema: &schema::FORWARDER_REQUEUE_BUFFER_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_stop_timeout`-Timeout (s) for forwarder graceful stop
    FORWARDER_STOP_TIMEOUT = SalukiAnnotation {
        schema: &schema::FORWARDER_STOP_TIMEOUT,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `heroku_dyno`-Heroku dyno telemetry mode
    HEROKU_DYNO = SalukiAnnotation {
        schema: &schema::HEROKU_DYNO,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `telemetry.dogstatsd.aggregator_channel_latency_buckets`-Histogram buckets: DSD aggregator channel lag
    TELEMETRY_DOGSTATSD_AGGREGATOR_CHANNEL_LATENCY_BUCKETS = SalukiAnnotation {
        schema: &schema::TELEMETRY_DOGSTATSD_AGGREGATOR_CHANNEL_LATENCY_BUCKETS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `telemetry.dogstatsd.listeners_channel_latency_buckets`-Histogram buckets: listener channel latency
    TELEMETRY_DOGSTATSD_LISTENERS_CHANNEL_LATENCY_BUCKETS = SalukiAnnotation {
        schema: &schema::TELEMETRY_DOGSTATSD_LISTENERS_CHANNEL_LATENCY_BUCKETS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `telemetry.dogstatsd.listeners_latency_buckets`-Histogram buckets: listener processing
    TELEMETRY_DOGSTATSD_LISTENERS_LATENCY_BUCKETS = SalukiAnnotation {
        schema: &schema::TELEMETRY_DOGSTATSD_LISTENERS_LATENCY_BUCKETS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `telemetry.dogstatsd_origin`-Per-origin processed-metrics telemetry
    TELEMETRY_DOGSTATSD_ORIGIN = SalukiAnnotation {
        schema: &schema::TELEMETRY_DOGSTATSD_ORIGIN,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `cluster_agent.enabled`-Enable Cluster Agent communication
    CLUSTER_AGENT_ENABLED = SalukiAnnotation {
        schema: &schema::CLUSTER_AGENT_ENABLED,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `config_id`-Fleet Automation config ID tag
    CONFIG_ID = SalukiAnnotation {
        schema: &schema::CONFIG_ID,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `dogstatsd_host_socket_path`-Host UDS socket dir for DSD
    DOGSTATSD_HOST_SOCKET_PATH = SalukiAnnotation {
        schema: &schema::DOGSTATSD_HOST_SOCKET_PATH,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.enabled`-Memory-based rate limiter toggle
    DOGSTATSD_MEM_BASED_RATE_LIMITER_ENABLED = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_ENABLED,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.go_gc`-Memory rate limiter GC percent
    DOGSTATSD_MEM_BASED_RATE_LIMITER_GO_GC = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_GO_GC,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.high_soft_limit`-Memory rate limiter high soft limit
    DOGSTATSD_MEM_BASED_RATE_LIMITER_HIGH_SOFT_LIMIT = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_HIGH_SOFT_LIMIT,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.low_soft_limit`-Memory rate limiter low soft limit
    DOGSTATSD_MEM_BASED_RATE_LIMITER_LOW_SOFT_LIMIT = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_LOW_SOFT_LIMIT,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.memory_ballast`-Memory rate limiter heap ballast size
    DOGSTATSD_MEM_BASED_RATE_LIMITER_MEMORY_BALLAST = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_MEMORY_BALLAST,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.rate_check.factor`-Memory rate limiter check factor
    DOGSTATSD_MEM_BASED_RATE_LIMITER_RATE_CHECK_FACTOR = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_RATE_CHECK_FACTOR,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.rate_check.max`-Memory rate limiter check max interval
    DOGSTATSD_MEM_BASED_RATE_LIMITER_RATE_CHECK_MAX = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_RATE_CHECK_MAX,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.rate_check.min`-Memory rate limiter check min interval
    DOGSTATSD_MEM_BASED_RATE_LIMITER_RATE_CHECK_MIN = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_RATE_CHECK_MIN,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.soft_limit_freeos_check.factor`-Memory rate limiter FreeOS check factor
    DOGSTATSD_MEM_BASED_RATE_LIMITER_SOFT_LIMIT_FREEOS_CHECK_FACTOR = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_SOFT_LIMIT_FREEOS_CHECK_FACTOR,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.soft_limit_freeos_check.max`-Memory rate limiter FreeOS check max
    DOGSTATSD_MEM_BASED_RATE_LIMITER_SOFT_LIMIT_FREEOS_CHECK_MAX = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_SOFT_LIMIT_FREEOS_CHECK_MAX,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_mem_based_rate_limiter.soft_limit_freeos_check.min`-Memory rate limiter FreeOS check min
    DOGSTATSD_MEM_BASED_RATE_LIMITER_SOFT_LIMIT_FREEOS_CHECK_MIN = SalukiAnnotation {
        schema: &schema::DOGSTATSD_MEM_BASED_RATE_LIMITER_SOFT_LIMIT_FREEOS_CHECK_MIN,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_no_aggregation_pipeline_batch_size`-No-aggregation pipeline batch size
    DOGSTATSD_NO_AGGREGATION_PIPELINE_BATCH_SIZE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_NO_AGGREGATION_PIPELINE_BATCH_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_packet_buffer_flush_timeout`-Packet buffer flush timeout
    DOGSTATSD_PACKET_BUFFER_FLUSH_TIMEOUT = SalukiAnnotation {
        schema: &schema::DOGSTATSD_PACKET_BUFFER_FLUSH_TIMEOUT,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_packet_buffer_size`-Datagrams per packet buffer
    DOGSTATSD_PACKET_BUFFER_SIZE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_PACKET_BUFFER_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_pipeline_autoadjust`-Auto-adjust pipeline workers
    DOGSTATSD_PIPELINE_AUTOADJUST = SalukiAnnotation {
        schema: &schema::DOGSTATSD_PIPELINE_AUTOADJUST,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_pipeline_count`-Parallel processing pipelines
    DOGSTATSD_PIPELINE_COUNT = SalukiAnnotation {
        schema: &schema::DOGSTATSD_PIPELINE_COUNT,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_queue_size`-Packet channel buffer size
    DOGSTATSD_QUEUE_SIZE = SalukiAnnotation {
        schema: &schema::DOGSTATSD_QUEUE_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_workers_count`-Number of DSD processing workers
    DOGSTATSD_WORKERS_COUNT = SalukiAnnotation {
        schema: &schema::DOGSTATSD_WORKERS_COUNT,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `enable_json_stream_shared_compressor_buffers`-Pre-allocate shared compressor buffers
    ENABLE_JSON_STREAM_SHARED_COMPRESSOR_BUFFERS = SalukiAnnotation {
        schema: &schema::ENABLE_JSON_STREAM_SHARED_COMPRESSOR_BUFFERS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `entity_id`-Agent pod entity ID
    ENTITY_ID = SalukiAnnotation {
        schema: &schema::ENTITY_ID,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `logging_frequency`-Transaction success log interval
    LOGGING_FREQUENCY = SalukiAnnotation {
        schema: &schema::LOGGING_FREQUENCY,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `use_dogstatsd`-Master DogStatsD enable toggle
    USE_DOGSTATSD = SalukiAnnotation {
        schema: &schema::USE_DOGSTATSD,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
}
