[package]
name = "checks-agent"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[features]
default = []

[dependencies]
memory-accounting = { workspace = true }
mimalloc = { workspace = true, features = ["no_thp"] }
saluki-app = { workspace = true, features = ["full"] }
saluki-components = { workspace = true, features = ["python-checks"] }
saluki-config = { workspace = true }
saluki-core = { workspace = true }
saluki-env = { workspace = true }
saluki-error = { workspace = true }
saluki-health = { workspace = true }
saluki-io = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "signal",
] }
tokio-rustls = { workspace = true }
tracing = { workspace = true }
