[package]
name = "checks-agent"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
memory-accounting = { workspace = true }
saluki-app = { workspace = true, features = ["full"] }
saluki-components = { workspace = true }
saluki-config = { workspace = true }
saluki-core = { workspace = true }
saluki-env = { workspace = true }
saluki-error = { workspace = true }
saluki-health = { workspace = true }
saluki-io = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "signal",
] }
tokio-rustls = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemalloc-ctl = { workspace = true, features = ["use_std"] }
tikv-jemallocator = { workspace = true, features = [
  "background_threads",
  "profiling",
  "unprefixed_malloc_on_supported_platforms",
  "stats",
] }

[lints]
workspace = true
