name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  label:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
    steps:
      - name: Get access token from dd-octo-sts
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/saluki
          policy: self.labeler

      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          repo-token: "${{ steps.octo-sts.outputs.token }}"
          sync-labels: true
