name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  label:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
    steps:
      - name: Get access token from dd-octo-sts
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/saluki
          policy: self.labeler

      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: "${{ steps.octo-sts.outputs.token }}"
          sync-labels: true
